Added Zenodo citation
Materials-Consortia/OPTIMADE pull request #332
Opened 2020-11-06 14:33 UTC by ml-evs

As discussed on the mailing list, this PR simply adds the Zenodo link as the current preferred citation, feel free to tweak the wording.

2020-11-06 14:35 UTC, rartino commented
Should this actually be to http://doi.org/10.5281/zenodo.4195050
or should it be http://doi.org/10.5281/zenodo.4195050
(Are we linking the latest version, or specifically version 1.0)?

2020-11-06 14:37 UTC, ml-evs commented
> Should this actually be to http://doi.org/10.5281/zenodo.4195051
> or should it be http://doi.org/10.5281/zenodo.4195050
> (Are we linking the latest version, or specifically version 1.0)?

That's a good question, I would prefer to link to the unversioned DOI (which I thought was the Zenodo default when exporting the citation) i.e. your second suggestion. Any disagreement?

2020-11-06 14:38 UTC, ml-evs commented on README.md
> +> Andersen *et al*, The OPTIMADE Specification, http://doi.org/10.5281/zenodo.4195051
```suggestion
> Andersen *et al*, The OPTIMADE Specification, http://doi.org/10.5281/zenodo.4195050
```

2020-11-06 16:03 UTC, merkys requested changes
I would suggest using HTTPS, otherwise good to go.

2020-11-06 16:03 UTC, merkys commented on README.md
> +Pending the release of an OPTIMADE paper, we kindly ask that you cite the Zenodo archive for this repository:
I assume "release" here means "opening to public" by either publication or upload to preprint server. Otherwise "publication" would be more precise.

2020-11-06 16:04 UTC, ml-evs commented on README.md
> +> Andersen *et al*, The OPTIMADE Specification, http://doi.org/10.5281/zenodo.4195051
Well spotted, added to the suggestion above. https://github.com/Materials-Consortia/OPTIMADE/pull/332#discussion_r518791983

2020-11-06 16:05 UTC, ml-evs commented on README.md
> +Pending the release of an OPTIMADE paper, we kindly ask that you cite the Zenodo archive for this repository:
That's what I was going for, agree it could be more precise. I think "publication" works for a preprint too, so I'll change it.

```suggestion
Pending the publication of an OPTIMADE paper, we kindly ask that you cite the Zenodo archive for this repository:
```

2020-11-06 16:08 UTC, ml-evs commented on README.md
> +> Andersen *et al*, The OPTIMADE Specification, http://doi.org/10.5281/zenodo.4195051
Turns out Zenodo redirects all HTTP to HTTPS anyway, but I've changed it everywhere :)

2020-11-06 16:10 UTC, merkys commented
Regarding versioned and unversioned links. I would prefer using unversioned link in `develop` branch, but at the moment of a release a link should be made versioned in order to get to stable release as such. But I guess this will lead us to egg-and-chicken problems, or not?

2020-11-06 16:14 UTC, ml-evs commented
> Regarding versioned and unversioned links. I would prefer using unversioned link in `develop` branch, but at the moment of a release a link should be made versioned in order to get to stable release as such. But I guess this will lead us to egg-and-chicken problems, or not?

This would lead to egg-chicken problems if we used the Zenodo/Github integration to automatically add a Zenodo entry for each new GitHub release, but we could take this approach if we wanted to release manually. This *may* actually be preferable as manual releases keep the manual authorship. I think the automated releases use the GitHub contributors alone, which is suboptimal...

2020-11-17 07:12 UTC, merkys approved these changes
Good to go! As before, I prefer versioned links for releases if this is not too difficult to do. If we can claim the DOI, release OPTIMADE and then update the content under DOI, this would be perfect.

2020-11-20 13:54 UTC, ml-evs commented
> Good to go! As before, I prefer versioned links for releases if this is not too difficult to do. If we can claim the DOI, release OPTIMADE and then update the content under DOI, this would be perfect.

This is technically possible, though it must be done manually. I'm a bit worried about the bus factor of all this as the Zenodo archive is done through my Zenodo account (and I don't think there's any way to give others access...). What I can do is reserve the DOI for the next versions (both patch and minor release) so we can consider this option next release.

2020-11-20 14:01 UTC, ml-evs commented
> I'm a bit worried about the bus factor of all this as the Zenodo archive is done through my Zenodo account (and I don't think there's any way to give others access...).

Relevant issue, hopefully not a problem for long:

https://github.com/zenodo/zenodo/issues/151#issuecomment-585738162

A shared account would be the other option, but my Zenodo is already linked to GH/ORCID with personal projects, so I think that's a non-starter. If the proverbial bus were to hit me, feel free to link this comment to the Zenodo admins to somehow give access to my Zenodo account to anyone nominated by Materials-Consortia. :upside_down_face:

2020-11-24 05:57 UTC, merkys commented
> A shared account would be the other option, but my Zenodo is already linked to GH/ORCID with personal projects, so I think that's a non-starter. If the proverbial bus were to hit me, feel free to link this comment to the Zenodo admins to somehow give access to my Zenodo account to anyone nominated by Materials-Consortia.

A shared account sounds really good. It would be cool if people would be allowed to transfer ownership of projects as in GitHub, but from your message I understand that this is not yet implemented in Zenodo. Hopefully, it's not for long.

2020-11-27 15:06 UTC, shyamd approved these changes

2020-12-07 19:50 UTC, merged