Adding the trajectories endpoint to OPTIMADE
Materials-Consortia/OPTIMADE pull request #377
Opened 2021-07-21 14:28 UTC by JPBergsma

During the OPTIMADE meeting in June 2021, we discussed in room 2 how the OPTIMADE standard could be expanded to allow the sharing of trajectory data. Based on the discussions with amongst others @giovannipizzi, @gmrigna, Adam Hospital, Tristan Bereau, Amit Gupta, Corey Oses, Ellad Tadmor, Maithilee Motlag, and Daniel S Karls, I have written a first draft for adding a trajectory endpoint. This will hopefully be a good base for further discussion.

The PR adds a trajectories section (in this PR section 7.3), that defines how a client can query and retrieve data from trajectories and how the server can share this data. We have tried to do this in a general way so that many different kinds of trajectories can be shared.

I will still add a few comments to the document, to show what I think would be interesting things to discuss.

2021-07-21 15:37 UTC, JPBergsma commented on optimade.rst
> +  The `reference\_structure`_ is an example of the kind of structures that are in the trajectory, and it is used to query the trajectory entries in the same way as the structures entries. The data be
As I stated at the end of this line, I have not defined anything about querying the individual frames. I did not include it because I think that, when such queries are done on many trajectories, it would take a long time for the server to process the query. Do you agree with this decision, or do you think we should define a way to query the whole trajectory?

2021-07-22 09:11 UTC, JPBergsma commented on optimade.rst
> +The preceding properties 7.3.1-4 and the fields described under `Properties Used by Multiple Entry Types`_ MUST be returned when no response\_fields property (see the section `Entry Listing URL Query
If anyone knows how to reference a section by number such that the section number is automatically updated, I would gladly hear it. Writing out all the subsection names would be the alternative, but I think this would make this sentence very long.

2021-07-22 09:49 UTC, JPBergsma commented on optimade.rst
> +    - **explicit_custom_sparse**: A separate list with frame numbers is defined in the field frame_number to indicate to which frame a value belongs.
I have listed all the options that we discussed during the meeting. We also considered that perhaps  having all these 5 options would be a bit too much, but we did not decide which ones would not be worth implementing.

2021-07-22 10:29 UTC, ml-evs reviewed
Thanks for the hard work on this @JPBergsma!

My comments below are mostly around maintaining our compliance with the [JSON:API](https://jsonapi.org/format/) format.

2021-07-22 10:29 UTC, ml-evs commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~
I think my suggestion would be to include the `reference_structure` as a mandatory `relationship` for each trajectory, so that filtering can be enabled as a relationship filter (which will probably have to become mandatory too), e.g. `/trajectories?filter=structure.elements HAS "C"`. This feels like the most JSON:API-esque way of doing this.

2021-07-22 10:29 UTC, ml-evs commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry point contains data belonging to a set of structures. These structures are related because they were, for example, created by the same procedure, e.
Sorry to be a pain, but could you please reformat this so that each sentence is on a new line (which will not incur a linebreak in rst)? This makes it easier for people to review/suggest changes on specific parts. I think we have tried to follow this for the rest of the spec. Other purely visual changes can wait until the content has been agreed upon.

2021-07-22 10:29 UTC, ml-evs commented on optimade.rst
> +  - :val:`["cartesian\_site\_positions","lattice_vectors","species",species_at_sites","_exmpl_Pressure"]`
All field names need to be lower case

```suggestion
  - :val:`["cartesian_site_positions","lattice_vectors","species",species_at_sites","_exmpl_pressure"]`
```

2021-07-22 10:29 UTC, ml-evs commented on optimade.rst
> +- **Description**: This is a link the client can use to download the remainder of the trajectory data when the server returns fewer frames than the client requested.
Could you explain how this is different to pagination in JSON:API? Could we not use the same mechanism, e.g. [a `links` field for the trajectory entry itself](https://jsonapi.org/format/#document-resource-object-links)?

2021-07-22 10:29 UTC, ml-evs commented on optimade.rst
> +    }
This is not a valid JSON:API response, this should be nested under a `"data"` field and all OPTIMADE defined fields must be nested under `"attributes"`. I've sketched this out below but it is difficult to format as a GitHub suggestion

```suggestion
.. code:: jsonc

    "data": [
      {          
         "id": "traj00000001",
         "type": "trajectories",
         "attributes": {
           "reference_structure":{
             "elements": ["H","O"],
             "nelements": 2,
             "elements_ratios": [0.666667,0.333333],
             "chemical_formula_descriptive": "H2O",
             "chemical_formula_reduced": "H2O",
             "chemical_formula_anonymous": "A2B",
             "dimension_types":[0,0,0],
             "nperiodic_dimensions": 0,
             "lattice_vectors" : [[4.0,0.0,0.0],[0.0,4.0,0.0],[0.0,0.0,4.0]],
             "cartesian_site_positions" : [[2.0,2.0,2.0],[1.238,2.0,1.416],[2.762,2.0,1.416]],
             "nsites":3,
             "species_at_sites":["O1","H1","H2"],
             "species":[
               {
                 "name":"O1",
                 "chemical_symbols":["O"],
                 "concentration":[1.0],
               },
               {
                 "name":"H1",
                 "chemical_symbols":["H"],
                 "concentration":[1.0],
               },
               {
                 "name":"H2",
                 "chemical_symbols":["H"],
                 "concentration":[1.0],
               }
             ]
          },
          "last_modified":"2021-07-16T18:02:03Z"
          "reference_frame": 359,
          "nframes": 360,
          "available_properties":[
            "cartesian_site_positions",
            "species",
            "dimension_types",
            "lattice_vectors",
            "species_at_sites",
            "_exmpl_temperature_set",
            "_exmpl_time",
            "_exmpl_ekin"
          ]
      },
      "relationships": {
        "references": {
          "data": [
            {
              "type": "references",
              "id": "dummy/2019"
            }
          ]
        }
      }
      
    },
    ...
    ]
```

2021-07-22 10:29 UTC, ml-evs commented on optimade.rst
> +.. code:: jsonc
Same comment as above, this needs `"data"`, `"attributes"` etc to be valid JSON:API

2021-07-22 11:03 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry point contains data belonging to a set of structures. These structures are related because they were, for example, created by the same procedure, e.
I have placed every sentence on a separate line.

2021-07-22 12:32 UTC, JPBergsma commented on optimade.rst
> +  - :val:`["cartesian\_site\_positions","lattice_vectors","species",species_at_sites","_exmpl_Pressure"]`
Thanks for pointing this out, I will change it in the next commit.

2021-07-22 15:46 UTC, JPBergsma commented on optimade.rst
> +  - It MAY also have a 'relationships'_ field for references that apply to the entire trajectory rather than to a single frame.
During the discussions, it was mentioned that it would be nice if a certain frame could be linked to a structure entry with the same structure. My first idea was to treat the relationships field in the same way as the other properties that have a value for a frame.
I however also wanted to have the option to have references relating to the entire trajectory and not to a single frame, and therefore I placed an extra relationships section in the reference structure.

I am now however starting to doubt whether this is such a good idea, especially because the JSON API standard also defines a relationships field. And the way I am currently using the relationship fields is probably not what the makers of the JSON API standard intended. 

So my main question is: Do you think it is necessary to be able to make references from a frame?
If not, I can simply remove the relationships field from reference_structure and use one global  relationships field.

2021-07-22 16:08 UTC, JPBergsma commented on optimade.rst
> +    }
I have tried to correct this in the latest commit. I am however not entirely sure it is correct so please check it again,

2021-07-22 16:25 UTC, ml-evs commented on optimade.rst
>        "last_modified":"2021-07-16T18:02:03Z"
`last_modified` also needs to be demoted to an attribute

2021-07-22 16:25 UTC, ml-evs commented on optimade.rst
> +            }
`relationships` is not an attribute so should be bumped up

2021-07-22 20:34 UTC, JPBergsma commented on optimade.rst
> +            }
Thank you, I will move it.

2021-07-22 20:35 UTC, JPBergsma commented on optimade.rst
>        "last_modified":"2021-07-16T18:02:03Z"
Thank you for looking at it again. I have moved it.

2021-07-26 15:57 UTC, JPBergsma commented on optimade.rst
> +available_properties
At present, this field only stores data about which properties are available. Do we also want to include information about how many values there are for each property, or which frame encoding the property has, so it may be easier to preallocate memory?

2021-07-26 17:22 UTC, JPBergsma commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~
I think the JSON relationship field should only be used for references. 
So if Iunderstand it correctly you are suggesting to make the reference structure a structure like any other structure in the structures endpoint, and that the reference structure field, within the relationship section of a trajectory, would have a link to this structure.

If I remeber correctly, during the Optimade meeting the point was raised that a trajectory should have all the data required to plot a trajectory. And as much of the data in the reference structure is needed to plot the trajectory it seemed logical to place it in the trajectory. Later we made it so practically any field can be defined on a per frame basis so now it may make more sense to have a seperate structure as the reference structure. 

One other point that we have to think of, if the reference structures are turned into normal structure entry point structures, is that the structures that are currently in the databases are all optimized structures. This may not be the case for a reference structure. We should somehow make sure that for someone who searches through the structures it is clear wether or not the structure is optimized.

2021-07-26 20:57 UTC, JPBergsma commented on optimade.rst
> +- **Description**: This is a link the client can use to download the remainder of the trajectory data when the server returns fewer frames than the client requested.
In principle, it should be possible to use the links field.
It would however make creating the next link a bit more complicated. (assuming the query would return multiple trajectories.)

You would have to specify what the original query was,
Next, you would need to specify which trajectory you are in the process of returning.
And finally, you would have to specify what is the first unreturned frame of that trajectory. 

As these extra fields should only be encountered by the server implementation that created the "next" link. We would not have to define these fields. So it would actually make writing the standard a bit easier. 

If you think this is a good idea, I can change the draft specification.

2021-07-27 09:03 UTC, ml-evs commented on optimade.rst
> +- **Description**: This is a link the client can use to download the remainder of the trajectory data when the server returns fewer frames than the client requested.
If the user wants to download an entire trajectory/more of a specific trajectory, would they not go to the single trajectory endpoint? In which case a self-link could be used (see e.g. optional fields in the section [Entry Listing JSON Response Schema](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#532entry-listing-json-response-schema)).

It's not clear to me what the intention of `next_part_trajectory` is from what is written here, what will the user receive if they follow that link?

2021-07-27 09:25 UTC, ml-evs commented on optimade.rst
> +  - It MAY also have a 'relationships'_ field for references that apply to the entire trajectory rather than to a single frame.
Just to clarify, the relationships field in the specification *is* the relationships field from JSON:API, it's just a general way of providing mappings from one entry to another, irrespective of their type.

You are right that JSON:API has no way of specifying relationships *within* an entry (e.g. individual relationships for frames within an entry types trajectory), and similarly listing them all in the top-level relationships is probably not a good idea.

Again, I think this depends on the intended use-case. Relationships don't have to be bi-directional, so you could have a one-to-one structures->trajectory relationship without the one-to-many trajectory->structure relationship. This would still allow you to grab all structures registered to a trajectory with something like `/structures?filter=trajectories.id=12345` but would not allow the reverse, e.g. `/trajectories?filter=structures.id=67890`.

Another problem with using relationships here is that JSON:API requires that you provide the linked documents in an `included` field if requested, which could become very large in both cases (would need very strict response field trimming, which will probably be the case for trajectories anyway).

2021-07-27 10:41 UTC, JPBergsma commented on optimade.rst
> +- **Description**: This is a link the client can use to download the remainder of the trajectory data when the server returns fewer frames than the client requested.
Via the link in `next_part_trajectory` The user would receive the next part of the trajectory. Trajectories may be very large, so you would want to have the option for the server to return it one block at a time. 

In principle, the client can make a query that would return multiple complete trajectories by combining a filter with the appropriate response fields. In that case, I was originally thinking that the `next` field in the links section could point to the next trajectory, while the "next_part_trajectory" would point to the next block of the current trajectory.

2021-07-27 12:10 UTC, JPBergsma commented on optimade.rst
> +  - It MAY also have a 'relationships'_ field for references that apply to the entire trajectory rather than to a single frame.
It is not mandatory to support the `included` field. If it is supported, the server would only have to return the mandatory fields of the trajectory. i.e. the reference frame and a few other fields. This would not be significantly more data than a typical structure entry.

2021-08-03 20:14 UTC, JPBergsma commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~
I recently spoke with Josh Vita from Open KIM. They use machine learning to try to generate interatomic potentials based on quantum mechanical simulations. They have training sets with many structures. We discussed whether they could use the trajectory end points for sharing these training sets. The individual structures in these training sets can, however, have different elements. So there is not a clear way for them to define a consistent reference structure. For example, should the elements field hold all the elements in the trajectory or just the elements for which the structure is given?

One option could be to have a set of reference properties that apply to all the frames and a separate optional reference structure. I am curious to hear what your opinions on this are.

2021-09-09 09:15 UTC, giovannipizzi commented on optimade.rst
> +available_properties
This might be indeed useful (I think it should always be easy to compute on the server side?)

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +- **Requirements/Conventions**:
Specify also here that this is zero-based, and the value must be >=0 and < nframes

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be larger or equal to 0 and MUST be less than or equal to nframes.(The total number of frames in the trajectory)
```suggestion
  - **Requirements/Conventions**: The value MUST be larger or equal to 0 and MUST be less than nframes.(The total number of frames in the trajectory)
```

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be larger or equal to first_frame and MUST be less than or equal to nframes(the total number of frames in the trajectory).
```suggestion
  - **Requirements/Conventions**: The value MUST be larger or equal to first_frame and MUST be less than nframes(the total number of frames in the trajectory).
```

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be larger or equal to 1 and MUST be less than or equal to the total number of frames.
```suggestion
  - **Requirements/Conventions**: The value MUST be larger than or equal to 1.
```
(I suggest removing the limitation on the max value - if it's too large, you will just get one frame, but I think this is OK). We might actually think at whether to reduce the contraints on  first and last frame (keeping >=0, but removing the largest value: e.g. like in python, if `a=[1,2,3]` you can do `a[7:12]` and this just returns an empty list.)

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +- **frame_encoding**:
I think the name 'encoding' is, in the end, correct in meaning - but I'm wondering if this might become confusing as people typically think to "string encoding" when "encoding" is mentioned? I don't have a better suggestion though (maybe "frame_serialization_format" but it's a bit long)

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +    - **explicit_custom_sparse**: A separate list with frame numbers is defined in the field frame_number to indicate to which frame a value belongs.
Let's discuss - it's probably OK to keep all, even if the clients must be a bit more complex - but maybe better to keep now rather than to add later, that will mean old clients will not work?

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +  - **Description**: If **frame_encoding** is set to "linear", this value gives the increase/decrease in the value of the property when going from one frame to the next.
Maybe clarify even more that this is the value change for a change by one unit of the frame number - even if some properties might be defined less often? (If you feel that's already clear enough, then no need to change)

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +- **frame_number**:
Maybe rename to `sparse_frame_numbers` that is, I think, more clear than `frame_number` (that to see seems too general and potentially confusing to users who don't read the specs). Also, update accordingly the example below (where it says "frames" instead).

Also: do you want to mention also here that the values will be `0<=x<nframes` for all elements `x` of `sparse_frame_numbers`?

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +- **values**:
Here (and above) I just have two related general questions, of which I'm not sure.

- is it OK to have some values specified only depending on the value of the string "encoding"? Probably yes and this can be written as a validation rule, but just to double check
- is it OK that the value depends on the type (I'm thinking also from a validation point of view)? Probably yes as it's always a list of values, just the length (and the meaning of which frames it's associated to) changes, but I wanted to double check

2021-09-09 09:27 UTC, giovannipizzi commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be present.
This is not true for the `linear` case (I think it's the only one?), to be fixed.

2021-09-09 10:21 UTC, giovannipizzi commented
Can we add and endpoint for bulk downloads?

2021-09-09 10:30 UTC, giovannipizzi commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be present.
Also, for 'constant', is this a list of 1 value or a single float?

2021-09-09 13:14 UTC, JPBergsma commented on optimade.rst
> +- **Requirements/Conventions**:
I will expand the description for the reference frame.

2021-09-09 13:52 UTC, JPBergsma commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be larger or equal to 1 and MUST be less than or equal to the total number of frames.
I think we can indeed leave this out. The server code would have to handle the case where the remainder is not dividable by the frame_step anyway.

2021-09-09 14:10 UTC, JPBergsma commented on optimade.rst
> +- **frame_encoding**:
I have changed it to frame_serialization_format for now. If you still come up with a better name i can easily change it with a search and replace.

2021-09-09 14:43 UTC, JPBergsma commented on optimade.rst
> +  - **Description**: If **frame_encoding** is set to "linear", this value gives the increase/decrease in the value of the property when going from one frame to the next.
I will add a small example, so it will hopefully be a bit clearer to the reader.

2021-09-09 15:27 UTC, JPBergsma commented on optimade.rst
> +- **frame_number**:
I will change it to `sparse_frames` that is a bit shorter and should also avoid any ambiguity.

2021-09-10 15:52 UTC, JPBergsma commented on optimade.rst
> +  - **Requirements/Conventions**: The value MUST be present.
You are right, for linear the value is not needed.

For constant, the format will depend on the property that is shared. It could be a float or a list of one value. But it can also be a list of lists such as for, for example, the lattice vectors.

2021-09-12 17:12 UTC, JPBergsma commented
> Can we add an endpoint for bulk downloads?
What would you want to do with that endpoint that could not be done with the endpoints that are already under discussion?
The server is already allowed to send back as many trajectories as it wants in one go unless the client specifies a page limit.

2021-09-12 17:47 UTC, JPBergsma commented on optimade.rst
> +- **Description**: This is a link the client can use to download the remainder of the trajectory data when the server returns fewer frames than the client requested.
For now, I have removed the next_part_trajectory field.

2021-09-14 14:50 UTC, giovannipizzi commented
>> Can we add an endpoint for bulk downloads?

>What would you want to do with that endpoint that could not be done with the endpoints that are already under discussion?
The server is already allowed to send back as many trajectories as it wants in one go unless the client specifies a page limit.

Both the client and the server can impose limits. What I'm thinking at is that the server might have to impose limits (we're returning data in JSON, that in most implementations has to be fully loaded in memory to be parsed, so the server will *have to* paginate). However there are other formats that would allow a simple file download (possibly also with streaming, reading one line at a time). Or, simply serve the file in the format stored in the underlying database.

Therefore, having a way to allow bulk downloads I think is very important - otherwise for big trajectories, the server will have to convert to JSON, paginate, the client will have to perform many paginated request, put all together, and reconstruct the trajectory in some other format. A bulk download would be much faster.

2021-09-14 17:17 UTC, JPBergsma commented
We could allow references/links that point directly to the (compressed) output files that contain the trajectory data. 
Such as xyz, pdb etc. 
This would however also apply to the structures end point, where databases may also want to supply the original pdb and CIF files. So I do not see this as an issue specifically for the Trajectories.

There is also PR#360 that suggests a files end point. 
If that PR gets merged, we can also update our description for the trajectory endpoint and add a piece about how to share the trajectory data in these file types.

2021-09-17 13:27 UTC, JPBergsma commented on optimade.rst
> +- **first_frame**:
At present, only one subrange can be returened at a time. Do we want to support for queries requesting multiple subranges?

2021-09-28 08:19 UTC, giovannipizzi commented on optimade.rst
> +- **first_frame**:
It would be good to hear from users, but I think a single range per request is enough (if we allow for getting one every N steps between a first and last frame)?

2021-12-15 12:41 UTC, JPBergsma commented on optimade.rst
> +    - **explicit_custom_sparse**: A separate list with frame numbers is defined in the field frame_number to indicate to which frame a value belongs.
Ok, I will keep all the options and mark this as resolved. Feel free to reopen it if you want to discuss it further.

2021-12-15 14:34 UTC, JPBergsma commented on optimade.rst
> +available_properties
I have added the `frame_serialization_format` and the number of values to the `available_properties` field.
This should help the client to estimate the amount of data that will be returned.

2021-12-15 14:52 UTC, JPBergsma commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~
I am closing this discussion. If I remember correctly, the discussions did not lead to a decision to change this, and it has also been open for a very long time without replies. Feel free to reopen it though.

2021-12-15 16:23 UTC, JPBergsma commented on optimade.rst
> +- **values**:
> is it OK to have some values specified only depending on the value of the string "encoding"? Probably yes and this can be written as a validation rule, but just to double check

I think this situation is quite similar to the structure_features field. 
If the string "assemblies" is present within `structure_features`  the field `assemblies` must be present as well.
If "assemblies" is not present the `assemblies` field should be `null` or not present.


> is it OK that the value depends on the type (I'm thinking also from a validation point of view)? Probably yes as it's always a list of values, just the length (and the meaning of which frames it's associated to) changes, but I wanted to double check

I think it is OK, At the info/structures endpoint the data type of all the properties in the database is listed. So we could check whether the data type of the items in the values field matches the type specified there. For the properties in the Optimade standard there is also the openapi_schema.json, where the data type of all OPTIMADE defined properties is listed.  Most of the validator was written by @ml-evs and @CasperWA though, so they can probably give a more definitive answer.

2021-12-16 07:25 UTC, merkys requested changes
This is a large addition to the specification, albeit well-written. I personally do not deal with trajectories thus my comments may look naive, but wouldn't it be simpler and sufficient to define a trajectory by a sequence (collection maybe, #386) of OPTIMADE structures? I am aware that the current proposal introduces means to "pack" values using `frame_serialization_format` mechanism, but I wonder whether added complexity vs. benefit ratio is optimal.

2021-12-16 07:25 UTC, merkys commented on optimade.rst
> +    - **Description**: This field gives the number of values for this property.
What does it mean when `nvalues` is different from the total number of frames?

2021-12-16 10:44 UTC, JPBergsma commented
> This is a large addition to the specification, albeit well-written. I personally do not deal with trajectories thus my comments may look naive, but wouldn't it be simpler and sufficient to define a trajectory by a sequence (collection maybe, #386) of OPTIMADE structures? I am aware that the current proposal introduces means to "pack" values using `frame_serialization_format` mechanism, but I wonder whether added complexity vs. benefit ratio is optimal.

Thank you for your comments.
There are several reasons why a trajectory can not be stored as a series of structures in a good manner.

An MD trajectory can easily contain 100.000 time steps.
To save storage space, not all the fields will be stored for every frame. In a project I did as a student I would store the constraint force every 5 time steps. Yet, the positions I would only store every 100 steps. 
The cartesian_site_positions are a mandatory field, so I would not be able to create a proper structure for all the time steps where I have data on the constraint force. Even if I had that data, storing that many structures would take up a lot of hard drive space. 

There would also be so many structures that queries with multiple properties would be very slow. 
These structures would also drown out structures which occur only once. So I think we would have to, somehow, distinguish them from the normal structures any way.

To keep things as close as possible to the current OPTIMADE we have therefore implemented the reference frame. So you can still query trajectories in the same way as you would do with a normal structure. There are still some rare cases where this could cause problems, but I think it should be sufficient for the vast majority of the trajectories.

2021-12-16 11:52 UTC, JPBergsma commented on optimade.rst
> +reference_structure
I think a lot of the specification was first written in Markdown. (Giovanni mentioned this approach to me.) There you need to escape underscores. At first, I used Pycharm to edit the RST file. It has some issues with creating links to other sections when there was an underscore in the name. I therefore removed them. I just noticed there are still some escaped underscores left in the document, though. Either I missed them the first time or they were added in later PR's. Do you want me to remove those as well ?

There is indeed a tilde too many. I have removed it.

2021-12-16 11:59 UTC, JPBergsma commented on optimade.rst
> +The preceding properties 7.3.1-4 and the fields described under `Properties Used by Multiple Entry Types`_ MUST be returned when no :query-param:`response_fields` property (see the section `Entry Lis
Yes, you are right, I was first hoping there was a way to update it automatically like in Latex. But I never found out how to do this in Restructuredtext.

2021-12-16 12:42 UTC, JPBergsma commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
I have added a link to the "Retrieving the trajectory data" section.

2021-12-16 14:08 UTC, merkys commented on optimade.rst
> +reference_structure
I suggest against bundling unrelated changes in this PR. This way conflicts may emerge, and the diff becomes difficult to eyeball.

2021-12-16 14:09 UTC, merkys commented on optimade.rst
> +The preceding properties `reference_structure`_, `reference_frame`_, `nframes`_, `available_properties`_ and the fields described under `Properties Used by Multiple Entry Types`_ MUST be returned whe
"fields described" -> "properties described"

2021-12-16 15:13 UTC, JPBergsma commented on optimade.rst
> +  - This reference_structure MAY be one of the frames from the trajectory, in that case the `reference_frame`_ field MUST specify which frame has been used.
> Also, is it meaningful to have the reference structure not taken from the frames of the trajectory?

You could use the average position of the atoms as the reference structure. You may for example want to predict the B-factors of a structure. In that case, one of the results from the simulation would be the average positions of the atoms, which you could use as a reference structure.

> I suggest replacing "reference_structure" with "reference structure" as the specification up to this point does not seem to use terms in such a way.

I have added ":property:" in front of reference_structure to make it more similar to how properties are used elsewhere in the text.

Other than that I do not see how my use is different from for example the `chemical_formula_reduced` in line 1984.
or  `response_fields` in line 1805. > or if they are included also when :query-param:`response_fields` is not present.

2021-12-17 08:33 UTC, JPBergsma commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
I have changed "describe" to "described". I however do not see anything wrong with the indentation. Could you be more specific ?

2021-12-17 08:47 UTC, JPBergsma commented on optimade.rst
> +The preceding properties `reference_structure`_, `reference_frame`_, `nframes`_, `available_properties`_ and the fields described under `Properties Used by Multiple Entry Types`_ MUST be returned whe
I have changed this.

2021-12-17 09:08 UTC, JPBergsma commented on optimade.rst
> +reference_structure
I have readded most of the necessary backslashes. So there should be fewer differences with the original OPTIMADE specification.

2021-12-17 09:59 UTC, JPBergsma commented on optimade.rst
> +  The data belonging to the frames of the trajectory is only returned when this is specifically requested in the :query-param:`response_fields` parameter.
It is mostly the same as the normal `response_fields` query parameter.

The behaviour here is however slightly different. Normally all the standard OPTIMADE fields are returned. For the positions of the particles in a trajectory you could use the "cartesian_site_positions" property that is already in the standard. This could lead a user to think that when they request a trajectory they would automatically get the particle positions. 
I however chose to have the user request which properties they want to have, so they do not request more data from the server than needed. To make this clear to the user I have placed this line here. It is described more in the section "Retrieving the trajectory data", to which I have made a link.

I can remove it here if you think it is to specific for a general introduction of the trajectory endpoint.

2021-12-17 10:34 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the reference_structure when the queried property is in the reference_structure.
You are right, the definition is not very clear about how you should query properties in the reference_structure.

There are two ways:

A: ...\trajectories?filter=nelements=2  
B: ...\trajectories?filter=reference_structure.nelements=2

I think I had method A in mind When I wrote:"Queries on the trajectories MUST be done on the information supplied in the reference_structure when the queried property is in the reference_structure."

But I do not have a strong preference. And method B is perhaps more in line with how we perform queries elsewhere on nested fields.
It should mainly be clear that the query will not be performed on the values in an individual frame.

For now, I will add an example of query A, but I can change it to query B if you prefer.

2021-12-17 11:08 UTC, JPBergsma commented on optimade.rst
> +While these URL query parameters are OPTIONAL for clients, API implementations MUST accept and handle them.
I have tried to clarify this a bit in the text. I however do not see why a user would misuse these query parameters at the structures endpoint as they do not make sense there.

2021-12-17 12:20 UTC, JPBergsma commented on optimade.rst
> +    - **Description**: This field gives the number of values for this property.
The value of a property may not have been calculated or stored at every frame/timestep. So the number of available values can be less than the number of frames. By specifying the number of values we allow a client to pre allocate memory to store the data.

2021-12-17 12:26 UTC, merkys commented on optimade.rst
> +  The data belonging to the frames of the trajectory is only returned when this is specifically requested in the :query-param:`response_fields` parameter.
OK, I think I understand now, thanks. However, I still think this sentence is superfluous. Section "Entry Listing Endpoints" provides sufficient description on how to say which properties should not appear in the response unless explicitly requested.

2021-12-17 12:27 UTC, merkys commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
OK, thanks for adding the link. I do not see the problem with indentation anymore. Maybe I was mistaken, sorry.

2021-12-17 12:34 UTC, merkys commented on optimade.rst
> +reference_structure
Thanks for de-bundling the changes. I will look at `\_` vs. `_` issue.

2021-12-17 12:37 UTC, merkys commented on optimade.rst
> +    - **Description**: This field gives the number of values for this property.
OK, thanks. But I see no need for a client to pre-allocate the memory at this point. A client will still read in JSON response with the actual values and do the pre-allocation then by looking at the number of values in the JSON.

2021-12-17 12:43 UTC, merkys commented on optimade.rst
> +While these URL query parameters are OPTIONAL for clients, API implementations MUST accept and handle them.
My comment is more about trying to control the namespace. I would prefer explicitly relating these `*_frame` query parameters to `/trajectories` as in future identically named parameters may appear in other endpoints with completely different meaning. But I am not sure how to properly do so, as we hadn't endpoint-specific query parameters before.

2021-12-17 13:05 UTC, JPBergsma commented on optimade.rst
> +  The data belonging to the frames of the trajectory is only returned when this is specifically requested in the :query-param:`response_fields` parameter.
Ok, I have removed the sentence from this section and changed the surrounding text a bit.

2021-12-17 13:40 UTC, JPBergsma commented on optimade.rst
> +    - **Description**: This field gives the number of values for this property.
The amount of data in a trajectory can be quite large, so the idea was that we would allow streaming JSON parsers to process the files.

2021-12-17 13:52 UTC, merkys commented on optimade.rst
> +    - **Description**: This field gives the number of values for this property.
Right, but one will always know the top limit, and that limit will be the amount of memory required in the worst-case scenario. I do not think that nowadays one would be unable to pre-allocate the maximum required amount of memory and re-allocate afterwards. Or use dynamic allocation on-the-fly (think linked lists).

2021-12-17 14:51 UTC, JPBergsma commented on optimade.rst
> +While these URL query parameters are OPTIONAL for clients, API implementations MUST accept and handle them.
That is an interesting point.
I think this goes beyond the scope of just this PR, as it may also affect other endpoints in the future.
So perhaps it would be good to open a separate issue about this.

It should not be too hard to change the name of a query parameter in the client and server software once that discussion reaches a conclusion. So I think that for now we can continue with finalizing this PR. It will take some time to implement the new trajectory endpoint anyway. So it should be possible to conclude that discussion before trajectory endpoints have been fully implemented.

2021-12-17 15:56 UTC, JPBergsma commented on optimade.rst
> +    - **Description**: This field gives the number of values for this property.
The size of a trajectory can definitely be larger than the amount of memory you have available in your machine. 
See for example this [simulation](https://phys.org/news/2019-04-scientists-billion-atom-biomolecular-simulation.html).
Most computers would already struggle to process a single structure of this trajectory.

I don't think OPTIMADE will be used for simulations that large, but the simulation data could still be several gigabytes in size. 
This can be too large for a simple computer to handle. That is part of the reason we allow the selection of a range of frames. That way, the client can request the data in several steps, if it cannot process it in a streaming fashion.
Knowing how many values there are of a property in the trajectory can help with estimating the average amount of data per frame.

2022-09-28 06:17 UTC, merkys commented on optimade.rst
> +    Entries are categorized into types, e.g., :entry:`structures`, :entry:`trajectories`, :entry:`calculations`, :entry:`references`.
This is supposed to be a small set of examples, I do not think it needs more than 3 items.

2022-09-28 06:18 UTC, merkys commented on optimade.rst
> +    A Trajectory contains data belonging to a set of structures.
I would replace "set" with "sequence" to make the relationship between structures clearer.

2022-09-28 06:19 UTC, merkys commented on optimade.rst
> +    It can however also contain data from structures that are related in an different way.
"an different" -> "a different"

2022-09-28 06:20 UTC, merkys commented on optimade.rst
> +It MUST NOT expose any entry listing endpoints (e.g., :endpoint:`structures` and :endpoint:`trajectories`).
Also an example here, no need to include `trajectories`.

2022-09-28 06:21 UTC, merkys commented on optimade.rst
> +  It can however also be used to share data from structures that are related in an other way.
"an other" -> "another"

2022-09-28 06:25 UTC, merkys commented on optimade.rst
> +    The subfields of the reference_structure MUST have the same queryability as in the `structures entries`_.
Markup seems off. `reference_structure` should be marked with `:property:`, but I cannot figure out what `structures entries` refer to.

2022-09-28 06:28 UTC, merkys commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
To me this seems as an unnecessary deviation from the current specification. We can easily get away without this special additional rule for queries by querying for, e.g., `trajectories?filter=reference_structure.nelements=2`.

2022-09-28 06:35 UTC, merkys commented on optimade.rst
> +
I suggest avoiding surplus empty lines, in consistence with the remaining specification. Single empty line is enough.

2022-09-28 06:39 UTC, merkys commented on optimade.rst
> +        "last_modified":"2021-07-16T18:02:03Z"
Missing trailing comma, invalid JSON. Please make sure this example is valid JSON, I have not checked for other possible syntax mistakes.

2022-09-28 06:59 UTC, merkys requested changes
I have highlighted several minor issues with the proposal which I would like to have resolved before approval.

The deviation from OPTIMADE-ish way of filtering seems unnecessary to me. Maybe we could re-use the existing mechanism of nested property names?

Both requesting frame ranges via URL query parameters and returning their values inside `trajectory` entries also seem to deviate from OPTIMADE-ish and JSON:API-ish way of doing things. Maybe frame range could be made a subresource of a trajectory? For example, instead of requesting `/trajectories/1?first_frame=10&last_frame=100&frame_step=20` we could request `/trajectories/1/10-20-100`? This would then return fields describing the frame range, but not the trajectory.

2022-09-28 08:05 UTC, JPBergsma commented on optimade.rst
> +    Entries are categorized into types, e.g., :entry:`structures`, :entry:`trajectories`, :entry:`calculations`, :entry:`references`.
Ok, I will remove ":entry:`trajectories`, "

2022-09-28 08:34 UTC, JPBergsma commented on optimade.rst
> +    A Trajectory contains data belonging to a set of structures.
I have replaced set with sequence for now. 
It depends a bit on how broad you see the scope of the trajectory endpoint. If you want to share a number of structures that are unordered, set would be more appropriate. 
There is/was also a proposal for a collections endpoint. If we accept that proposal, there will be an alternative way to group structures. In that case it won't be necessary to do this via the trajectory endpoint and this definition can be a bit more restrictive by using sequence instead of set.

2022-09-28 08:35 UTC, JPBergsma commented on optimade.rst
> +It MUST NOT expose any entry listing endpoints (e.g., :endpoint:`structures` and :endpoint:`trajectories`).
Ok, I will remove this.

2022-09-28 08:51 UTC, JPBergsma commented on optimade.rst
> +  It can however also be used to share data from structures that are related in an other way.
I will changed it.

2022-09-28 09:53 UTC, rartino submitted a review, later dismissed
Great work with this - and a great extension to OPTIMADE. 

There are a few things I think needs another look - in particular the format of `available_properties` is a rather important thing I think we should try to get right in the first version.

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +  - This :property:`reference_structure` MAY be one of the frames from the trajectory, in that case the `reference_frame`_ field MUST specify which frame has been used.
Is the MUST requirement on `reference_frame` reasonable? The way I read this, the creator of a synthetic example structure (rather than just taking one out of the trajectory) MUST dig through the data to ensure not to have accidentally recreated an image that appear in the trajectory. I agree that it in many cases this would be unlikely to happen - but since trajectories are for sequences also outside MD, it seems possible and I think it is an unnecessary harsh requirement. I'd argue to lower it to SHOULD.
```suggestion
  - This :property:`reference_structure` MAY be one of the frames from the trajectory, in that case the `reference_frame`_ field SHOULD specify which frame has been used.
```

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
I do not understand how to read this MUST, what is it meant to enforce?

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +    For example, the query : http://example.com/optimade/v1/trajectories?filter=nelements=2 would use the `nelements`_ property within the reference_structure.
```suggestion
    For example, the query: http://example.com/optimade/v1/trajectories?filter=nelements=2 would use the `nelements`_ property within the reference_structure.
```

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +
This is tricky, but especially in light of the property standardization work, I do not think we want non-standard custom-written "Support"-levels. So, I think the more intricate requirement in the relationship with the trajectory should go in a separate Requirements/Conventions point. This is then what I would suggest if you accept lowering the requirement to SHOULD level:
```suggestion
  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
  - **Query**: Support for queries on this property is OPTIONAL.
    If supported, filters MAY support only a subset of comparison operators.
  - SHOULD NOT be :val:`null` if the `reference_structure`_ is in the trajectory. 
  - MUST be :val:`null` or omitted if `reference_structure`_ is not in the trajectory.
```

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +  This makes it easier for a client to estimate the amount of data a query returns.
The design of `available_properties` breaks something we decided way back: to avoid storing data as keys in  dictionaries. Instead - see e.g. the 'species' property - it was found for several reasons to be a better idea to turn these designs into lists of dictionaries where the key is instead inserted among the right-hand-side values with a sensible field name. I'll edit an example below to show how.

If the definition of available_properties is changed this way, an added advantage should be that it is easier to format this definition of the property the same way as, e.g., `species` where all the type info goes into type. Right now the "Sub dictionary fields" category is something that was introduced here and is used nowhere else.

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +         }
In line with my comment above (but needs other changes above if accepted), this is how I think this data structure should look:
```suggestion
         "available_properties": [
           {
             "property": "cartesian_site_positions", 
             "frame_serialization_format": "explicit",
             "nvalues": 1000
           },
           {
             "property": "lattice_vectors",
             "frame_serialization_format": "constant",
           },
           {
             "property": "species",
             "frame_serialization_format": "constant",
           },
           {
             "property": "dimension_types",
             "frame_serialization_format": "constant",
           },
           {
             "property": "species_at_sites",
             "frame_serialization_format": "constant",
           },
           {
             "property": "_exmpl_pressure",
             "frame_serialization_format": "explicit_custom_sparse",
             "nvalues": 20
           },
           {
             "property": "_exmpl_temperature",
             "frame_serialization_format": "explicit_regular_sparse",
             "step_size_sparse": 10
             "nvalues": 100
           }
         ]
```

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +Next to this the client MAY specify the following parameters to customize the return from the server at the trajectory endpoint.
```suggestion
Furthermore, the client MAY specify the following parameters to customize the return from the server at the trajectory endpoint.
```

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +The preceding properties `reference_structure`_, `reference_frame`_, `nframes`_, `available_properties`_ and the properties described under `Properties Used by Multiple Entry Types`_ MUST be returned
I agree with @merkys in the closed comment that we at least must inject a "for queries on the trajectory endpoint" here; but there is a more major issue that we don't have a place for these kind of endpoint requirements. To not hold this PR, I think we just need to add an issue to address that on a larger scale. But fore now I suggest:
```suggestion
For queries referencing the :endpoint:`trajectories` endpoint, the preceding properties `reference_structure`_, `reference_frame`_, `nframes`_, `available_properties`_ and the properties described under `Properties Used by Multiple Entry Types`_ MUST be returned when no :query-param:`response_fields` property (see the section `Entry Listing URL Query Parameters`_) is specified.
```

2022-09-28 09:53 UTC, rartino commented on optimade.rst
> +After the previous querry is an example of a JSON object that could be returned after the following query:
"Query" is misspelled, but I also have difficulty parsing the meaning of the rest of the sentence. Is this what is meant?
```suggestion
Upon having performed the above query, the following query can be performed to return trajectory data:
```
(I also removed the mentioning of JSON. I assume I can be allowed to encode the response in `response_format=_httk_hdf5` just like with everything else in OPTIMADE...)

2022-09-28 10:57 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
Reading back this line, it is indeed needlessly restrictive/unclear.

My example Heroku server also supports queries like `cartesian_site_positions.values > 40` and `reference_structure.nsites < 40`

Before I rewrite this; Do we want to keep allowing a query like `nsites < 40`as shorthand for `reference_structure.nsites < 40`, which was what this line was originally meant to describe.

2022-09-28 12:29 UTC, JPBergsma commented on optimade.rst
> +    The subfields of the reference_structure MUST have the same queryability as in the `structures entries`_.
I have added the `:property:` flag.
`structures entries`_ is a link to section 8.2 
It is not possible for something to marked and be a link at the same time, so I have now made the first `structures entries` a link and placed the `:entry:` marker in front of the other.
I also moved this line after the list of reference_structure properties, as this seems more appropriate.

2022-09-28 12:39 UTC, merkys commented on optimade.rst
> +    A Trajectory contains data belonging to a set of structures.
> It depends a bit on how broad you see the scope of the trajectory endpoint. If you want to share a number of structures that are unordered, set would be more appropriate.

Then I would argue that name "trajectory" is no longer accurate, or am I missing something?

2022-09-28 12:42 UTC, merkys commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
> Before I rewrite this; Do we want to keep allowing a query like `nsites < 40`as shorthand for `reference_structure.nsites < 40`, which was what this line was originally meant to describe.

I would say no. I would feel more comfortable with less deviations from the current filtering idea.

2022-09-28 12:44 UTC, merkys commented on optimade.rst
> +    The subfields of the reference_structure MUST have the same queryability as in the `structures entries`_.
Right, but shouldn't it then be "Structures Entries" (capitalized)?

2022-09-28 13:52 UTC, JPBergsma commented on optimade.rst
> +        "last_modified":"2021-07-16T18:02:03Z"
I have added a few missing quote marks and added and removed commas where necessary.

I now use ellipses to indicate that some of the JSON response is missing. 
To make it correct JSON, I would also have to add other fields such as the meta and links fields. 
Do you want me to do this as well ?

2022-09-28 13:55 UTC, merkys commented on optimade.rst
> +        "last_modified":"2021-07-16T18:02:03Z"
There are ellipses in JSONs in the specification already. They are placed in comments (`// ....`) to render correct JSONC (a.k.a. JSON with comments). Please do the same here.

2022-09-28 15:13 UTC, ml-evs commented on optimade.rst
> +
Discussion from the web meeting (28/09/22) was to move these definitions into the trajectory endpoint introduction

2022-09-28 16:56 UTC, JPBergsma commented on optimade.rst
> +
Ok, I have removed these definitions here and added the same information to the description field of the trajectory endpoint.

2022-09-28 19:42 UTC, JPBergsma commented on optimade.rst
> +    The subfields of the reference_structure MUST have the same queryability as in the `structures entries`_.
I have capitalized "Structures Entries" when referring to section 8.2

2022-09-29 05:29 UTC, merkys commented on optimade.rst
> +    //,...
`//,...` -> `// ...`

2022-09-29 08:56 UTC, JPBergsma commented on optimade.rst
> +    A Trajectory contains data belonging to a set of structures.
No you're not missing anything. Trajectory would indeed not be such a good name in that case. So far, there are no plans to use the trajectory endpoint in such a broad sense. But I can't exclude the possibility that some future group will want to use it in such a way.

2022-09-29 09:09 UTC, rartino commented on optimade.rst
> +    A Trajectory contains data belonging to a set of structures.
Isn't the design of the trajectory endpoint fundamentally relying on the assumption that it describes an *ordered* collection of frames - since they are indexed by a frame number; i.e., it represents them as a sequence rather than a set?

(And, if one really wants to represent a set of structures, shouldn't one use a #386 collection of structures instead?)

2022-09-29 10:20 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
Ok, I have removed these lines.

2022-09-29 10:20 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
@rartino Do you mean the must in line  "Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`."
or another MUST?

2022-09-29 10:56 UTC, JPBergsma commented on optimade.rst
> +    A Trajectory contains data belonging to a set of structures.
Let's say, I have a training set for generating machine learned potentials. It would feature a set of structures with the same atoms but in different positions. The generated potential would not depend on the order of the structures, so there is no reason to place them in a specific order. So in this case the order of the structures would not be fundamental. 
Of course the order MUST be the same every time a request is made, but it does not matter in which order the structures are initially stored in the trajectory.
It would be more efficient to use the trajectory endpoint for sharing this data, because I would not need to repeat many of the fields like species, lattice_vectors, and species at sites. While this is not the purpose of the trajectory endpoint, it is possible it will be used like this in the future.

2022-09-29 11:56 UTC, JPBergsma commented on optimade.rst
> +    An individual structure or data belonging to an individual structure from a trajectory.
Matthew made the same comment and I have removed the definitions from 
Definition of Terms section and I have tried to add the same information to the description of the Trajectory endpoint.

2022-09-29 12:10 UTC, JPBergsma commented on optimade.rst
> +  For example the successive structures from a Monte Carlo simulation.
I had already changed the text in this section after moving removing the definitions, but I have tried to include the changes suggested here as best as I could.

2022-09-29 12:11 UTC, JPBergsma commented on optimade.rst
> +  Next to this they can optionally have all the fields of the structures entries as well as relationships and database specific fields.
I will put this suggestion in the text as well.

2022-09-29 13:47 UTC, JPBergsma commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
The checks fail when I directly commit rartino's code suggestions so I will now add these manually.

2022-09-29 13:50 UTC, rartino commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
It is the trailing whitespace check that seems to be failing currently. I'll quickly edit my code suggestions to verify that they do not add new trailing whitespace.

2022-09-29 13:51 UTC, JPBergsma commented on optimade.rst
> +  Queries on individual frames are not supported.
Which lines are you referring to ?

2022-09-29 13:53 UTC, JPBergsma commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
I already removed all the trailing white space I could find, but it still gave me an error.

2022-09-29 13:54 UTC, rartino commented on optimade.rst
> +  Queries on individual frames are not supported.
All of the marked text - i.e., as it looks now, lines 2833 to 2838.

2022-09-29 13:56 UTC, JPBergsma commented on optimade.rst
> +    For example, the query : http://example.com/optimade/v1/trajectories?filter=nelements=2 would use the `nelements`_ property within the reference_structure.
This line is no longer there.

2022-09-29 13:57 UTC, rartino commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
There was a whitespace in the `available_properties` example that I removed. I didn't find any other.

2022-09-29 14:03 UTC, rartino commented on optimade.rst
> +             "property": "cartesian_site_positions",
```suggestion
             "property": "cartesian_site_positions",
```
Commit this to remove the trailing whitespace that currently breaks tests.

2022-09-29 14:05 UTC, rartino commented on optimade.rst
> +  It is possible to request only part of a trajectory and to request only 1 out of every n frames.
I've added as a separate comment (look at the bottom of this PR discussion) the edit that removes the trailing whitespace that presently breaks the tests. The rest of my code suggestions should not break anything.

2022-09-29 14:10 UTC, JPBergsma commented on optimade.rst
> +             "property": "cartesian_site_positions",
Thanks, that seems to have done the trick.

2022-09-29 14:22 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
Yes, I meant that MUST (sorry for being unclear, it looked more clear when I commented inline in the view differences mode). From your discussion above I gather that it has to do with the PR wanting to enable queries on subfields of `reference_structure` but without the dot notation. However, I'd argue that this is not easily understood from the sentence as phrased now. I also agree with @merkys that it would be better to avoid this somewhat unexpected extension to the protocol.

If `reference_structure.nsites` feels bulky (and I do somewhat agree with that), why not just skip bundling all this inside a `reference_structure` and instead define them as outermost properties, and in each description say that they refer to a reference structure representative of the structures in the trajectory?

2022-09-29 14:41 UTC, ml-evs commented on optimade.rst
> +  It can be used to select trajectories with queries and to give a quick visual impression of the structures in this trajectory.
An attempt at rewording to better reflect (my understanding of) the purpose of this field

```suggestion
- **Description**: A representative example of the structures that comprise trajectory.
  This structure provides an overview of the trajectory and is used when filtering trajectories according to fixed properties of the underlying frames, such as composition or dimensionality.
```

2022-09-29 14:42 UTC, ml-evs commented on optimade.rst
> +  - This reference frame has the same properties as the `Structures Entries`_ namely:
```suggestion
  - This reference frame has the same properties outlined in `Structures Entries`_, namely:
```

2022-09-29 14:46 UTC, ml-evs commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
```suggestion
- **Description**: The :entry:`trajectories` entry is used to share data belonging to indexable sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
```

Not sure if "indexable"/"indexed" is quite what I mean here, but some words that distinguish this field from a collection of structures would be useful, i.e., collections could be used to store a sequence of structures, but there is no mechanism (yet discussed) for slicing/indexing within collections, which I think is the main distinction here (perhaps @rartino has thoughts given his comment on collections elsewhere).

2022-09-29 14:47 UTC, ml-evs commented on optimade.rst
> +- **Description**: The number of the frames in the trajectory.
```suggestion
- **Description**: The number of frames in the trajectory.
```

2022-09-29 14:50 UTC, ml-evs commented on optimade.rst
> +  - MUST be :val:`null` or omitted if `reference_structure`_ is not in the trajectory.
```suggestion
  - SHOULD NOT be :val:`null` if the `reference_structure`_ exactly matches the frame at the index `reference_frame`_ in the trajectory.
  - MUST be :val:`null` or omitted if `reference_structure`_ is not an exact match to any one frame in the trajectory.
```

2022-09-29 14:52 UTC, ml-evs commented on optimade.rst
> +- **Description**: The number of the frames in the trajectory.
More meta question, is this equal to the number of frames in the OPTIMADE representation of the trajectory, or the trajectory as simulated (e.g., `ceil(total_time / time_step)` for MD). The description might have to be tweaked to make either direction clearer.

2022-09-29 14:57 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
The structure properties keys like `nsites` can already be in the outermost properties. E.g. in a grand canonical simulation, the number of particles can change during the simulation. So there would already be a trajectory property 'nsites' holding a dictionary with properties like frame_serialization_format and the values of `nsites` at each of the frames. So it is not possible to place these fields in the outermost level.

2022-09-29 16:21 UTC, JPBergsma commented
> Merkys: Both requesting frame ranges via URL query parameters and returning their values inside trajectory entries also seem to deviate from OPTIMADE-ish and JSON:API-ish way of doing things. Maybe frame range could be made a subresource of a trajectory? For example, instead of requesting /trajectories/1?first_frame=10&last_frame=100&frame_step=20 we could request /trajectories/1/10-20-100? This would then return fields describing the frame range, but not the trajectory.

@giovannipizzi requested that I would include the frame ranges within the response. If I remember correctly, he found it clearer to return it with the trajectory property as it may not be immediately clear what the first frame and last frame are in case the frame_serialization_format is explicit_regular_sparse. 

The method you suggest for selecting frames is quite universal. It should also apply to other future endpoints that could have some form of indexing. So we will need to consider such future use cases as well.  
I think that 10-20-100 would at present be a valid id. So we would need to add a rule like:   "id's cannot contain a dash '-' ".

Do I understand correctly that with " This would then return fields describing the frame range, but not the trajectory."  you mean you would not return the fields: available_properties, reference_structures, nframes and reference_frame when only a subrange of the trajectory is requested?

2022-09-30 08:54 UTC, JPBergsma commented on optimade.rst
> +  Queries on individual frames are not supported.
This text is part of the general description of the trajectory endpoint, and together with the previous paragraph it gives a summary of what the trajectory endpoint is. 
The information in this section can also be found elsewhere in the text. So I think it can be removed without changing the specification of the trajectory endpoint, although it would make it more difficult to get a good idea of what the trajectory endpoint is with a quick glance.
I'll remove this section, as both you and Merkys seem to be in favour of removing it.

2022-10-03 09:18 UTC, rartino commented on optimade.rst
> +  It can be used to select trajectories with queries and to give a quick visual impression of the structures in this trajectory.
It has to be "a trajectory" or "the trajectory" on the first line, right? (@ml-evs if you agree - just edit your 'suggested change')

2022-10-03 15:25 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
I am not sure what you mean with indexable. It is not my intention to support queries on individual frames.
So they do not need to be indexed by the database backend.

I do not think we should make an artificial distinction between collections and trajectories. In principle, the trajectory endpoint can be used to share collections of structures as well. The use of a reference_structure however only makes sense when the structures have a lot of similarities. If the structures are very diverse, you would not be able to find them efficiently with queries.

Perhaps we could use "sequences of similar structures" but I am not sure whether this would be clear to all readers.

@rartino What do you mean with jumping back and forth? 

In the BioExcel case, we generate the cartesian_site_positions for each of the frames from a list of 32-bit floating point values. We know the number of particles and the number of bytes needed to store the coordinates, so we can set the position of the file pointer to read any frame we want. @rartino is this what you meant with generated on the fly?
They generate some of the files for their files endpoint on the fly as well.

2022-10-03 16:26 UTC, JPBergsma commented on optimade.rst
> +  It can be used to select trajectories with queries and to give a quick visual impression of the structures in this trajectory.
I think "make up" is more common than "comprise" so I'll used that instead. 
I am not sure "overview" is entirely correct word here. To me it suggests some kind of average which is not what this structure is. Therefore I removed "provides an overview of the trajectory and" from Matthews suggestion.

2022-10-04 09:17 UTC, rartino commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
With "jumping back and forth", I mean that a server support clients to ask for, e.g., frame 10-30, 100-120, and then 60-80, etc. I'd be very happy to see this functionality as an optional part of the standard; and it is great that you have found a way to efficiently handle these requests for your data set. However, not all providers - including myself - will be able to provide this feature at a reasonable resource usage. For ourselves, my hope is that the standard will allow me to provide our MD run data via the `/trajectory` endpoint metadata, and then providing the trajectory data *only* via a "next"-link paginated unbroken sequence of frames.

Regarding the terminology of sequences vs sets. The design of `/trajectory` is that the frames are ordered using an unbroken sequence of integers. I do not see why we need to relate this to any underlying "physical" relationship between the frames, it is IMO correct to describe the trajectory entry type to be metadata + a sequence of frames.

2022-10-04 09:45 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The number of the frames in the trajectory.
Good point. I would argue that it is the number of frames exposed by the API. So it would not necessarily match the number of calculation steps used to calculate the trajectory.

2022-10-04 09:47 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
Oh, ok - I realize from this reply that I had missed how the current design mixes everything - both trajectory metadata and frame data - under "the same entry" in a way this is a bit at odds with the jsonapi design and relies on giving quite a special role to `response_fields`.

I understand that this may have already been discussed at length, and settled, by the people partaking in the design discussions on trajectories on the last meeting. Nevertheless, why did we not settle for a design more in line with the articles and comments examples from JSON API? There, one retrieve data about article 1 as:
  http://example.com/articles/1
and its comments as:
  http://example.com/articles/1/comments

For us, that would suggest a design more in line with, e.g.:
  http://example.com/trajectories/1
and:
  http://example.com/trajectories/1/frames
where one could then specify a frame range using frame properties, e.g.,
  http://example.com/trajectories/1/frames&filter=framenbr>42 and framenbr<42
The response to these request could then be more or less the same as trajectory data example in this PR.

Is there a reason the design isn't like this?

2022-10-04 10:51 UTC, merkys commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
Overall, query support for the reference frame only makes little sense to me. Consider a situation where the reference frame does not match client's filter although there are frames that would. Related to that, will there be any guidelines for reference frame selection?

Maybe it would be better to include ranges (min, max) of each parameter instead, but then the number of parameters is allowed to change if, let's say, new particles appear in some of the frames. Maybe it is then better to support queries on parameters that are guaranteed to stay fixed in a simulation, for example, cell parameters in invariable-cell simulations?

2022-10-04 14:31 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
@merkys 
There is no guideline, it is up to the database provider to decide which frame is most representative. 
I thought it would be handy to have a reference structure because it allows making a visualization of the structure in the trajectory.  For most trajectories, only the cartesian_site_positions change, so the reference structure is sufficient for querying.

For those simulations where other properties change, such as the elements that are present or the number of atoms, it is not ideal.
A quick fix would be to add fields to the individual trajectory properties. So we could have properties like: `nsites.average`, `nsites.minimum`, `nsites.maximum` and `elements.set` to allow more flexible querying.
For most of the optimade fields this would work.
For chemical formula's and lattice vectors it is however not immediately obvious how this should be done, as there is not a clear way to define a minimum or a maximum and there are a practically infinite number of possible values.
These fields are however not so interesting for querying. But it does mean we cannot make fields like `.minimum` and `.set` 
MUST fields.

Trajectories can have 100.000's of frames, so selecting trajectories by querying individual frames does not seem practical.

2022-10-04 16:16 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
@rartino 
I don't think we discussed this option.
In the current proposal, all the data is contained in one response, so a response would be similar to a file format, which probably makes it a bit easier to process the response.  
(Although large trajectories may need to be split up, as processing large JSON files can be difficult.)

By having a separate endpoint for the frames, I would also expect that the frames behave as objects on their own, just as for example the structures at the structures endpoint. 
So I would expect a return like `data:[{data_frame_1}, {data_frame_2}, {data_frame_3},...]`
Where each data_frame would contain all the data belonging to that frame. 
This would however give a larger response than the data structure in the trajectory proposal and would also be more difficult to generate for the server. Converting a single array to a string can be done fairly fast with NumPy. Generating all the individual frames would however require a lot more looping, which is relatively slow in python.

2022-10-05 10:33 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
We have a REST api, so the server does not keep track of what the client has previously requested.
Your server thus MUST be able to handle such requests, assuming that the client requests the ranges(10-30, 100-120, and then 60-80) in separate requests. 

In what kind of format do you store your trajectory data? If it is a fixed width format, you can calculate where in the file a new frame starts.

2022-10-05 11:03 UTC, rartino commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
> We have a REST api, so the server does not keep track of what the client has previously requested.

This is frequently not the case in practice for many REST implementations, and when using the approach of giving out a 'handle' that the client uses to represent the state it can be argued it is not against what is meant by the 'statelessness' of REST. Anyone with that handle can make the same continuation request, so the *protocol* is stateless.

> Your server thus MUST be able to handle such requests, assuming that the client requests the ranges(10-30, 100-120, and then 60-80) in separate requests.

I do not see why this has to be a MUST-level requirement. Surely, if we agree on it, we can put it on the level of providing an OPTIMADE paginated response of the frame data - which allows me to just provide a 'next' link that embeds the state handle? I do not think I will be able to deliver random access for our MD data.

> In what kind of format do you store your trajectory data? If it is a fixed width format, you can calculate where in the file a new frame starts.

Most of what we have so far is in bz2:ed VASP XDATCAR files; where my intent was to translate them on-the-fly frame-by-frame in sequence as the data is requested.

2022-10-05 15:18 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
You certainly have a point in that one would expect:

  http://example.com/trajectories/1/frames

to just return a sequence of "frames"-type jsonapi resource objects, and we apparently want to stay away from that for efficiency reasons and instead provide data in separate sequences for everything that can be listed in `available_properties`. It still seems to me as a smaller deviation from the OPTIMADE and jsonapi structure to do something like this:
  http://example.com/trajectories/1/frameset?filter=framenbr>10 and framenbr <100
and allow a frameset to be more of a dynamically generated resource object that represents the data connected to a sequence of frames.

Note that this type of syntax also makes it possible to formulate the type of search that @merkys was asking about via, e.g.:

  http://example.com/trajectories/1/frameset?filter=nsites=42

although, as you say, I would expect few provides to implement this.

I saw that @merkys was actually onto a similar line of thinking with the some kind of sub-encoding construct like `http://example.com/trajectories/1/10-20-100`, although, I think that is further from the jsonapi structure than the above.

2022-10-05 16:23 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
> I do not see why this has to be a MUST-level requirement. Surely, if we agree on it, we can put it on the level of providing an OPTIMADE paginated response of the frame data - which allows me to just provide a 'next' link that embeds the state handle? I do not think I will be able to deliver random access for our MD data.

Perhaps a MUST level is too strong and SHOULD, would be a better. 
Returning the whole trajectory instead of only a part of the trajectory would however be quite inefficient, and I do not see any case where it would be impossible to return a subrange of frames.
Making a list of pointers which specify where in the file each frame starts should be possible for nearly all trajectory file formats. 
The ability to return frames from a certain pointer onward would also be needed to handle the next link so that part would not require any extra work.

So I think it would be possible to implement this for most if not all databases. Finally, it would always be possible to convert the data to a data format that is easier to share. 

In case we do make it optional, we should define fields at the info endpoint where a client can check which methods are supported by the server.
 
If a server does not support slicing of the trajectory, you would have to send the whole trajectory. In that case it would be more efficient to send the bzipped trajectory file directly, although it would make processing the data more difficult for the client..

>  Most of what we have so far is in bz2:ed VASP XDATCAR files; where my intent was to translate them on-the-fly frame-by-frame in sequence as the data is requested.

Is this a good example of a [VASP XDATCAR file](https://www.ovito.org/wp-content/uploads/asgarosforum/2882/firstframesXDATCAR.txt) ?
It seems that in that case, each frame has the same size, so you can calculate where the data for a certain frame begins.

The BZIP2 compression makes things more complicated, but not impossible.
A BZIP2 file contains blocks that can be decompressed individually. So it is not necessary to decompress the entire file.
Each block contains a fixed amount of data. So we can calculate which blocks we need to decompress. Unfortunately, the BZIP2 format does not store the size of the compressed blocks, so we will have to make and store a list with the starting points of each block. With this list, we can then determine which blocks we need to decode. 

An alternative approach would be to start decompressing the bzip2 file at approximately the correct location (each block will contain the same type of data, so they will all have approximately the same size.) From that point, you can look for the magic byte sequences that define the start of a block. Once the block is decoded, you can check the value of the "Direct configuration" to see if you are at the correct frame.

2022-10-06 10:08 UTC, JPBergsma commented on optimade.rst
> +  This makes it easier for a client to estimate the amount of data a query returns.
I am starting to wonder whether we really need the available properties field. 
If we no longer support redirecting queries to the reference structure we could perform queries directly on the properties. 
Instead of only making the properties available when specifically requested in the response field, We could do this just for the values subfield. In that case we could get rid of the available properties field all together.

2022-10-07 12:01 UTC, rartino commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
> Returning the whole trajectory instead of only a part of the trajectory would however be quite inefficient, and I do not see any case where it would be impossible to return a subrange of frames.

The way I see OPTIMADE design, it has never been about what is technically possible/impossible, but that we do not want to put a burden on providers to have to reorganize their data and change the tables/documents/hierarchies in their underlying backend to participate. I feel pretty safe in saying that not everyone with MD data stored today can provide access to individual frames in that data with a reasonable resource usage. 

It is also not clear to me why this is such an important feature that needs to be on MUST level? I've participated in plenty of projects dealing with MD data. In many of them it could have been useful with a standardized format (and a standard communications protocol to transfer the data), but I cannot recall any case where a strong need appeared for transferring partial ranges of MD data. I understand that use cases exist -- e.g., if one wants build a UI on top of OPTIMADE that allows looking at the frames and "scrubbing" the timeline -- so I am very happy this part of the standard exist. However, do we prefer people to not share their MD data at all, rather than share it without random access to frames? Because that is what we are saying with "MUST".

> The ability to return frames from a certain pointer onward would also be needed to handle the next link so that part would not require any extra work.

No. All I need to do is:
- Open a file pointer on the initial request and associate the pointer with an abstract handle id.
- Read as many frames that fits in a paginated response.
- Give a 'next' link that references that handle.
- The next request I receive that has that handle reference, I use the file pointer to transfer the next paginated part of the MD data, until the end is reached.
- I remove expired handles from the dictionary that keeps track of them after a set timeout; requests referencing an unknown/expired handle receives an error indicating that the client has to re-query.

> If a server does not support slicing of the trajectory, you would have to send the whole trajectory. In that case it would be more efficient to send the bzipped trajectory file directly, although it would make processing the data more difficult for the client..

The point for interoperability is to provide data using a carefully standardized format. I don't think bzip2:ed VASP XDATCARs is a good standard.

> Is this a good example of a VASP XDATCAR file ? [...] so we will have to make and store a list with the starting points of each block.

Right, so you end up prescribing that I have to restructure my data representation - in this case build indexes we don't yet have. It isn't that I *cannot* do that - I *can* even just pre-convert all our MD data into an OPTIMADE friendly format and also store them that way. But, it is a highly non-trivial amount of work.

2022-10-07 12:09 UTC, rartino commented on optimade.rst
> +  This makes it easier for a client to estimate the amount of data a query returns.
`available_properties` made sense to me... It allows me to query trajectories that have certain types of data, e.g., "give me all trajectories with force data". It also doubles by describing the underlying serialization model for that data. This I would probably never query on - but is good to be able to know what to expect (e.g. to prepare data structures) upon retrieving trajectory data.

2022-10-11 14:23 UTC, JPBergsma commented on optimade.rst
> +  This makes it easier for a client to estimate the amount of data a query returns.
It is indeed important to be able to check for which fields data is present in the trajectory. 

If we do not redirect queries to the `reference_structure`, we can however perform queries directly on the fields in the trajectory. So you could do a query like: `filter=lattice_vectors IS KNOWN AND cartesian_site_positions.nvalues > 1`
to find a structure for which the lattice vectors are defined and for which there is more than 1 frame for which the particle positions have been recorded.
So far, fields like `cartesian_site_positions.frame_serialization_method` were present in both the `available_properties` list and the trajectory property itself. So, I think we can now get rid of this kind of duplication. It also makes this kind of queries a bit simpler. e.g `lattice_vectors IS KNOWN` vs `available_properties.property HAS  "lattice_vectors"`

We however, do have to use something like `response_fields=cartesian_site_positions.values` to request the values that are not shared by default.

2022-10-14 13:00 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
> The point for interoperability is to provide data using a carefully standardized format. I don't think bzip2:ed VASP XDATCARs is a good standard.

Good point.

> I feel pretty safe in saying that not everyone with MD data stored today can provide access to individual frames in that data with a reasonable resource usage.

That's why I wrote:
> Perhaps a MUST level is too strong and SHOULD, would be a better.
Although, I think returning only a part of a trajectory instead of the whole trajectory would be faster for practically all file types.

>No. All I need to do is:
> -  Open a file pointer on the initial request and associate the pointer with an abstract handle id.
> -  Read as many frames that fits in a paginated response.
> -  Give a 'next' link that references that handle.
> -  The next request I receive that has that handle reference, I use the file pointer to transfer the next paginated part of the MD data, until the end is reached.
> -  I remove expired handles from the dictionary that keeps track of them after a set timeout; requests referencing an unknown/expired handle receives an error indicating that the client has to re-query.

I think this approach has quite some similarities with what I suggested. 
In my case, I would store a list with the file pointers at which each frame starts.
In your case, you would store a dictionary with the handle IDs as the keys and the file pointer from which the rest of the trajectory should be read as one of the keys.
So in both cases, we need to be able to read frames from a certain file pointer onward.

Your method has the advantage that:
- You could use a much smaller next link because you could store the rest of the query with the handle. 
- Your dictionary with the handles would be much smaller than the list I proposed.

The disadvantages would be that:
- you would not be able to provide random access.
- If there are multiple threads/servers, you would need to either make sure the next request was executed by the same server/thread or synchronize your dictionary between different servers/threads.

2022-10-14 14:00 UTC, rartino commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
Right, so we've settled on not MUST level. I think MAY would be more suitable, but that distinction is not so important.

But, just to clarify something on the point you are making:

> Your dictionary with the handles would be much smaller than the list I proposed.

Indeed - the overhead in keeping track of a list of open file pointers scales with the number of users who simultaneously request data from the server(s) at the cost of a file pointer/user. The overhead of pre-caching pointers to frames scales with the total number of MD frames in my database. In normal circumstances these two approaches have a qualitative difference in resource usage.

Also, you forgot in the list that pointers to frames require significant pre-processing of data before it can be served.

Finally, on this:
> I think returning only a part of a trajectory instead of the whole trajectory would be faster for practically all file types.

Well, I've certainly seen gzip:ed XDATCAR files in the past.

2022-10-15 18:57 UTC, JPBergsma commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
I have changed MUST to SHOULD at line 2982.

>  Well, I've certainly seen gzip:ed XDATCAR files in the past.
It depends on which program was used to generate the gzip files, but often they can indeed only be decoded from the start. 

In principle, it would still be possible to provide access at fixed points in the file by storing the preceding 32kb along with the file pointer. Depending on the size of the frames, this may however be a non-negligible amount of data.  
So it could be impractical to do this for every frame, and such access points could, for example, only be there for one out of every 100 frames.  You would also have to store this 32kb of data, but as you keep track of far fewer points from which the file could be accessed, it would be much less data.

2022-10-16 19:38 UTC, rartino commented on optimade.rst
> +- **Description**: The :entry:`trajectories` entry is used to share data belonging to sequences of structures, e.g., from a molecular dynamics simulation or a Monte Carlo simulation.
To return to the topic of this thread - especially with MUST -> SHOULD, IMO "indexable" should not be part of the definition of a trajectory.

@ml-evs: Isn't "sequence" (which is already there) the word that distinguishes a trajectory from a set? I.e., the fact that the frames are numbered with a contiguous list of integers?

2022-10-16 21:20 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
I've thought some more about this - there really is no way to do it "cleanly" within the jsonapi data model. I seem to recall @ml-evs pointing out at an OPTIMADE web meeting that the key issue is that we do not have a way to handle properties so big that they need pagination. So, the solution is to either (i) not have such data fields (i.e., divide huge entries into sub datatypes like above, e.g., frames / frameranges, etc.) or (ii) to invent a new mechanism to handle such properties. Both (i) and (ii) have their benefits and drawbacks.

The current PR has a design for (ii) that I think is a good solution. However, I also think we should be careful not to end up with different entries (re-)inventing this mechanism in different ways. So, I hope we can settle for semantics that will be somewhat generalizeable. (Which is also the only way we can make this work with the new property data definitions that were recently merged...)

So, looking at how one could think of @JPBergsma's design in more general terms:

- Some properties in an entry are serialized. Perhaps this should be made very obvious, e.g., by a common prefix, i.e., `serialized_cartesian_site_positions`?
- The data in serialized properties should not be returned unless specific REST query parameters relating to serialization are specified. These parameters should then be standardized on OPTIMADE protocol level (rather than for a specific entry); so something like `series_start` and `series_count` or `series_end`, where the only MUST requirement is to accept `series_start=1` to return a paginated series of responses according to what @JPBergsma describes in this PR.
- But then - instead of bundling the serialization info in `available_properties`, it would seem easier to just agree that the serialization info is what is returned for serialized fields when no serialization parameters are specified? E.g., so a response without the `series_start` parameter would return for `serialized_carteasian_site_positions`:
  ```
           {
             "frame_serialization_format": "explicit",
             "nvalues": 1000
           }
  ```
  whereas if one sets `series_start=1`, one gets data in this, and all other, serialized fields.

2022-10-17 11:07 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
We can indeed prefix the properties names like `serialized_cartesian_site_positions`.

> - The data in serialized properties should not be returned unless specific REST query parameters relating to serialization are specified. These parameters should then be standardized on OPTIMADE protocol level (rather than for a specific entry); so something like `series_start` and `series_count` or `series_end`, where the only MUST requirement is to accept `series_start=1` to return a paginated series of responses according to what @JPBergsma describes in this PR.

Do I understand correctly that you want to replace `first_frame` with `series_start`, `last_frame` with `series_end` and `frame_step` with `series_count`, so these parameter names are more appropriate for reuse in future endpoints?
I think `series_step` would be a more appropriate replacement for `frame_step`. With `series_count` My first guess would be that it is the number of frames that should be returned.

> But then - instead of bundling the serialization info in available_properties, it would seem easier to just agree that the serialization info is what is returned for serialized fields when no serialization parameters are specified? E.g., so a response without the series_start parameter would return for `serialized_carteasian_site_positions`:
  ```
           {
             "frame_serialization_format": "explicit",
             "nvalues": 1000
           }
  ```

That was what I was thinking about in my post below:
> So far, fields like cartesian_site_positions.frame_serialization_method were present in both the available_properties list and the trajectory property itself. So, I think we can now get rid of this kind of duplication. It also makes this kind of queries a bit simpler. e.g lattice_vectors IS KNOWN vs available_properties.property HAS "lattice_vectors"

2022-10-17 11:53 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
> Do I understand correctly that you want to replace `first_frame` with `series_start`, `last_frame` with `series_end` and `frame_step` with `series_count`, so these parameter names are more appropriate for reuse in future endpoints?

Right, and the definitions of them being lifted up in the more general parts of the OPTIMADE specification.

My thinking is that `frame` is very trajectory-specific language. I'm far from convinced `series` is the best term either. When I was writing up my reply, I first wrote `sequence_start`, etc., but when I saw that you were already using the term "serialization" for "serialization formats" etc, and went with that for clarity. However, the "thing" that is special with these properties isn't so much that they are "serialized" (everything is serialized when communicated over HTTP), it is that they represent some form of sequential data, I think. (We were indeed onto this in another discussion spawned by @ml-evs.)

> I think series_step would be a more appropriate replacement for frame_step. With series_count My first guess would be that it is the number of frames that should be returned.

Fair point about wanting an (optional) `series_step` or equivalent - it should also be included. I did actually mean `series_count` as you interpreted it, and meant to reflect on whether it would be better (more generalizeable) to give a count rather than the end value. Why did you end up with `frame_end` rather than `frame_count` in your design? 

This is, however, a side point. I think it is best if we settle for a single "magical" query parameter that enable output of serialized/sequenced data; which then should be `series_start`. Hence, it probably should be a client error to specify `series_step` without `series_start`.

2022-10-17 13:30 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
We could make `series_start` the "magical" parameter, although the presence of any of `series_start`, `series_count` `series_end` or `series_step`, would indicate that the user wants trajectory information.

It was more than a year ago that we discussed this, so I am not a 100% sure what the reasons for choosing to specify the end point over specifying the number of frames that needed to be returned were. It may simply have been that in python, you can do array indexing as `List[start: end(exclusive): step_size]`. So it seemed logical to do this here in the same way, as this would be the easiest to implement in python.

2022-10-17 14:19 UTC, rartino commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
> We could make `series_start` the "magical" parameter, although the presence of any of `series_start`, `series_count` `series_end` or `series_step`, would indicate that the user wants trajectory information.

I do not have a strong opinion; we could indeed say that all of these are "magical". The relatively weak argument to specify a single one (i.e., `series_start`) is that I think the protocol becomes slightly more robust to change. If we later standardize yet another parameter - or if someone makes up their own, e.g., `_exmpl_series_blockify`. If the specification clearly says "Serialized data is returned if, and only if, the query parameter `series_start` is included with a non-empty value in the request." then clients won't expect that just including, e.g., `?_exmpl_series_blockify=1` will return serialized data (which a server that do not recognize that parameter couldn't understand.) 

> It may simply have been that in python, you can do array indexing as `List[start: end(exclusive): step_size]`. So it seemed logical to do this here in the same way, as this would be the easiest to implement in python.

Not very important at all, but my gut feeling is that start + count is slightly more common in similar interfaces for some minor reasons, like: "start from frame 5 and give me 5 frames" unambiguously returns frames 5, 6, 7, 8, 9. For "start from frame 5 and end at frame 10" I'd have to check documentation on whether frame 10 will be returned or not. But if anyone has a slight inclination towards start + end, it would be fine.

2022-10-17 16:11 UTC, JPBergsma commented on optimade.rst
> +  - Queries on the trajectories MUST be done on the information supplied in the :property:`reference_structure` when the queried property is in the :property:`reference_structure`.
In some cases, the query would be shorter because one of the other parameters e.g.(series_end or series_count) would have been specified already. Other than that, there is no real advantage to allowing multiple parameters to trigger sending the values belonging to the trajectory. Although I do like the symmetry of having all these parameters behave in the same way.

We used the terms first and last to make it a bit clearer that it is an inclusive range. At least, I interpret "last" as inclusive.
The number of values returned may be less than `series_count` because not all properties have values defined for each frame. Perhaps this is confusing to some.
 
But I do not have a strong preference for either of these two discussion points.

2023-06-16 12:30 UTC, vaitkus commented on optimade.rst
> +- **Requirements/Conventions**: The values MUST be larger than 0 and equal or less than nframes.
```suggestion
- **Requirements/Conventions**: The values MUST be larger than 0 and equal to or less than nframes.
```

2023-06-29 16:58 UTC, JPBergsma commented on optimade.rst
> +- **Requirements/Conventions**: The values MUST be larger than 0 and equal or less than nframes.
During the optimade meeting we decided to start counting from 0 instead, so this remark is no longer valid.

2024-01-17 15:10 UTC, vaitkus commented on optimade.rst
> +~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~
```

2024-01-17 15:10 UTC, vaitkus commented on optimade.rst
> +  }
```suggestion
  {
    "data":{
      "id": "traj00000001",
      "type": "trajectories",
      "attributes": {
        "last_modified":"2021-07-16T18:02:03Z",
        "elements": [["H","O"]],
        "nelements": [2],
        "elements_ratios": [[0.666667,0.333333]],
        "chemical_formula_descriptive": ["H2O"],
        "chemical_formula_reduced": ["H2O"],
        "chemical_formula_anonymous": ["A2B"],
        "dimension_types":[[0,0,0]],
        "nperiodic_dimensions": [0],
        "lattice_vectors" : [[[4.0,0.0,0.0],[0.0,4.0,0.0],[0.0,0.0,4.0]]],
        "cartesian_site_positions" : null,
        "nsites":[3],
        "species_at_sites":[["O1","H1","H2"]],
        "species":[[
          {
            "name":"O1",
            "chemical_symbols":["O"],
            "concentration":[1.0]
          },
          {
            "name":"H1",
            "chemical_symbols":["H"],
            "concentration":[1.0]
          },
          {
            "name":"H2",
            "chemical_symbols":["H"],
            "concentration":[1.0]
          }
        ]],
        "reference_frames": [1],
        "nframes": [360],
        "_exmpl_temperature": null,
        "_exmpl_ekin": null
      },
      "meta":{
        "property_metadata":{
          "cartesian_site_positions":{
            "range":{
              "indexable_dim": ["frames"],
              "data_range": [{
                  "start": 1,
                  "step": 1,
                  "stop": 360
                },{
                  "start": 1,
                  "step": 1,
                  "stop": 3
                },{
                  "start": 1,
                  "step": 1,
                  "stop": 3
                }],
              "layout":"dense",
              "nvalues": 3240
            }
          },
          "_exmpl_temperature":{
            "range": {
              "nvalues": 144,
              "indexable_dim": ["frames"],
              "data_range": [
                {
                  "start": 1,
                  "stop": 360,
                  "step": null
                }
              ],
              "layout": "sparse"
            }
          },
          "_exmpl_ekin":{
            "range": {
              "nvalues": 180,
              "indexable_dim": ["frames"],
              "data_range": [
                {
                  "start": 1,
                  "stop": 360,
                  "step": 2
                }
              ],
              "layout":"dense"
            }
          }
        },
        "partial_data_links": {
          "cartesian_site_positions": [
            {
              "format": "jsonlines",
              "link": "https://example.org/optimade/v1.2/extensions/partial_data/trajectories/traj00000001/cartesian_site_positions/jsonlines"
            },{
              "format": "_exmpl_xyz",
              "link": "https://example.org/optimade/v1.2/extensions/partial_data/trajectories/traj00000001/cartesian_site_positions/xyz"
            }
          ],
          "_exmpl_temperature": [
            {
              "format": "jsonlines",
              "link": "https://example.org/optimade/v1.2/extensions/partial_data/trajectories/traj00000001/temperature/jsonlines"
            }
          ],
          "_exmpl_ekin": [
            {
              "format": "jsonlines",
              "link": "https://example.org/optimade/v1.2/extensions/partial_data/trajectories/traj00000001/ekin/jsonlines"
            }
          ]
        }
      },
      "relationships": {
        "references": {
          "data": [
            {
              "type": "references",
              "id": "dummy/2019"
            }
          ]
        }
      }
    }
    //...
  }
```

2024-07-04 07:27 UTC, giovannipizzi commented on optimade.rst
> +  }
For simplicity I'm merging this without carefully checking, since anyway the example needs to be adapted afterwards

2025-09-17 06:36 UTC, sauliusg commented on optimade.rst
> +  :entry:`trajectories` entries have the properties described in the section `Properties Used by Multiple Entry Types`_ as well as the property `nframes`_ and `reference_frames`_.
Note: dim_frames needs to be defined somwhere.

2025-09-17 06:53 UTC, sauliusg commented on optimade.rst
> +        "nframes": [360],
```suggestion
        "nframes": 360,
```

2025-09-18 17:16 UTC, eimrek commented on optimade.rst
> +  In this example, the properties :field:`elements`, :field:`nelements`, and :field:`lattice_vectors` are compacted along the first dimension (`dim_frames`).
`dim_frames` missing from the example?

2025-09-18 17:28 UTC, ml-evs reviewed
Mostly minor rewordings that hopefully improve clarity. 

My only bigger comment is that we should mention partial data somewhere in the trajectories introduction as it is then used in the examples.

It also feels a bit weird to refer to trajectories in the compactable specification, but maybe its unavoidable (or otherwise compactable could be moved to the appendix).

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +One particular example are lists with equal values along a given list axis (e.g., in the case
```suggestion
For example, lists with constant values along a given list axis (e.g., in the case
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +In such case, the server MUST indicate that that dimension is compactable, by setting to :val:`TRUE`
```suggestion
In such cases, the server MUST indicate that the dimension is compactable, by setting to :val:`TRUE`
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +Currently, only one **compact format** is defined, supporting lists with equal values along a given list axis.
```suggestion
Currently, only one **compact format** is defined to support the case where a list  consists of constant values along a given axis.
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  property, thus reducing the amount of data transferred and avoiding to perform separate HTTP requests for each
```suggestion
  property, thus reducing the amount of data transferred and avoiding the need to perform separate requests for each
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +The client MUST be able to handle responses with both compact and non-compact property formats.
```suggestion
A client MUST be able to handle responses with both compact and non-compact property formats.
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  Instead the :field:`_exmpl_timestep` property is not compacted, since it has different values for each frame.
```suggestion
  On the other hand, the :field:`_exmpl_timestep` property is not compacted, since it has different values for each frame.
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  Moreover, the value of the :field:`cartesian_site_positions` property is omitted (with value :val:`null`, as the server deems it to be too large for a single response, e.g. because the number of at
```suggestion
  Moreover, the value of the :field:`cartesian_site_positions` property is omitted (with value :val:`null`, as the server deems it to be too large for a single response) and its content is instead transferred using the large property values protocol (see section `Transmission of large property values`_; for brevity we do not show here the content of the :field:`meta` field).
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  We note that the value to be repeated can be either a single item (as it is the case for :field:`nelements`, to be interpreted as ``[2, 2, 2, 2, 2]``) or a list. In the latter case, the whole list
```suggestion
  The value to be repeated can either be a single item (as it is the case for :field:`nelements`, to be interpreted as :val:`[2, 2, 2, 2, 2]`) or a list. 
  In the latter case, the whole list is repeated, as it is the case for :field:`elements` (to be interpreted as :val:`[["H","O"], ["H","O"], ["H","O"], ["H","O"], ["H","O"]]`) and the :field:`lattice_vectors` (to be interpreted as the repetition of the 3x3 matrix :val:`[[4.0, 0.0, 0.0],[0.0, 4.0, 0.0],[0.0, 0.0, 4.0]]` 5 times, i.e., a trajectory with the same lattice vectors for all 5 frames).
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  The individual steps of the trajectories are called frames.
```suggestion
  Individual steps of trajectories are referred to as frames.
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +    - all custom properties defined in the `Structures Entries`_ endpoint are also used for trajectories, with the following difference: each property is extended by wrapping it in a list, so that th
```suggestion
    - all custom properties defined in the `Structures Entries`_ endpoint are also used for trajectories, with the following difference; each property is extended by wrapping it in a list, so that each custom property of a :entry:`structures` resource becomes a list with an additional first dimension `dim_frames`_ (of size `nframes`_).
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +- **Description**: The number of frames in the trajectory as exposed by the API.
```suggestion
- **Description**: The number of frames in the trajectory as exposed in the resource.
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  E.g., for a 10 ps simulation with calculation steps of 1 fs where data is stored once every 50 fs, nframes = 200.
```suggestion
  For example, a 10 ps simulation with calculation steps of 1 fs where data is stored once every 50 fs, `nframes`_ will be 200.
```

2025-09-18 17:28 UTC, ml-evs commented on optimade.rst
> +  For data-transfer efficiency reasons, the server MAY define as :field:`compactable` the additional first dimension `dim_frames` for some of these properties, so as to return them in the `Compact li
I would also mention partial data here, as this endpoint will be the primary user of it

2025-09-18 18:28 UTC, giovannipizzi commented on optimade.rst
> +  In this example, the properties :field:`elements`, :field:`nelements`, and :field:`lattice_vectors` are compacted along the first dimension (`dim_frames`).
Indeed but it's not part of the response, it's in the property definition.

2025-09-18 18:38 UTC, gmrigna commented on optimade.rst
> +  For data-transfer efficiency reasons, the server MAY define as :field:`compactable` the additional first dimension `dim_frames` for some of these properties, so as to return them in the `Compact li
This will be done in the next commit by @giovannipizzi

2025-09-18 23:23 UTC, rartino commented on optimade.rst
> +If a client finds a string in the :field:`compactable` that it does not recognize (this might happen with major changes of the property definition), it MUST return an error to the user.
```suggestion
If a client finds a string in the :field:`compactable` field that it does not recognize (which may be defined by future versions of this specification), it MUST NOT attempt to interpret the corresponding property value.

2025-09-18 23:32 UTC, rartino commented on optimade.rst
> +  individual property.
```suggestion
- even if in the future a compact format is implemented also in the large-property transfer protocol (described in the section `Transmission of large property values`_), using the approach described here (where data is directly provided in the :field:`data` section) avoids unnecessary separate requests for each individual property.
```

2025-09-19 05:32 UTC, giovannipizzi commented on optimade.rst
> +An appropriate way to communicate the format of the compact representation will then be defined.
```suggestion
```

2025-09-19 05:34 UTC, giovannipizzi commented on optimade.rst
> +    For instance, for the :field:`lattice_vectors` property:
```suggestion
    For instance, for the :field:`lattice_vectors` property of a Trajectory entry:
```

2025-09-19 05:37 UTC, giovannipizzi commented on optimade.rst
> +  - all custom properties defined in the `Structures Entries`_ endpoint are also used for trajectories, with the following difference; each property is extended by wrapping it in a list, so that each
```suggestion
  - all custom properties defined in the `Structures Entries`_ endpoint are also used for trajectories, with the following difference: each property is extended by wrapping it in a list, so that each custom property of a :entry:`structures` resource becomes a list with an additional first dimension of size `nframes`_ (with dimension name ``dim_frames``, as defined in the property definition). This allows these properties to be defined for each frame, and thus possibly change during the trajectory.
```

2025-09-19 05:39 UTC, giovannipizzi commented on optimade.rst
> +- **Description**: The indexes of a set of frames that give a good but very brief overview of the trajectory.
```suggestion
- **Description**: The indices of a set of frames that give a good but very brief overview of the trajectory.
```

2025-09-19 05:39 UTC, giovannipizzi commented on optimade.rst
> +  The first frame could for example be a starting configuration, the second a transition state and the third the final state.
```suggestion
  The first reference frame could for example be a starting configuration, the second a transition state and the third the final state.
```

2025-09-19 06:09 UTC, gmrigna commented on optimade.rst
> +    For instance, for the :field:`lattice_vectors` property:
```suggestion
    For instance, for the :field:`lattice_vectors` property of an entry of type :entry:`trajectories`:
```

2025-09-19 08:27 UTC, giovannipizzi commented on optimade.rst
> +  :entry:`trajectories` entries have the properties described in the section `Properties Used by Multiple Entry Types`_ as well as the property `nframes`_ and `reference_frames`_.
Removed reference to dim_frames to avoid having to define it at this point

2025-09-19 08:46 UTC, giovannipizzi approved these changes
Fantastic work!

2025-09-19 10:51 UTC, merged

2025-09-19 10:52 UTC, rartino commented
@giovannipizzi 🎉🥳