Space group additions: `space_group_hall` and `space_group_it_number`
Materials-Consortia/OPTIMADE pull request #405
Opened 2022-05-30 20:35 UTC by merkys

Partially addresses #35  This PR introduces two symmetry space group notations, Hall symbol and IT number, closely following their usage in CIF. Both Hall symbol and IT number have their drawbacks: in some cases both need additional information to uniquely define symmetry space group of a crystal. To cover this drawback, a list of symmetry operations is needed, and its introduction is envisaged in #35. Nevertheless standardizing Hall symbol and IT number would facilitate searches on these widely used notations.

2022-05-30 21:10 UTC, rartino commented
Correct me if I am wrong, but I have come to the conclusion that it is *not* 100% safe to assume there is a standard Hall symbol for all possibilities - in case a structure isn't placed with a "proper" origin. Is it absolutely safe to assume there is a non-standard Hall symbol that describes structures given with a completely arbitarily origin?

Also, I think I'm for MAY support level on these. If you don't know the symmetry information it can be very expensive (arguably sometimes even impossible) to assign them.

2022-05-31 07:37 UTC, merkys commented
> Correct me if I am wrong, but I have come to the conclusion that it is _not_ 100% safe to assume there is a standard Hall symbol for all possibilities - in case a structure isn't placed with a "proper" origin. Is it absolutely safe to assume there is a non-standard Hall symbol that describes structures given with a completely arbitary origin?

Right, but maybe we can say that only standard Hall symbols are supported, and they should be provided only for structures with "proper" origin? My point is that if we cannot use standard Hall symbol/IT number to unambiguously define symmetry, these fields should be `null`, and in future symmetry operator lists should be used to define such situations.

> Also, I think I'm for MAY support level on these. If you don't know the symmetry information it can be very expensive (arguably sometimes even impossible) to assign them.

Sure, I am fine with OPTIONAL/MAY support level.

2022-05-31 14:55 UTC, rartino requested changes
A few suggested changes

2022-05-31 14:55 UTC, rartino commented on optimade.rst
> +  - Each component of the space group name MUST be separated by a single space symbol.
```suggestion
  - Each component of the Hall symbol MUST be separated by a single space symbol.
  - If there exists a standard Hall symbol which represents the symmetry it SHOULD be used.
  - MUST be null if :property:`nperiodic_dimensions` is not equal to 3.
```

2022-05-31 14:55 UTC, rartino commented on optimade.rst
> +- **Description**: Symmetry space group name as defined in Hall, S. R. (1981), Acta Cryst. A37, 517-525 and erratum (1981), A37, 921.
To be closer to the phrasing of the IUCr, and strictly expressing that it is not just any Hall symbol, but the one that represents the structure:
```suggestion
- **Description**: A Hall space group symbol representing the symmetry of the structure as defined in Hall, S. R. (1981), Acta Cryst. A37, 517-525 and erratum (1981), A37, 921.
```

2022-05-31 14:55 UTC, rartino commented on optimade.rst
> +- **Description**: Symmetry space group number as defined in International Tables for Crystallography Vol. A.
```suggestion
- **Description**: Space group number for the structure assigned by the International Tables for Crystallography Vol. A.
```

2022-05-31 14:55 UTC, rartino commented on optimade.rst
> +  - The integer value MUST be between 1 and 230.
```suggestion
  - The integer value MUST be between 1 and 230.
  - MUST be null if :property:`nperiodic_dimensions` is not equal to 3.
```

2022-05-31 14:57 UTC, rartino commented on optimade.rst
> +  - **Support**: SHOULD be supported by all implementations, i.e., SHOULD NOT be :val:`null`.
```suggestion
  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
```

2022-05-31 14:57 UTC, rartino commented on optimade.rst
> +  - **Support**: SHOULD be supported by all implementations, i.e., SHOULD NOT be :val:`null`.
```suggestion
  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
```

2022-06-01 08:19 UTC, ml-evs approved these changes

2022-06-01 08:19 UTC, merged