Means to specify database license
Materials-Consortia/OPTIMADE pull request #414
Opened 2022-06-02 11:35 UTC by merkys

Fixes #102. After discussions with @rartino in #102 I became convinced that for now a single license for all the data in a database should be sufficient. Should there be parts of database belonging under a different license, they should either be described in database-wide license document, or moved to a separate "sibling" database under a different license.

2022-06-02 11:45 UTC, sauliusg reviewed
The stanza says "all data", but shouldn't we include also "all metadata"?
I was slightly inclined to have a possibility to specify license per record, but I agree that this wold be unnecessary complication for now. We can always upgrade if there is a genuine need.

I would approve the PR if/when the question about metadata is resolved.

2022-06-02 11:49 UTC, merkys commented
> The stanza says "all data", but shouldn't we include also "all metadata"? I was slightly inclined to have a possibility to specify license per record, but I agree that this wold be unnecessary complication for now. We can always upgrade if there is a genuine need.
> 
> I would approve the PR if/when the question about metadata is resolved.

@sauliusg I have added this in 3a678c3.

2022-06-02 12:09 UTC, sauliusg approved these changes

2022-06-02 12:19 UTC, merkys commented
This is an important change (please note `MUST` level of inclusion), thus I would like to make sure that providers-consortium members check it out and let us know should there be a problem with conforming to it.

2022-06-03 08:30 UTC, merkys commented
I have updated the PR to reflect workshop discussions: `license_is_compatible_with_cc_by_4_0` has been replaced by `compatible_licenses` list of SPDX identifiers. The new property is OPTIONAL.

2022-06-03 12:31 UTC, blokhin commented
For the case of the MPDS, we might have multiple licenses for the different sections of our data: CC BY 4.0, commercial/proprietary, per-vendor custom license, etc. We currently use per-entry custom field `_mpds_data_license`, which I would feel strong to recommend as a standard `data_license` / `entry_license` field.

2022-06-06 13:03 UTC, merkys commented
> For the case of the MPDS, we might have multiple licenses for the different sections of our data: CC BY 4.0, commercial/proprietary, per-vendor custom license, etc. We currently use per-entry custom field `_mpds_data_license`, which I would feel strong to recommend as a standard `data_license` / `entry_license` field.

This is a scenario quite closely fitting my reasoning which I have presented in #102 in my discussions with @rartino. If MPDS uses per-entry custom field, why not promote it to the standard? But this probably could be introduced in a follow-up PR in order not to block the current one.

According to this PR, MPDS licensing situation could be solved in two ways:
1. Separate databases (one per each license);
2. Specify all licenses and their governed domains in the top-level license file.

@blokhin Is any of these solutions suitable for MPDS? If so, maybe per-entry licensing could wait for the follow-up PR?

2022-06-06 22:46 UTC, rartino reviewed
Some input on the overall design.

2022-06-06 22:46 UTC, rartino commented on optimade.rst
> +    If :field:`license` and :field:`compatible_licenses` contradict, :field:`compatible_licenses` has precedence.
Based on our Workshop discussion on this and Wikipedia's "definition" of what license compatibility means, I don't think "compatible licenses" is the right term. For this to work, this field simply is a list of licenses that the database owner grant you the data under. So, how about naming it `available_licenses`? 

Also, if there ever was a time to be overly verbose for clarity in this text, this is it; so I suggest adding a bit of text to try to make the commitment of including something in this field more stringently clear.

```suggestion
  - **available\_licenses**: List of SPDX license identifiers specifying a set of alternative licenses under which the client is granted access to the data and metadata in this database.
    Inclusion of a license identifier in the list is a commitment of the database that the rights are in place to grant clients access to all the data and metadata according to the terms of these licenses.
    If the licensing information provided via the field :field:`license` omits licensing options specified in :field:`available_licenses`, or if it otherwise contradicts them, a client MUST still be allowed to interpret the inclusion of a license in :field:`available_licenses` as a full commitment from the database that the data and metadata is available, without exceptions, under the respective licenses.
    If the database cannot make that commitment, e.g., if only part of the data is available under a license, the corresponding license identifier MUST NOT appear in :field:`available_licenses` (but, rather, the field :field:`license` is to be used to clarify the licensing situation.)
    In case the data and metadata is multiply-licensed, identifiers of these multiple licenses SHOULD be provided to let clients know under which conditions the data and metadata can be used.
```

2022-06-06 22:46 UTC, rartino commented on optimade.rst
> +    Example: :field-val:`https://spdx.org/licenses/CC0-1.0`.
It isn't fully clear to me how to evaluate the "MUST point to [the] SPD-hosted license fulltext". Is this saying that if I make my data available under CC-BY-4.0 I MUST put "https://spdx.org/licenses/CC-BY-4.0" in this field? That is to say, I MUST NOT link to my own website where I say, e.g., that ~ "all the structures are indeed fully available under CC-BY-4.0, but it would also be really nice if you guys could please also cite our paper." Because, in that case I don't really like this.

I get a feeling there is an attempt here to make this field 'interpretable' if the license is a standard license. I would rather suggest pointing to `compatible_licenses` (suggested: `available_licenses`) for all client needs of a machine-readable license field.

2022-06-07 08:34 UTC, rartino commented
@blokhin Even with your licensing situation, I hope that you do not have anything against merging this PR that allow linking a database-wide license text, where you can clarify the maybe not so simple licensing situation in MPDS? At the same time, perhaps we can continue the discussion of separate licenses for individual entries in #102? I'll copy your comment there to continue that discussion.

2022-06-13 09:22 UTC, JPBergsma commented on optimade.rst
> +    If the license is included in the `SPDX License List <https://spdx.org/licenses/>`__, then the URL MUST point to SPDX-hosted license fulltext, i.e., it MUST start with :field-val:`https://spdx.or
There may be more databases besides MPDS that use a per entry licencing system. So I think it would be good to specify that in that case, the link should point to a document describing how to find the licence for each entry. Otherwise someone may fill in a null value here, because there is no server wide licence.

2022-06-17 07:14 UTC, rartino commented
@merkys This seems a bit stalled? To move things forward, if you disagree with my suggestions, but don't have time to debate this, perhaps we can simplify the PR back to just a single "free-form" link without any machine-readable version and add the machine readable version in a separate PR?

2022-06-17 14:05 UTC, merkys commented
> @merkys This seems a bit stalled? To move things forward, if you disagree with my suggestions, but don't have time to debate this, perhaps we can simplify the PR back to just a single "free-form" link without any machine-readable version and add the machine readable version in a separate PR?

Yes, I wanted to give some more time for opinions like @blokhin's. But sure, if we can agree on a common subset of this PR, I am fine with stepping back. I would like to have licensing sorted out before the next release, one way or another.

2022-06-17 15:01 UTC, blokhin commented
I'm okay with the database-wide `available_licenses` / `license` fields. But what do you think about the optional per-entry license field?

2022-06-17 15:57 UTC, rartino commented on optimade.rst
> +    If :field:`license` and :field:`compatible_licenses` contradict, :field:`compatible_licenses` has precedence.
@merkys But, this semantic difference is exactly the point. To be meaningful, this field needs to mean that the copyright owner of the database is willing to allow you to use the data under any one of these licenses which is closer to ~= "licenses used by this database" than "licenses compatible with the usage of data in this database" with the accepted meaning of "license compatibility".

I think this is a point we probably should try to agree on before moving forward; because this should at least be understandable by us, if it is to be understandable by anyone else...

2022-06-17 16:00 UTC, rartino commented
@blokhin

My opinion on the per-entry field is that it is best kept as a database-specific field, because it should always have a database-specific meaning defined in the global license. As soon as we standardize a `license` field, rather than `mdps_license`, it means both servers and clients can try to give it meaning outside of the main license info. And IMO they shouldn't.

2022-06-20 06:18 UTC, rartino requested changes
The adjustments I think are needed to address my other point -- i.e., that the link really should be a free link with no requirement to be computer parsed, since `available_licenses` takes that role.

(I'm happy to hear contradicting opinions on this, though - I really don't mean to "steamroll" this PR, just make sure it is will work in a way that can be handled semi-automatically by my client implementation...)

2022-06-20 06:18 UTC, rartino commented on optimade.rst
> +    Example: :field-val:`https://spdx.org/licenses/CC0-1.0`.
```suggestion
  - **license**: A `JSON API links object <http://jsonapi.org/format/1.0/#document-links>`__ giving a URL to a web page containing a human-readable text describing the license (or licensing options if there are multiple) covering all the data and metadata provided in this database.
    Clients are advised not to try automated parsing of this link or its content, but rather rely on the field :field:`licenses` instead.
    Example: :field-val:`https://example.com/licenses/example_license.html`.
```

2022-06-20 06:18 UTC, rartino commented on optimade.rst
> +
```suggestion
  - **available\_licenses**: List of `SPDX license identifiers <https://spdx.org/licenses/>` specifying a set of alternative licenses under which the client is granted access to all the data and metadata in this database.
    if the data and metadata is available under multiple alternative licenses, identifiers of these multiple licenses SHOULD be provided to let clients know under which conditions the data and metadata can be used.
    Inclusion of a license identifier in the list is a commitment of the database that the rights are in place to grant clients access to all the data and metadata according to the terms of either of these licenses (at the choice of the client).
    If the licensing information provided via the field :field:`license` omits licensing options specified in :field:`available_licenses`, or if it otherwise contradicts them, a client MUST still be allowed to interpret the inclusion of a license in :field:`available_licenses` as a full commitment from the database that the data and metadata is available, without exceptions, under the respective licenses.
    If the database cannot make that commitment, e.g., if only part of the data is available under a license, the corresponding license identifier MUST NOT appear in :field:`available_licenses` (but, rather, the field :field:`license` is to be used to clarify the licensing situation.)
        An empty list indicates that none of the SPDX licenses apply for the entirety of the database and that the licensing situation is clarified in human readable form in the field :field:`license`.
```

2022-06-20 06:38 UTC, merkys commented on optimade.rst
> +    Example: :field-val:`https://spdx.org/licenses/CC0-1.0`.
> It isn't fully clear to me how to evaluate the "MUST point to [the] SPD-hosted license fulltext". Is this saying that if I make my data available under CC-BY-4.0 I MUST put "https://spdx.org/licenses/CC-BY-4.0" in this field? That is to say, I MUST NOT link to my own website where I say, e.g., that ~ "all the structures are indeed fully available under CC-BY-4.0, but it would also be really nice if you guys could please also cite our paper." Because, in that case I don't really like this.

Yes, this was my intention here. I understand the need to specify other usage guidelines, but I see these as a separate thing, provided a standard license is used.

> I get a feeling there is an attempt here to make this field 'interpretable' if the license is a standard license. I would rather suggest pointing to `compatible_licenses` (suggested: `available_licenses`) for all client needs of a machine-readable license field.

Yes, having a machine-readable way to specify a license was my intention. But I agree your suggestion of better relying on `compatible_licenses`/`available_licenses` is more natural here.

2022-06-20 06:56 UTC, merkys commented on optimade.rst
> +    If the license is included in the `SPDX License List <https://spdx.org/licenses/>`__, then the URL MUST point to SPDX-hosted license fulltext, i.e., it MUST start with :field-val:`https://spdx.or
I would suggest resolving this by explicitly stating that there is no default value/interpretation of `null` for these licensing properties. In case no pointers are provided in `license` (or `*_licenses`), this means no rights are granted for the client (as is with the [source code](https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it)). I do not want to entangle too much logic around this PR - there is a field for provider to put a link to their license/policies, and it is up to a provider to describe their license/policies in it.

2022-06-20 08:04 UTC, merkys commented on optimade.rst
> +    If :field:`license` and :field:`compatible_licenses` contradict, :field:`compatible_licenses` has precedence.
On second thought, I guess the precise name of the property is not that much of an issue, provided the description is clear. Thus I accepted your subsequent change suggestion.

2022-06-20 08:07 UTC, merkys commented on optimade.rst
> +    Example: :field-val:`https://spdx.org/licenses/CC0-1.0`.
As I accepted your change suggestions, I mark this as resolved now.

2022-06-20 08:10 UTC, rartino commented on optimade.rst
> +    If the license is included in the `SPDX License List <https://spdx.org/licenses/>`__, then the URL MUST point to SPDX-hosted license fulltext, i.e., it MUST start with :field-val:`https://spdx.or
Also, with the latest edits, the text for `license` says that the text it points to may express "(or licensing options if there are multiple)", which I think is the appropriate level of clarification about this.

2022-06-20 08:15 UTC, rartino approved these changes
I think it would be great if @sauliusg has a chance to take a look at the present version before we merge it, since I think he has a good handle on the formalities around licensing. I also recall @giovannipizzi having some thoughts/input on this on the workshop.

2022-06-20 08:36 UTC, merkys commented on optimade.rst
> +    If the license is included in the `SPDX License List <https://spdx.org/licenses/>`__, then the URL MUST point to SPDX-hosted license fulltext, i.e., it MUST start with :field-val:`https://spdx.or
But maybe we need to explicitly state what missing/`null` value for `license` means too?

2022-06-20 09:11 UTC, rartino commented on optimade.rst
> +    If the license is included in the `SPDX License List <https://spdx.org/licenses/>`__, then the URL MUST point to SPDX-hosted license fulltext, i.e., it MUST start with :field-val:`https://spdx.or
Sure, it does not hurt to clarify for both the fields that null/missing means "no license". But, I suppose, in particular `available_licenses` present, and `license` missing should still be interpret able.

2022-06-20 13:53 UTC, blokhin approved these changes

2022-06-29 05:51 UTC, rartino commented
This has sitting approved for a week waiting for further input. In the interest of cleaning up our PRs, I'm going to merge it.

2022-06-29 05:51 UTC, merged

2022-12-06 21:25 UTC, ml-evs commented on optimade.rst
> +    An empty list indicates that none of the SPDX licenses apply for the entirety of the database and that the licensing situation is clarified in human readable form in the field :field:`license`.
Without opening a new issue, I just wanted to clarify something here @merkys (and others). The field `license` is simply a Links object, so when you say "situtation is clarified in human readable form in the field `license`", are you referring to the content served at the URL pointed to be license, or the `meta` section of the Links object?

2022-12-06 21:44 UTC, JPBergsma commented on optimade.rst
> +    An empty list indicates that none of the SPDX licenses apply for the entirety of the database and that the licensing situation is clarified in human readable form in the field :field:`license`.
If I remember the discussion correctly, we were indeed referring to the content of the URL to which the licence link points.

2022-12-07 07:45 UTC, merkys commented on optimade.rst
> +    An empty list indicates that none of the SPDX licenses apply for the entirety of the database and that the licensing situation is clarified in human readable form in the field :field:`license`.
It is `license->href` indeed, worth clarifying.