Add structure_origin property for structures
Materials-Consortia/OPTIMADE pull request #455
Opened 2023-02-20 09:06 UTC by rartino

This is a proposed solution for #406 

Before you fire up your keyboards to comment on all the many ways this can/should be extended to allow other possible aspects representing the full provenance of experimental, computational, and AI-model-created structural information, please realize that this property isn't exactly designed to do that.

This is meant to be "a flag" to address a very real and quite pressing need - which we have experienced ourselves when creating OPTIMADE use examples - to have some relatively simple way to filter out "random noise" when querying the OPTIMADE network for "all structures". Of course, what is random noise for one person is signal for another. I've tried my very best to walk the delicate balance to define *a few* reasonable categories that, based on the discussions in #406, covers actual use cases.

I'd be more than happy to see (and review) a future PR for representing a much more rich account of all the experimental and computational history that led to arriving at some structural information. But, I also believe that representation can co-exist with the "flag" proposed in this PR.

2023-02-20 09:08 UTC, rartino commented on optimade.rst
> +  - If the field is omitted, set to an empty string, or `null` it means the same thing as :val:`unknown`.
```suggestion
  - If the property is omitted, set to an empty string, or `null` it means the same thing as :val:`unknown`.
```

2023-02-20 09:09 UTC, rartino commented on optimade.rst
> +    Providers who want to communicate structural information about compounds that exist only at unusual or extreme conditions should categorize them as :val:`other` and, if desired, use another facil
```suggestion
    Providers who want to communicate structural information about compounds that exist only at unusual or extreme conditions should categorize them as :val:`other` and, if desired, use another facility (e.g., a provider-specific property) to communicate more specific information.
```

2023-02-20 12:36 UTC, vaitkus commented on optimade.rst
> +      For example, experimental structures relaxed using ab-inito calculations are meant to be qualify for this category.
```suggestion
      For example, experimental structures relaxed using ab-initio calculations are meant to qualify for this category.
```

2023-02-20 12:36 UTC, vaitkus commented on optimade.rst
> +    * :val:`hypothetical`: the structural information is known to not have been created in a way that provides no guarantees of producing synthesizable structures or structures found in nature. This
```suggestion
    * :val:`hypothetical`: the structural information is known to have been created in a way that provides no guarantees of producing synthesizable structures or structures found in nature.
      This category is suitable for randomly placed atoms (e.g., meant to provide a starting point for further processing) or outcomes of AI models with predictive power deemed insufficient for the :val:`predicted` category.
```

2023-02-20 12:36 UTC, vaitkus commented on optimade.rst
> +  - Database-specific strings using a database provider prefix (e.g., `_exmpl_experimental_at_extreme_pressure` MAY be used but are strongly discouraged.
```suggestion
  - Database-specific strings using a database provider prefix (e.g., `_exmpl_experimental_at_extreme_pressure`) MAY be used but are strongly discouraged.
```

2023-02-20 12:36 UTC, vaitkus commented on optimade.rst
> +    * :val:`predicted`: the structural information is not directly related to the outcome of an experimental technique on an existing material, but has undergone theoretical processing to suggest it
```suggestion
    * :val:`predicted`: the structural information is not directly related to the outcome of an experimental technique on an existing material, but has undergone theoretical processing to suggest it as a candidate for a synthesizable structure.
      This category includes theoretically invented structures that have been relaxed using ab-initio calculations and found to be close to the convex hull of stability, or structures generated from AI models with a demonstrated reasonable predictive power.
      This category definition also involves a degree of subjectivity that has to be determined by the database provider.
```

2023-02-20 12:39 UTC, rartino commented on optimade.rst
> +    * :val:`hypothetical`: the structural information is known to not have been created in a way that provides no guarantees of producing synthesizable structures or structures found in nature. This
Good catch with that not!

2023-02-21 18:06 UTC, ml-evs reviewed
Thanks for writing this up @rartino. 

I have quite a few comments below but definitely still support the overall idea.

2023-02-21 21:16 UTC, rartino commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
Ok, I don't feel strongly about the explicit "unknown" if you insist on not having it, but there is a subtle difference in meaning between 'null' and 'unknown'. The latter means the database has consciously chosen to mark the structure as 'unknown', whereas 'null' can (and probably does) mean that this information may not be supported at all.

2023-02-21 21:27 UTC, rartino commented on optimade.rst
> +    * :val:`processed`: the structural information originates from experimental data, but has undergone additional processing in such a way that the result is still recognizable as the experimental s
So, I had actually done the same thing (asked ChatGPT - to come up with suggestions :-) ). I decided against "Derived" since aside the meaning sought here - "the structural information derives from the experiment" - the word also has connotations to "mathematical derivations", and thus could confuse someone to think that it is a category for "mathematically derived" structures. I also first liked "Refined", but realized that in some context it is read as positive in value, which isn't necessary correct here.

But I get that "processed" isn't perfect. The key piece of info isn't "derived" or "processed", it is that it is *from experiment* and that is missing in both words.

2023-02-21 21:40 UTC, rartino commented on optimade.rst
> +      Substituting one or more elements in a structure (while, e.g., keeping the experimental coordinates the same) are not meant to qualify for this category.
I think I would say your edge cases are "processing in such a way that the result is still recognizable as the experimental structure."

Perhaps adding another example or two could help clarify. On the other hand, I'm afraid the more details we add, the more we open up for a difficult discussion about where, exactly, the line is drawn; when the somewhat subjective interpretation of the above sentence is meant to be the defining statement.

2023-02-21 21:41 UTC, rartino commented on optimade.rst
> +    * :val:`predicted`: the structural information is not directly related to the outcome of an experimental technique on an existing material, but has undergone theoretical processing to suggest it
Isn't *candidate* and *potentially* redundant?

2023-02-21 21:49 UTC, ml-evs commented on optimade.rst
> +    * :val:`processed`: the structural information originates from experimental data, but has undergone additional processing in such a way that the result is still recognizable as the experimental s
I don't dare ask the Bing bot...

I personally think derived is clear in this context, "experimentally derived" would be common parlance in the literature no? Maybe others will have suggestions too

2023-02-21 22:19 UTC, rartino commented on optimade.rst
> +      This category includes theoretically invented structures that have been relaxed using ab-initio calculations and found to be close to the convex hull of stability, or structures generated from
I see your point that from a data organization perspective, this is more about the relation between this structure and other structures, so in a way it doesn't really "belong" to the structure.

On the other hand, we haven't really made the commitment to organize data that way; perhaps the `/structures` endpoint should be seen more as "give me all you can say that relates to this structure" than "this is the contents of my structure SQL table." There is nothing that prevents an implementation from keeping hull distances in a separate table/document (which is updated when needed) and join it with static structure data to form responses.

And those who do not want to do that do not have to. This category is meant to say *"if you are looking for 'real structures', as the database provider of this data, I suggest you to also consider these structures, even though they are not based on experiments"*. But, the provider can of course decide not to make that kind of recommendation and put all non-experimental structures in `hypothetical`.

> I think we will find that anyone hosting AI-derived data will decide that they have "demonstrated reasonable predictive power".

The key word here was meant to be *demonstrated* more so than *reasonable predictive*, i.e., at least there should have been some form of test, not just some form of experimental AI model aiming (but never tested) to generate stable structures.

Also: about you inserting "reasonable external condition". This applies to all points, and thus was covered below the list. Is it necessary to also place it here?

2023-02-21 22:20 UTC, ml-evs commented on optimade.rst
> +    * :val:`predicted`: the structural information is not directly related to the outcome of an experimental technique on an existing material, but has undergone theoretical processing to suggest it
I read candidate as "fulfills all the criteria to be synthesizable if chosen" which I think is stronger than what we are going for, but if it doesn't help clarify then feel free to resolve/ignore

2023-02-21 22:33 UTC, rartino commented on optimade.rst
> +      This category is suitable for randomly placed atoms (e.g., meant to provide a starting point for further processing) or outcomes of AI models with predictive power deemed insufficient for the :
Reading your suggestion, "hypothetical" was indeed the wrong name for the category I described. But your change here is more that you suggest adding an extra category. I suppose a category for non-stable structures that still have undergone DFT relaxations - or equivalent - can be useful. 

IMO the definition shouldn't be phrased as there being a guarantee that they are not thermodynamically stable. Just that they are "relaxed" (and haven't been placed in another category).

I also feel odd about saying that an AI model does "local optimization". Does it make sense to formulate it that these structures are predicted, by *ab inito* or AI models, to be close to an energy surface minimum?

2023-02-21 22:40 UTC, rartino commented on optimade.rst
> +    * :val:`other`: the origin of the structural information is not correctly described by any of the other categories.
If you remove my version of `hypothetical`, then I think we absolutely need this to distinguish "This database doesn't provide `structure_origin`" from "I *know* this structure is random noise".

But also, I added this at the end, because I specifically realized none of the other categories made sense for structures stabilized at, e.g., 100 GPa. I think I still want a separate category for such structures. We have quite some high pressure data from some of our ongoing projects, and I want to be able to distinguish it from "random noise" structures.

2023-02-21 22:42 UTC, rartino commented on optimade.rst
> +    If supported, filters MAY support only a subset of comparison operators.
```suggestion
  - **Query**: MUST be a queryable property with support for all mandatory filter features.
```

2023-02-22 10:36 UTC, JPBergsma commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
Would you as a client treat "unknown" different from `null` ?
If not, there is no real reason to differentiate the two.
I am also wondering how to handle `IS KNOWN` in filters. 
Should it return true or false when the value is set to "unknown" ?

2023-02-22 10:54 UTC, rartino commented on optimade.rst
> +    * :val:`processed`: the structural information originates from experimental data, but has undergone additional processing in such a way that the result is still recognizable as the experimental s
> I personally think derived is clear in this context, "experimentally derived" would be common parlance in the literature no?

But, when we abbreviate it just as "derived", is it still clear that it refers to "experimentally derived", as opposed to, e.g., "mathematically derived"?

"Processed" is, at least, making clear that the thing started from something that was *altered*. My problem with the word "derived" is that it doesn't have that meaning in all contexts, e.g., in "mathematically derived".

However, I can't help thinking there should be an even better word. Something that unambiguously refers to "from experiment" not just "modified".

2023-02-22 11:17 UTC, JPBergsma commented on optimade.rst
> +    * :val:`processed`: the structural information originates from experimental data, but has undergone additional processing in such a way that the result is still recognizable as the experimental s
To me, "derived" sounds less strict than "processed".
With "derived" I could also for see cases where one atom has been replaced with a different chemically similar atom. Which I would not expect this with "processed".

2023-02-22 11:29 UTC, vaitkus commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
The treatment of `null` SHOULD/MUST be the same as of `unknown`, at least according to line 2882 of this PR:

> If the property is omitted, set to an empty string, or `null` it means the same thing as :val:`unknown`.

@JPBergsma wrote:

> I am also wondering how to handle IS KNOWN in filters.
> Should it return true or false when the value is set to "unknown" ?

I think that the "unknown" enumeration value should be treated as any another explicitly specified value and return true. That is, it should be interpreted as "it is known that the value is unknown".

2023-02-22 11:30 UTC, ml-evs commented on optimade.rst
> +      This category is suitable for randomly placed atoms (e.g., meant to provide a starting point for further processing) or outcomes of AI models with predictive power deemed insufficient for the :
> Reading your suggestion, "hypothetical" was indeed the wrong name for the category I described. But your change here is more that you suggest adding an extra category. I suppose a category for non-stable structures that still have undergone DFT relaxations - or equivalent - can be useful.

This category would contain the majority of structures for most databases, I think?  

> IMO the definition shouldn't be phrased as there being a guarantee that they are not thermodynamically stable. Just that they are "relaxed" (and haven't been placed in another category).

That's fair.

> I also feel odd about saying that an AI model does "local optimization". Does it make sense to formulate it that these structures are predicted, by _ab inito_ or AI models, to be close to an energy surface minimum?

Yes, a bit hard to capture this in the words, by "inferred" by an AI model, I meant that the model has some surrogate representation of a PES from which it is trying to sample phases which would be local minima, but that it is a bit of a mouthful.

2023-02-22 11:31 UTC, ml-evs commented on optimade.rst
> +    * :val:`other`: the origin of the structural information is not correctly described by any of the other categories.
Yes, to be clear, `unknown` should still be an allowed value but I don't think it should be the default (although I would need to re-assess once we finalize the other categories).

2023-02-22 11:35 UTC, ml-evs commented on optimade.rst
> +      This category includes theoretically invented structures that have been relaxed using ab-initio calculations and found to be close to the convex hull of stability, or structures generated from
> On the other hand, we haven't really made the commitment to organize data that way; perhaps the `/structures` endpoint should be seen more as "give me all you can say that relates to this structure" than "this is the contents of my structure SQL table." There is nothing that prevents an implementation from keeping hull distances in a separate table/document (which is updated when needed) and join it with static structure data to form responses.

That's fair -- I actually don't know what the SOP for many databases would be in this case, i.e. if you add one new stable phase, does it get added with a negative hull distance or is the whole database updated? The former is probably the most useful from a user perspective who is working actively with the database day-to-day, but the latter would be better for consistency.

> And those who do not want to do that do not have to. This category is meant to say _"if you are looking for 'real structures', as the database provider of this data, I suggest you to also consider these structures, even though they are not based on experiments"_. But, the provider can of course decide not to make that kind of recommendation and put all non-experimental structures in `hypothetical`.

👍 

> The key word here was meant to be _demonstrated_ more so than _reasonable predictive_, i.e., at least there should have been some form of test, not just some form of experimental AI model aiming (but never tested) to generate stable structures.

👍 

> Also: about you inserting "reasonable external condition". This applies to all points, and thus was covered below the list. Is it necessary to also place it here?

This is the category that is affected most by it, I would say maybe a forward reference "under reasonable conditions (see below)" or something to that effect would help?

2023-02-22 12:24 UTC, vaitkus commented on optimade.rst
> +    * :val:`predicted`: the structural information is not directly related to the outcome of an experimental technique on an existing material, but has undergone theoretical processing to suggest it
```suggestion
    * :val:`predicted`: the structural information is not directly related to the outcome of an experiment on an existing material, but has undergone theoretical processing to suggest it as a candidate for a potentially synthesizable structure.
```

2023-02-22 12:59 UTC, JPBergsma commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
> >    I am also wondering how to handle IS KNOWN in filters.
    Should it return true or false when the value is set to "unknown" ?

> I think that the "unknown" enumeration value should be treated as any another explicitly specified value and return true. That is, it should be interpreted as "it is known that the value is unknown".
 
This could be confusing to the client, i.e if you do the query IS KNOWN you would still get results with an unknown value. It thus makes queries a bit more complicated, because you would need two clauses to remove all entries with an unknown value. 
Combined with "If the property is omitted, set to an empty string, or null it means the same thing as :val:unknown.", I do not see a good reason to keep "unkown" as a value for this field. So I would therefore argue to remove it.

2023-02-22 14:57 UTC, rartino commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
I agree with @JPBergsma's good point that the specific string "unknown" easily leads to confusion with the IS KNOWN operator. So, we should change the name, or skip it and replace it with 'unknown'.

>> The treatment of `null` SHOULD/MUST be the same as of `unknown`, at least according to line 2882 of this PR:
> If the property is omitted, set to an empty string, or null it means the same thing as :val:unknown.

Maybe that line can be made more clear - but what is meant is that both `null` and "unknown" means the same thing *in terms of the categorization of the origin.* However, "unknown" communicates, in addition to that, that the database explicitly has assigned this category.

I'm getting convinced that this distinction is not important, though. So - ok - I'll remove it.

2023-02-22 16:54 UTC, rartino commented
@vaitkus @ml-evs Thanks for reviewing this. I've now tried my best to accommodate all comments, except the rename "processed" -> "derived" which I think we need to discuss some more.

2023-03-03 13:49 UTC, rartino commented
It makes sense to present it on the web meet. I'd be happy to yield to the greater consensus between "processed", "derived", or any other word the swarm intelligence can come up with.

2023-03-03 17:29 UTC, merkys commented on optimade.rst
> +    Clients encountering unrecognized strings SHOULD treat them to mean the same as :val:`unknown`.
I find the reference to `unknown` slightly puzzling as there is no such category `unknown` in the above list. Maybe we can replace `unknown` with `null`, or say "Clients encountering unrecognized strings SHOULD treat them as if this property would be omitted"?

2023-03-17 18:31 UTC, rartino commented on optimade.rst
> +    Providers who want to communicate structural information about compounds that exist only at unusual or extreme conditions SHOULD use the :val:`other` category, and, if desired, use another facili
Suggested edit from web discussion:
```suggestion
    * :val:`predicted`: the structural information is not directly related to the outcome of an experiment on an existing material, but is proposed from theoretical methods to represent a potentially synthesizable structure at non-extreme conditions (i.e., existence around NTP or at lower temperatures) and in a regular atmosphere.
      For example, theoretically invented structures found to be close to the convex hull of thermodynamical stability at reasonable conditions by relaxation using *ab initio* calculations, AI models with a demonstrated reasonable predictive power, or similar techniques qualify for this category.
      Structures that are the outcome of theoretical methods that specifically target conditions far from normal conditions are not meant to qualify for this category.
      This category definition involves a degree of subjectivity that has to be determined by the database provider.
      The database provider MAY choose not to use theoretical methods to propose structures in the way described here, in which case this category is not used.

    * :val:`hypothetical`: the structural information is not directly related to the outcome of an experiment on an existing material, but is proposed from theoretical methods to represent a local energy minimum on the potential energy surface.
      This category accommodates potentially highly thermodynamically unstable structures, e.g., predicted to decompose into other competing phases, even with respect to the elemental solids.
      For example, structures relaxed using *ab initio* calculations but not identified to end up close to the convex hull of thermodynamical stability qualify for this category.
      AI models which, with a demonstrated reasonable predictive power, can generate structures in local potential energy minimums (e.g., by relaxation via predicted forces, direct generation, etc.) also qualify.
      This category definition also involves a degree of subjectivity that has to be determined by the database provider.

    * :val:`arbitrary`: the structural information has been created in a way that does not ensure any type of stability, i.e., not even representing a local energy minimum on the potential energy surface.
      For example, arbitrarily placed atoms that have not been locally optimized, non-equilibrium snapshots, and outcomes of AI models for which the predictive power is deemed insufficient for the earlier categories, all qualify for this category.

    * :val:`other`: the origin of the structural information is known, but is not correctly described by any of the above categories.

    Providers who want to communicate structural information about compounds that exist only at unusual or extreme conditions SHOULD use the :val:`other` category, and, if desired, use another facility (e.g., a provider-specific property) to communicate more specific information.
```

2023-03-17 18:32 UTC, rartino commented on optimade.rst
> +    Clients encountering unrecognized strings SHOULD treat them to mean the same as :val:`unknown`.
```suggestion
    Clients encountering unrecognized strings SHOULD treat them to mean the same as the field having the value :val:`null`.
```

2023-03-17 18:36 UTC, rartino commented
@sauliusg @ml-evs @vaitkus @JPBergsma For the changes we discussed at the web meet, I think the "non-extreme conditions" actually only apply to the category `predicted`, so I moved it there. I think this works; please review.

2023-03-18 13:08 UTC, ml-evs commented on optimade.rst
> +  - For a structure entry directly encoding structural information obtained from a neutron diffraction experiment: :val:`"experimental"`.
It seems a bit strange to have a single example here. Perhaps we can just duplicate some of the inlined examples for each category here too?


e.g.,

```suggestion
  - For a structure entry directly encoding structural information obtained from a neutron diffraction experiment: :val:`"experimental"`.
  - A structure entry of a theoretical relaxation of an :val:`"experimental"` entry should be marked as :val:`"derived"`.
```

(happy to add more)

2023-03-20 07:12 UTC, merkys commented on optimade.rst
> +    * :val:`predicted`: the structural information is not directly related to the outcome of an experiment on an existing material, but is proposed from theoretical methods to represent a potentially
Could we remove the reference to *extreme conditions* in favor of defining properties describing the conditions? My rationale is that *extreme* might be a difficult term to agree upon, but having queryable properties for temperature, pressure etc. would both solve this issue and bring even more usable data about entries in databases.

2023-03-20 07:38 UTC, rartino commented on optimade.rst
> +  - For a structure entry directly encoding structural information obtained from a neutron diffraction experiment: :val:`"experimental"`.
Each point already contain somewhat more general examples of what should and should not use the classifications. I suppose 2-3 "global" examples are ok, but should in that case be very specific to not overlap with the list. Hence, I added some detail to your suggestion for it to not be redundant with the definition text of the "derived" category.

2023-03-20 07:41 UTC, rartino commented on optimade.rst
> +    * :val:`predicted`: the structural information is not directly related to the outcome of an experiment on an existing material, but is proposed from theoretical methods to represent a potentially
Looking at this now, I think I messed up trying to quickly edit in what we had agreed on during the web meet before I forgot. This was indeed not supposed to remain, but be replaced by the edit @ml-evs comments on below.
```suggestion
    * :val:`predicted`: the structural information is not directly related to the outcome of an experiment on an existing material, but is proposed from theoretical methods to represent a potentially synthesizable structure.
```

2023-03-20 07:47 UTC, rartino commented on optimade.rst
> +      The database provider MAY choose not to use theoretical methods to propose structures in the way described here, in which case this category is not used.
The intended meaning is that this category likely requires the database to do some form of bookkeeping of the convex hull or equivalent and make a subjective decision about what "close to the convex hull" means. It is fully ok for a database not to do that, in which case the category is empty and everything gets lumped into the next category "hypothetical". I'd be happy for any suggestion of a formulation that is clear to you (or suggest we remove it altogether). In the meantime I'll check what chatGPT proposes.

2023-03-20 12:36 UTC, rartino commented on optimade.rst
> +      Structures that are the outcome of theoretical methods that specifically target conditions far from normal conditions are not meant to qualify for this category.
```suggestion
      Structures that are the outcome of theoretical methods that specifically target conditions far outside normal conditions are not meant to qualify for this category.
```

2023-03-20 12:37 UTC, rartino commented on optimade.rst
> +      If this functionality is not provided, any structures that possibly could fit this category are meant to be assigned the next qualifying category below instead.
```suggestion
      If this functionality is not provided, any structures that could fit this category are meant to be assigned the next qualifying category below instead.
```

2023-03-20 12:40 UTC, rartino commented on optimade.rst
> +- **Description**: A string that describes aspects of the origin of the structural data to indicate if it is based directly or indirectly on experimental evidence, or inferred from other sources, giv
```suggestion
- **Description**: A string that describes aspects of the origin of the structural data to indicate if it is based directly or indirectly on experimental evidence, or inferred from other sources, giving some information on whether the structure was obtained with the intent of representing structures that can exist in nature or be synthesized as a stable compound.
```

2023-03-20 12:47 UTC, rartino commented on optimade.rst
> +
```suggestion
```

2023-03-20 14:25 UTC, ml-evs commented on optimade.rst
>        For example, theoretically invented structures found to be close to the convex hull of thermodynamical stability at reasonable conditions by relaxation using *ab initio* calculations, AI models
This sentence is implicitly referencing the global convex hull of all materials, which of course shifts as we predict more, but hopefully in ways such that a previously stable structure will still be close (enough) to the new convex hull if a novel competing phase is discovered to not change its category here.

Do we need to guard against the case of a database serving e.g., a wholly incomplete ternary phase diagram consisting of just the chemical potentials and one ternary phase with negative formation energy, if in fact several binary phases are "known" and would otherwise destabilise it? i.e., should we add some comment about best efforts to ensure phase diagram completeness before marking something as `predicted`? I don't like my suggestion below, but something along those lines?

```suggestion
      For example, theoretically invented structures found to be close to the convex hull of thermodynamical stability at reasonable conditions by relaxation using *ab initio* calculations, AI models with a demonstrated reasonable predictive power, or similar techniques qualify for this category.
      The global convex hull is a shifting baseline, but when using this field, database providers should make their best efforts to ensure completeness of at least the lower dimensional subspaces of a phase diagram before marking an n-dimensional phase as `predicted`, e.g., a ternary structure must compete favourably against the relevant binary phases, and a quaternary must compete with known ternary phases.
```

2023-03-20 16:19 UTC, rartino commented on optimade.rst
> +    Clients encountering unrecognized strings SHOULD treat them to mean the same as the field having the value :val:`null`.
```suggestion
    Clients encountering unrecognized strings SHOULD treat them to mean the same as the field having the value :val:`"other"`.
```

2023-03-20 17:05 UTC, JPBergsma commented on optimade.rst
>        For example, theoretically invented structures found to be close to the convex hull of thermodynamical stability at reasonable conditions by relaxation using *ab initio* calculations, AI models
I do not think we should define what the boundaries for synthesizability are. It is up to the person who generates the compound to determine whether it is syntheziable or not. 
How far from the hull would you consider the limit for synthesizability ? Silver nitride($Ag_3N$) is far from the hull, and yet you can still synthesize it.

2023-03-21 11:01 UTC, JPBergsma commented on optimade.rst
> +      It is OPTIONAL for database providers to predict theoretical structures as potentially synthesizable or not.
```suggestion
      It is OPTIONAL for database providers to predict theoretical structures as potentially synthesizable or not.
```
This space causes the precommit check to fail.

2023-03-22 07:27 UTC, rartino commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
@ml-evs @JPBergsma @vaitkus As I'm looking over this PR in hope of finalizing this, I find that the decision we landed on here does not sit well with me.

The issue is that we have defined `null` for property values to mean something very specific, which is regulated in the section "Properties with an unknown value", i.e., "no data value is present".

But, here, we are asking databases to essentially assign *as a data value* `null` to this field to communicate that, as @vaitkus expressed it: "it is known that the value is unknown".

This also sets a bad example for future fields. In general, we do not want :val:`null` to carry a data meaning - it should carry the meaning "there is no data" and we should instruct clients how to be interpret that in terms of provided data values.

So, after thinking this through, I feel more strongly now that we should come up with another string that means "it is known that the value is unknown", define it, and say that clients that missing data is "closest" to that data value (but also expresses that the data value is missing as per the section "Properties with an unknown value", but I think that can be understood implicitly).

2023-03-22 07:49 UTC, rartino commented on optimade.rst
> +
```suggestion

* :val:`arbitrary`:indeterminate`: the database provider has determined that it is unable to classify the origin of the structural data according to the provided categories, e.g., because the source of the data provides no such information.
      There is a subtle, but relevant, distinction between this value and and not assigning the property any value (i.e, the field is missing or have value :val:`null` which makes the property unknown in the sense of "Properties with an unknown value"_).
      A database that assigns the data value "indeterminate" to a structure communicates an intentional classification of the structures into this category, i.e., it states that it is known that the origin is not known, in contrast to not providing a data value classifying the origin of the structure.

```

2023-03-22 07:58 UTC, rartino commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
I added a new classification "indeterminate" for this.

2023-03-22 07:59 UTC, rartino commented on optimade.rst
> +      There is a subtle, but relevant, distinction between this value and and not assigning the property any value (i.e, the field is missing or have value :val:`null`, making the property unknown in
```suggestion
      There is a subtle, but relevant, distinction between this value and and not assigning the property any value (i.e, the field is missing or has value :val:`null`, making the property unknown in the sense discussed in the section `Properties with an unknown value`_).
```

2023-03-22 08:00 UTC, rartino commented on optimade.rst
> +      The value "indeterminate" communicates that the database provider has intentionally classified the structures into this category, i.e., it states that it is known that the origin is not known,
```suggestion
      The value "indeterminate" communicates that the database provider has intentionally classified the structure into this category, i.e., it states that it is known that its origin is not known, in contrast to the database not providing any data value for classifying the structure.
```

2023-03-22 08:02 UTC, rartino commented on optimade.rst
> +* :val:`indeterminate`: the database provider has determined that it is unable to classify the origin of the structural data in these categories, e.g., because the source of the data provides no such
```suggestion
* :val:`indeterminate`: the database provider has determined that it is unable to classify the origin of the structural data into these categories, e.g., because the source of the data provides no such information.
```

2023-03-22 09:55 UTC, ml-evs approved these changes
One formatting tweak but I am happy with this now.

2023-03-22 09:55 UTC, ml-evs commented on optimade.rst
> +      The value "indeterminate" communicates that the database provider has intentionally classified the structure into this category, i.e., it states that it is known that its origin is not known, i
```suggestion
    * :val:`indeterminate`: the database provider has determined that it is unable to classify the origin of the structural data into these categories, e.g., because the source of the data provides no such information.
      There is a subtle, but relevant, distinction between this value and and not assigning the property any value (i.e, the field is missing or has value :val:`null`, making the property unknown in the sense discussed in the section `Properties with an unknown value`_).
      The value "indeterminate" communicates that the database provider has intentionally classified the structure into this category, i.e., it states that it is known that its origin is not known, in contrast to the database not providing any data value for classifying the structure.
```

2023-03-22 12:29 UTC, vaitkus commented on optimade.rst
> +    This value is used if the origin of the structural data is not known, or, if it is partially known but to an insufficient degree to distinguish between the categories defined below.
Does this sentence still apply in full after the introduction of the `indeterminate` value? Shouldn't the "partially known" part fall under the new enumeration value?

2023-03-22 15:52 UTC, rartino commented on optimade.rst
> +    This value is used if the origin of the structural data is not known, or, if it is partially known but to an insufficient degree to distinguish between the categories defined below.
Ah, my mistake. I actually looked for this sentence below the categories (where it originally was), did not find it, and thought that we had taken it out in an earlier stage. But, thanks, indeed, this should be fixed. I think all is well if we just remove it. 
```suggestion
```

2023-03-22 16:02 UTC, JPBergsma requested changes
I am not sure this PR is going in the right direction. 
I think this is because we are still mixing two different things in this property.

1. How was the structure was obtained. i.e. from an experiment or computation.

2. How likely it is that this structure/material can exist/is real.

So I have made a few comments to make this proposal more like 2. Although these are still far from perfect.

I think that if I take an experimentally determined structure as input and the positions of the atoms remain the same (within the margins of uncertainty) in a calculation, the structure of that calculation should have the same value as the experimental structure.

2023-03-22 16:23 UTC, rartino commented on optimade.rst
> +    This value is used if the origin of the structural data is not known, or, if it is partially known but to an insufficient degree to distinguish between the categories defined below.
Right, @vaitkus also noticed it, and it was a mistake it got left in the text. It is already fixed now.

2023-03-22 16:51 UTC, rartino commented on optimade.rst
> +- **Description**: A string that describes aspects of the origin of the structural data to indicate if it is based directly or indirectly on experimental evidence, or inferred from other sources, giv
I strongly disagree with `certainty_of_existence` as a name. "Existence" isn't a very transparent term and can mean different things. The large removal IMO takes away many important subtleties I had hoped we were converging on.

2023-03-22 18:34 UTC, rartino commented
@JPBergsma With the major edits/removals, field name, and category changes, this seems less an edit suggestion and more of a counter-proposal to what we seemed to converge on. If you feel strongly about the classification being restructured this way, please make a counter-PR and we can discuss the pro:s and con:s at the next web meet.

2023-03-22 21:26 UTC, rartino commented on optimade.rst
> +    * :val:`other`: the origin of the structural information is known, but is not correctly described by any of the above categories.
We took out the example of structures stable at extreme conditions and unusual conditions because it was difficult to interpret in the context of experimental structures. However, for theoretical structures, I still think the category "other" can apply in some such cases. It would make sense for a series of theoretical structures with predicted structural stability at 100 TPa or in an environment of very unusual chemical potentials.  

How about an interface structure created from two faithful representations of experimental structures?

Perhaps a nanoparticle structure which is stable in water due to the water molecules stabilizing it, but highly unstable otherwise; represented as an OPTIAMDE structure without the water molecules?

From a more philosophical standpoint, even if we can agree on how to classify these examples, it is still not obvious that the categories span the full space of possibilities. To not include an 'other' category forces those with data that they do not know how to classify to do the best they can with the options given, which works against standardization. 

(This discussion reminds me of a segment in Holzmann "Design and Validation of Computer Protocols" where he frames the [Clayton Tunnel rail crash](https://en.wikipedia.org/wiki/Clayton_Tunnel_rail_crash) as a failure of protocol design as the protocol used by the signalmen was unable to represent an unusual state of the tunnel and trains they ended up in, leading to a fatal train crash killing 23 people. The story communicates a point about making assumptions in protocol design; I recommend the read if you can find it.)

2023-06-05 13:30 UTC, merkys commented
Revisiting the proposal, I can say that I like the categories, but feel that the borders between them might be too blurry. Nevertheless specifying them in high detail might require arbitrary decisions. It would be nice to hear more opinions from people with non-experimental background.

2023-06-09 09:10 UTC, rartino commented
Workshop: this probably needs to go in a separated namespace, since it is difficult to agree on the precise way to do the categorization. We may want to think about designing it in a way so one can indicate that it is known that they are "theoretical" without any resolution but not make a statement about them being experimental.

2023-06-18 08:56 UTC, sauliusg commented on optimade.rst
> +    * :val:`experimental`: the structural information is a faithful representation of the outcome of an experimental technique for structure determination.
I find the current classification scheme to be too vague and too poorly undefined to be satisfactory as a standard for a database implementation, especially for the automated application. In particular, what is "observed experimentally" is very much dependent on the field of research (e.g., in what sense was the Ds element, with the half life below a millisecond and abundances of several atoms actually observed?), and "consensus" and "structure exists" are in the eye of the beholder.

An alternative suggestion comes from our discussion with Rickard (@rartino) during the lunch-time discussion of the 2023 CECAM workshop. We notice that *most* of the structures we are interested in comes from some sort of a minimization procedure, when the atomic coordinates are refined against a chosen target function. This target function essentially defined the physical meaning of the refined structure (and thus the conclusions we an draw from it); closeness to the optimum can be evaluated and serves as a quality criterion. The target function can be specified regardless to the minimization procedures (algorithms, programs) that were employed. The target function is unique for a given structure and specific to a given methods, thus it can be used for broad classification of the structures.

The current examples of the classes could be:

- structures defined by diffraction methods (aka "experimental"): minimise discrepancy between the observed and predicted scattered amplitudes, `min sum_h,k,l ||F_obs| - |F_calc||`; see https://dictionary.iucr.org/R_factor. Subclasses can be introduced depending on the radiation type (X-rays, neutrons, electrons);
- DFT calculated structures: minimize the computed ground state energy as a function of electron density (right?), `min E(rho(x,y,z))`; subclasses can be introduced depending on the exact form of the hamiltonian, and on the aproximations that were in place;
- classical minimized structures: minimize empirical energy, `min E(bonds, angles, dihedrals)`;
- machine learning structures: minimise discrepancy between the actual and predicted coordinates in the training process, minimise some other target function of the ML, or maximise the likelihood function;

Finally, there might be structures that were not optimised in any way, and these can be designated as "fantsy structures"

Note that the classes introduced in this way will be unambiguous, non-overlapping, and structures withing a single class will be easier comparable between themselves as the structures from different classes.

Should we go this direction as a more tractable one?

2023-06-18 15:02 UTC, ml-evs commented on optimade.rst
> +    * :val:`experimental`: the structural information is a faithful representation of the outcome of an experimental technique for structure determination.
I must say that I'm not sure this differs much from our current proposal, though we could certainly adopt some of your wording. Is it the PR you disagree with in its current state or just the suggestion in the comment you are replying to?

The important distinction missing from you suggestion is the mechanism for a database to indicate that they believe a structure to be globally stable when compared to other structures in the same database; whilst we can handle this with the eventual "stability" namespace, I think it would be a shame to exclude e.g., generative structures with high predicted stability probability, or phases that cannot easily be exhaustively screened for stability from our definition (the "stability" namespace would strictly boil this down to a distance from a well-defined locally completed convex hull).

2023-06-18 15:11 UTC, sauliusg commented on optimade.rst
> +    * :val:`experimental`: the structural information is a faithful representation of the outcome of an experimental technique for structure determination.
> I must say that I'm not sure this differs much from our current proposal, though we could certainly adopt some of your wording. Is it the PR you disagree with in its current state or just the suggestion in the comment you are replying to?

To me the difference is fundamental.

The suggested definitions, unlike the current PR wording, are unambiguous (IMHO) and mathematically well defined. We just need to double check what exactly minima are meant by different methods. I am pretty sure for experimental crystallography, not so sure about other methods.

2023-06-18 15:12 UTC, sauliusg commented on optimade.rst
> +    * :val:`experimental`: the structural information is a faithful representation of the outcome of an experimental technique for structure determination.
> The important distinction missing from you suggestion is the mechanism for a database to indicate that they believe a structure to be globally stable when compared to other structures in the same database; whilst we can handle this with the eventual "stability" namespace, I think it would be a shame to exclude e.g., generative structures with high predicted stability probability, or phases that cannot easily be exhaustively screened for stability from our definition (the "stability" namespace would strictly boil this down to a distance from a well-defined locally completed convex hull).

I wold strongly suggest that `stability` is conveyed by another, numeric property. As you suggest, it should give energy above the convex hull, and would give a possibility to search for quantitative results.

2024-01-10 15:21 UTC, rartino commented on optimade.rst
> +
```suggestion
optimization\_type
~~~~~~~~~~~~~~~~~~

- **Description**: A string that classifies the type of optimization that has resulted in the structural data.

- **Type**: string
- **Requirements/Conventions**:
  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
  - **Query**: Support for queries on this property is OPTIONAL.

  - If the property is :val:`null` or omitted, no information is provided about the type of optimization used to obtain the structural data.

  - If present and not :val:`null`, the property SHOULD take one of the following values:

    * :val:`experimental`: the structure is the result of an optimization or refinement process part of an experimental technique, e.g., minimization of the discrepancy between observed and predicted scattered amplitudes from diffraction data.

    * :val:`hybrid`: the structure is the result of the combination of an experiment and further optimization based on a reasonable theoretical energy model in such a way that it remains a fair representation of the original experimental structure.
      For example, experimental structures relaxed using *ab initio* calculations are in this category.
      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements are not included in this category.

    * :val:`global`: the structure has been optimized using a theoretical technique based on a reasonable energy model in a way that takes into account the global energy surface.
      The structure has been optimized into the global energy minimum or into a local minimum within an energy range of the global minimum commonly considered for potential metastability (typically on the scale of 100 meV/atom).
      A common technique for this type of optimization is to construct the convex hull of thermodynamical stability from the known minima and dismiss structures outside the relevant energy range. 
  
    * :val:`local`: the structure has been optimized using a theoretical technique based on a reasonable energy model into a local minimum of the energy surface.
      For example, structures relaxed using *ab initio* calculations without consideration of the convex hull of thermodynamical stability qualify for this category.

    * :val:`none`: the structural has not undergone an optimization process and is thus, in some sense, arbitrary.
      Structures of this kind can come from, e.g., randomly generated coordinates or non-equilibrium snapshots.
    
    * :val:`indeterminate`: the database declares that the type of optimization used for this specific entry cannot be determined, e.g., because that information is missing.
      This value represents a stronger statement - it is known that optimization is unknown - than an omitted classification (i.e, the field is missing or has value :val:`null`) that marks the property unknown only in the sense discussed in the section `Properties with an unknown value`_.)

    * :val:`other`: the structure is the result of some optimization process, but none of the other categories correctly represents the type of optimization used.

    Other strings prefixed by a database-specific prefix, e.g., `_exmpl_optimized_on_fixed_grid`. SHOULD NOT be used.
    Other non-standard strings MUST NOT be used.
    Clients encountering unrecognized strings SHOULD treat them to mean the same as the field having the value :val:`"other"`.
    
    Structures produced by AI models and other techniques that have been reasonably tested to reliably generate results equivalent with structural optimization using energy models SHOULD be classified the same as if that type of energy model had been used. 

- **Examples**:

  - For a structure entry directly encoding structural information obtained from a neutron diffraction experiment: :val:`"experimental"`.
  
  - For a structure entry that encodes the structural information from a theoretical relaxation of an :val:`"experimental"` entry using computational software that implements density functional theory: :val:`"hybrid"`.

```

2024-01-10 15:35 UTC, rartino reviewed
(Some adjustments made via the reviewer function)

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
```suggestion
- **Requirements/Conventions**:

  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
```

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +    * :val:`experimental`: the structure is the result of an optimization or refinement process part of an experimental technique, e.g., minimization of the discrepancy between observed and predicted
```suggestion
    * :val:`experimental`: the structure results from an optimization or refinement process part of an experimental technique, e.g., minimization of the discrepancy between observed and predicted scattered amplitudes from diffraction data.
```

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +    * :val:`hybrid`: the structure is the result of the combination of an experiment and further optimization based on a reasonable theoretical energy model in such a way that it remains a fair repre
```suggestion
    * :val:`hybrid`: the structure is the result of the combination of an experiment and further optimization based on a reasonable theoretical energy model so that it remains a fair representation of the original experimental structure.
```

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements are not included in this category.
```suggestion
      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements, are not included in this category.
```

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +    * :val:`none`: the structural has not undergone an optimization process and is thus, in some sense, arbitrary.
```suggestion
    * :val:`none`: the structure has not undergone an optimization process and is thus, in some sense, arbitrary.
```

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +      This value represents a stronger statement - it is known that optimization is unknown - than an omitted classification (i.e, the field is missing or has value :val:`null`) that marks the proper
```suggestion
      This value represents a stronger statement (that the database knows that the type of optimization is not known) than an omitted classification (i.e., the field is missing or has the value :val:`null`) which communicates that the property is unknown only in the sense discussed in the section `Properties with an unknown value`_.)
```

2024-01-10 15:35 UTC, rartino commented on optimade.rst
> +    Structures produced by AI models and other techniques that have been reasonably tested to reliably generate results equivalent with structural optimization using energy models SHOULD be classifie
```suggestion
    Structures produced by AI models and other techniques that have been reasonably tested to reliably generate results equivalent to structural optimization using energy models SHOULD be classified the same as if that type of energy model had been used. 
```

2024-01-10 15:37 UTC, rartino commented on optimade.rst
> +    Structures produced by AI models and other techniques that have been reasonably tested to reliably generate results equivalent to structural optimization using energy models SHOULD be classified
```suggestion
    Structures produced by AI models and other techniques that have been reasonably tested to reliably generate results equivalent to structural optimization using energy models SHOULD be classified the same as if that type of energy model had been used.
```

2024-01-10 15:38 UTC, rartino commented on optimade.rst
> +      A common technique for this type of optimization is to construct the convex hull of thermodynamical stability from the known minima and dismiss structures outside the relevant energy range.
```suggestion
      A common technique for this type of optimization is to construct the convex hull of thermodynamical stability from the known minima and dismiss structures outside the relevant energy range.
```

2024-01-10 15:45 UTC, rartino commented on optimade.rst
> +
```suggestion
optimization\_type
~~~~~~~~~~~~~~~~~~

- **Description**: A string that classifies the type of optimization that has resulted in the structural data.

- **Type**: string
- **Requirements/Conventions**:

  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
  - **Query**: Support for queries on this property is OPTIONAL.

  - If the property is :val:`null` or omitted, no information is provided about the type of optimization used to obtain the structural data.

  - If present and not :val:`null`, the property SHOULD take one of the following values:

    * :val:`experimental`: the structure results from an optimization or refinement process part of an experimental technique, e.g., minimization of the discrepancy between observed and predicted scattered amplitudes from diffraction data.

    * :val:`hybrid`: the structure is the result of the combination of an experiment and further optimization based on a reasonable theoretical energy model so that it remains a fair representation of the original experimental structure.
      For example, experimental structures relaxed using *ab initio* calculations are in this category.
      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements, are not included in this category.

    * :val:`global`: the structure has been optimized using a theoretical technique based on a reasonable energy model in a way that takes into account the global energy surface.
      The structure has been optimized into the global energy minimum or into a local minimum within an energy range of the global minimum commonly considered for potential metastability (typically on the scale of 100 meV/atom).
      A common technique for this type of optimization is to construct the convex hull of thermodynamical stability from the known minima and dismiss structures outside the relevant energy range.

    * :val:`local`: the structure has been optimized using a theoretical technique based on a reasonable energy model into a local minimum of the energy surface.
      For example, structures relaxed using *ab initio* calculations without consideration of the convex hull of thermodynamical stability qualify for this category.

    * :val:`none`: the structure has not undergone an optimization process and is thus, in some sense, arbitrary.
      Structures of this kind can come from, e.g., randomly generated coordinates or non-equilibrium snapshots.

    * :val:`indeterminate`: the database declares that the type of optimization used for this specific entry cannot be determined, e.g., because that information is missing.
      This value represents a stronger statement (that the database knows that the type of optimization is not known) than an omitted classification (i.e., the field is missing or has the value :val:`null`) which communicates that the property is unknown only in the sense discussed in the section `Properties with an unknown value`_.)

    * :val:`other`: the structure is the result of some optimization process, but none of the other categories correctly represents the type of optimization used.

    Other strings prefixed by a database-specific prefix, e.g., `_exmpl_optimized_on_fixed_grid`. SHOULD NOT be used.
    Other non-standard strings MUST NOT be used.
    Clients encountering unrecognized strings SHOULD treat them to mean the same as the field having the value :val:`"other"`.

    Structures produced by AI models and other techniques that have been reasonably tested to reliably generate results equivalent to structural optimization using energy models SHOULD be classified the same as if that type of energy model had been used.

- **Examples**:

  - For a structure entry directly encoding structural information obtained from a neutron diffraction experiment: :val:`"experimental"`.

  - For a structure entry that encodes the structural information from a theoretical relaxation of an :val:`"experimental"` entry using computational software that implements density functional theory: :val:`"hybrid"`.

```

2024-01-10 15:53 UTC, rartino commented
Ok, lets make another attempt at this. 

I've now **completely reworked all text** of this PR to adhere to the alternative framing of classification suggested by @sauliusg here: https://github.com/Materials-Consortia/OPTIMADE/pull/455#discussion_r1233232471

I've demoted the PR to a draft, because it makes sense to first iterate this attempt with @sauliusg to make sure it fulfills the goals described in his comment before it is moved to others' review.

2024-01-10 15:57 UTC, rartino commented on optimade.rst
> +      For example, structures relaxed using *ab initio* calculations without consideration of the convex hull of thermodynamical stability qualify for this category.
```suggestion
      For example, structures relaxed using *ab initio* calculations without consideration of the energy of other minima in configuration space qualify for this category.
```

2024-01-10 15:59 UTC, rartino commented on optimade.rst
> +    Other strings prefixed by a database-specific prefix, e.g., `_exmpl_optimized_on_fixed_grid`. SHOULD NOT be used.
```suggestion
    Other strings prefixed by a database-specific prefix, e.g., `_exmpl_optimized_on_fixed_grid` SHOULD NOT be used.
```

2024-01-10 16:06 UTC, vaitkus commented on optimade.rst
> +    Other strings prefixed by a database-specific prefix, e.g., `_exmpl_optimized_on_fixed_grid` SHOULD NOT be used.
```suggestion
    Other strings prefixed by a database-specific prefix, e.g., `_exmpl_optimized_on_fixed_grid`, SHOULD NOT be used.
```

2024-01-10 16:06 UTC, vaitkus commented on optimade.rst
> +      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements, are not included in this category.
Just out of curiosity, to which category would such structures belong to?

2024-01-10 16:49 UTC, rartino commented on optimade.rst
> +      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements, are not included in this category.
This is meant to say that substitution breaks the "fair representation of the original experimental structure". So, at that point they are just theoretical constructs and it depends on if/how these constructs are optimized using theoretical techniques. 

- Atoms substituted and then coordinates, parameters left unoptimized -> 'none'. 
- Atoms substituted and then relaxed into local minimum -> 'local'
- Atoms substituted, relaxed into local minimum, culled based on convex hull distance -> 'global'.

(etc.)

2024-01-18 10:01 UTC, rartino commented on optimade.rst
> +      Structures where the experimental coordinates are kept, but one or more elements are substituted for other elements, are not included in this category.
(For bookkeeping I close this as resolved)

2024-10-18 13:34 UTC, sauliusg approved these changes
We could add an example of a specific minimised function(s) (e.g. \sum_{hkl} (F^{obj}_{hkl} - F^calc}_{hkl})^2 -> min for experimental single crystal structures); but this is probably too specific, so for now I would leave the current wording with the example of @rartino.

2024-11-16 11:52 UTC, ml-evs approved these changes
Meant to do this before the meeting yesterday, but I am happy with this classification and think the text is clear.

Ideally we should merge this and try to get some databases to apply the categorization before the next release.

2024-11-16 11:58 UTC, ml-evs commented on optimade.rst
> +      For example, structures relaxed using *ab initio* calculations without consideration of the energy of other minima in configuration space qualify for this category.
```suggestion
      For example, structures relaxed using *ab initio* calculations without consideration of the energy of other minima in configuration space qualify for this category. Such structures may indeed be near the global minimum but should not be marked as such unless the competing minima are present in the database.
```

Just read the final comment from @rartino, is this the kind of thing we had in mind? Similarly global could be tweaked a bit to indicate that the rest of the PES should be reported for something to be `global`, or is this too harsh a constraint?

2025-01-31 16:37 UTC, ml-evs commented on optimade.rst
> +      For example, structures relaxed using *ab initio* calculations without consideration of the energy of other minima in configuration space qualify for this category.
Will potentially add in a future PR!

2025-02-03 12:13 UTC, merged