Further updates to property definitions
Materials-Consortia/OPTIMADE pull request #460
Opened 2023-02-27 13:50 UTC by rartino

In the work on #445 a few more things have come up in need of adjustments in the specification.

It adopts `$comment` from JSON Schema to address #459. Even if I, in the work on definitions, ended up not needing it, I foresee possible future uses and it is a trivial extension.

This PR bundles a potentially controversial change of something that has irked me more and more when working on the definitions. The `type` field we inherit from JSON Schema is AFAIK the *only* place in the OPTIMADE standard where a dictionary field may have multiple data types, either String or List. Hence, I'm going to propose that we force Property Definitions to always use the list format. *Most* of our properties anyway allow "null" and are thus not affected. For the few that don't, it may seem silly to force ["string"] over "string"; but having starting to work on converting these definitions  between formats in #445, I really think the simplification of the representation format is worth it.

Further changes in this PR is:

- The addition of `x-optimade-requirements/response-default-level` to specify to what degree a property should or should not be included in a response per default. We have this information embedded in some of our current property definitions on this format: "Response: REQUIRED in the response."

- A corresponding addition in `x-optimade-implementation/response-default` for implementations to indicate what a specific implementation does for each field. (I had to name it differently, since the latter should be a boolean and the former a string.)

When I was adding these, I realized we need to clarify what is, and what is not, "the same" in terms of Property Definitions, so this is also done. Feel free to complain (and/or suggest fixes) if these formulations are not clear. They are, however, IMO absolutely important.

I should say I was initially a bit hesitant if the "default response" info really belong in the Property Definitions. However, after some thinking, I really do believe they do. When groupings of people uses this format to "develop standards" e.g. for biomol, experimental, magnetism, etc., databases they will want to be able to say what a database is expected to return by "default", just as we wanted for the basic properties we have standardized so far.

2023-02-27 13:58 UTC, rartino commented
For some reason I cannot request a review from @fekad via the Reviewers system, so I ping him here instead. Since you gave much good feedback on the initial property definitions, and I suspect you may have thoughts on the `type` field change, I'd be happy if you have time to take a look at this.

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  This field, along with a few others, should be seen as annotations rather then integral parts of the Property Definition.
```suggestion
  This field, along with a few others, should be seen as annotations rather than integral parts of the Property Definition.
```

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  This field, along with a few others, should be seen as annotations rather then integral parts of the Property Definition.
Also, I would probably rephrase the sentence to omit the `along with a few others` part and only focus on this definition. Since we do not explicitly list or reference those other definitions, it is probably of little use to the reader. The same comment applies to a few other newly added sentences with a similar structure.

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  - :field:`response-default`: boolean
```suggestion
  - :field:`response-default`: Boolean
```

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +    The value :val:`TRUE` means the implementation includes the property in responses by default, i.e., when not specifically requested.
It seems that other Boolean definitions also explicitly define the semantics of the "FALSE" value.

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
Could/should it default to FALSE instead under these conditions? Or does it clash with backwards compatibility?

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +    Expresses if an implementation of this property is required or not to include or exclude it in responses when not specifically requested.
```suggestion
    Expresses if an implementation of this property is required to include or exclude it in responses when not specifically requested.
```

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  It MUST be a one or two element list where the first element is a string correlated with :field:`x-optimade-type` as follows; if :field:`x-optimade-type` is:
```suggestion
  It MUST be a list of one or two elements where the first element is a string correlated with :field:`x-optimade-type` as follows; if :field:`x-optimade-type` is:
```

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  These comments should be omitted in formatted descriptions of the property shown to end users.
```suggestion
  These comments should be omitted in formatted descriptions of the property shown to the end users.
```

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  (Comments relevant in descriptions for end users should go into :field:`description`.)
```suggestion
  (Comments in descriptions relevant to the end users should go into :field:`description`.)
```

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  and the following additional OPTIONAL fields are allowed:
A bit of unconventional syntax here since we follow `appear.` with a lowercase `and`. Not sure how to rephrase it, though.

2023-02-27 14:42 UTC, vaitkus commented on optimade.rst
> +  Two Property Definitions that only differ by the value of :field:`x-optimade-implementation` are considered the same, and as explained in relation to the :field:`$id` field below, they SHOULD share
Is there a way to reference/link a specific part of the text that defines the "`as explained in relation to the :field:$id field below`"? I tried searching for the "below" part, but could not easily locate it with a cursory glance.

2023-02-27 15:00 UTC, ml-evs reviewed
To limit slosh/churn I will wait until Antanas' review has been addressed before taking a look, please re-request my review after that

2023-02-27 16:19 UTC, rartino commented on optimade.rst
> +    The value :val:`TRUE` means the implementation includes the property in responses by default, i.e., when not specifically requested.
```suggestion
    The value :val:`TRUE` means the implementation includes the property in responses by default, i.e., when not specifically requested.
    The value :val:`FALSE` means that the property is only included when requested.
```

2023-02-27 16:21 UTC, rartino commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
My thinking was that it could not mean either TRUE or FALSE, because that would mean that leaving this *optional* field out would make you standards-violating if you do the opposite. Meaning, it wouldn't really be optional to declare this, you'd have to do it in cases where the default is wrong.

2023-02-27 16:23 UTC, rartino commented on optimade.rst
> +  and the following additional OPTIONAL fields are allowed:
```suggestion
  The dictionary has the same format as :field:`x-optimade-implementation`, *except that* the :field:`response-default` SHOULD NOT appear, and the following additional OPTIONAL fields are allowed:
```

2023-02-27 16:27 UTC, rartino commented on optimade.rst
> +  This field, along with a few others, should be seen as annotations rather then integral parts of the Property Definition.
```suggestion
  This field should be seen as an annotation rather then an integral part of the Property Definition.
```

2023-02-27 16:41 UTC, vaitkus commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
I see. But the false-if-not-defined approach is already used with other *optional* boolean fields such as `sortable`. The default could also be wrong in those cases, albeit with slightly lesser side-effects.  Or is this case semantically different?

2023-02-27 16:57 UTC, rartino commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
I think it is different, in that it just means that this declaration should only be read as the provider not *promising* you can sort on the property. It isn't meant to be standards violating to still allow a sort in that case. Here, however, FALSE means it isn't included by default, so if you do, you break that contract.

I suppose we could reformulate the definition of this boolean instead, to say that FALSE means either. But it is actually useful to know if a field definitively is not going to be included in the response.

2023-02-27 17:28 UTC, vaitkus commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
Ok, so the real problem is that a reasonable default does not exist. However, the inclusion of the third "unknown" state quite limits the usability of the fields: even if one can say that certain properties will definitely be or not be there, the ones with unspecified `response-default` would still need to be manually excluded/include just to be safe one is getting the desired result.

Of course, this depends on the use case in mind. My initial impression was that this field should allow to formulate a complete expectation on what fields will be returned in the 
response by default. However, I understand that the intended purpose might be different. The use case that I described would probably require to declare the option as mandatory rather than option (something that we probably do not want to do?).

As for the FALSE value, I think that the current strict definition should be retained as it conveys more information.

2023-02-28 11:40 UTC, JPBergsma commented on optimade.rst
> +  This field should be seen as an annotation rather then an integral part of the Property Definition.
```suggestion
  This field should be seen as an annotation rather than an integral part of the Property Definition.
```

2023-02-28 12:17 UTC, rartino commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
> However, the inclusion of the third "unknown" state quite limits the usability of the field: even if one can say that certain properties will definitely be or not be there, the ones with unspecified response-default would still need to be manually excluded/include just to be safe one is getting the desired result.

I think the assumption here is that a reasonable provider provides this for all the usual fields that you care about, and it is missing only on fields you are likely not to care about. In that case, it is useful. 

The typical use case for "I don't want to say" is when testing things. Lets say you are in the process of adding new information to the database, you've made a "stub" property definition to cover it, but not yet decided it should go in the default responses or not. This seems a reasonable use case for "null".

2023-02-28 16:28 UTC, rartino commented on optimade.rst
> +  Two Property Definitions that only differ by the value of :field:`x-optimade-implementation` are considered the same, and as explained in relation to the :field:`$id` field below, they SHOULD share
Ok, I've added internal hyperlinks for this, and also to reference the definition of `x-optimade-type` from `type`.

2023-02-28 16:30 UTC, rartino commented
@ml-evs Ok, I think I've addressed everything from @vaitkus now, except the ongoing discussion we have about the default for `response-default`.

2023-02-28 17:36 UTC, vaitkus commented on optimade.rst
> +    Omitting the field or :val:`null` means the implementation does not declare if the property will be included in responses by default or not.
Understood. I would probably use a different approach of not serving "stub" definitions by default and then moving on to serving them once ready, but I do understand that different people use different practices. So unless you see any benefits of declaring this field as mandatory, I consider the discussion resolved.

2023-02-28 17:38 UTC, vaitkus approved these changes
Thank you for the changes.

2023-03-01 08:37 UTC, rartino commented
So, another thing came up as I was working on the property definitions yesterday. It turns out that, since I don't want to duplicate my unit definitions in the source files, I more or less automatically also get definition files also for *units*. 

Hence, it is going to be trivial to do the same thing for physical units as we are about to do for properties, i.e., give them URIs that are URLs under `https://schemas.optimade.org/units/...`, that point at the unit definitions using the format described in the OPTIMADE specification section 7.2.

I've set things up for this in #445. For example, YAML source files for the angstrom and meter:

- https://github.com/rartino/OPTIMADE/blob/add-property-definitons-3/properties/src/units/current/atomistic/angstrom.yaml
- https://github.com/rartino/OPTIMADE/blob/add-property-definitons-3/properties/src/units/current/si/m.yaml

This actually seems very useful in itself, in that it provides a way in any context to reference our precise unit definitions via this URI.

However, this motivates a few additions I'd like to do the Unit definitions format:
- Allowing an `$id` field also inside the unit definition.
- Allowing `version` and `property-format`, and make `property-format` MANDATORY if the unit definition is not embedded inside a property definition.
- Add another tag `defining-relation` that allows us to describe how the units we define relate to others (primarily to relate them to SI units).

Any thoughts? Given that this PR isn't yet merged, can I add these changes also to this PR, or should it go in its own?

2023-03-01 15:03 UTC, ml-evs requested changes
A few minor comments @rartino. Might make sense to also accept further contributions to this PR if that is easier for you. Will try to respond your most recent comment outside of this particular review.

2023-03-01 15:10 UTC, ml-evs commented
> So, another thing came up as I was working on the property definitions yesterday. It turns out that, since I don't want to duplicate my unit definitions in the source files, I more or less automatically get definition files also for _units_.
> 
> Hence, it is going to be trivial to do the same thing for physical units as we are about to do for properties, i.e., give them URIs that are URLs under `https://schemas.optimade.org/units/...`, that point at the unit definitions using the format described in the OPTIMADE specification section 7.2.
> 
> I've set things up for this in #445. For example, YAML source files for the angstrom and meter:
> 
>     * https://github.com/rartino/OPTIMADE/blob/add-property-definitons-3/properties/src/units/current/atomistic/angstrom.yaml
> 
>     * https://github.com/rartino/OPTIMADE/blob/add-property-definitons-3/properties/src/units/current/si/m.yaml
> 
> 
> This actually seems very useful in itself, in that it provides a way in any context to reference our precise unit definitions via these URIs.
> 
> However, this motivates a few additions I'd like to do the Unit definitions format:
> 
>     * Allowing an `$id` field also inside the unit definition.
> 
>     * Allowing `version` and `property-format`, and make `property-format` MANDATORY if the unit definition is not embedded inside a property definition.
> 
>     * Add another tag `defining-relation` that allows us to describe how the units we define relate to others (primarily to relate them to SI units).

I like the sound of this! 

> **Edit:** Also _one more thing_: we have inherited from JSON Schema that the text in our descriptions uses commonmark. However, it is super inconvenient not to be able to write math expressions in our context. I suppose one could embed HTML MathML. But, for our use, should we not refer to an extension (or define ourselves) that allow embedding of LaTeX expressions inside $ signs?

I think MathML makes som sense as the only real native web standard I know of (especially now that Chrome has support for it again since January 2023), however I think we are all most familiar with LaTeX. GitHub right now will render e.g., 

$$ x = y^2 $$

with MathJax, but seemingly not MathML: 

<math mode="display" xmlns="http://www.w3.org/1998/Math/MathML">
 <semantics>
  <mrow>
    <mi>x</mi>
    <mo>=</mo>
    <mfrac>
      <mrow>
        <mo form="prefix">&minus;</mo>
        <mi>b</mi>
        <mo>&pm;</mo>
        <msqrt>
          <msup><mi>b</mi><mn>2</mn></msup>
          <mo>&minus;</mo>
          <mn>4</mn><mo>&it;</mo><mi>a</mi><mo>&it;</mo><mi>c</mi>
        </msqrt>
      </mrow>
      <mrow>
        <mn>2</mn>
        <mo>&it;</mo>
        <mi>a</mi>
      </mrow>
    </mfrac>
  </mrow>
  <annotation encoding="application/x-tex"><!-- TeX -->
     x = \frac{-b\pm\sqrt{b^2-4ac}}{2a}
  </annotation>
  <annotation encoding="StarMath 5.0">
     x = {-b plusminus sqrt {b^2 - 4 ac}} over {2 a}
  </annotation>
  <!-- More annotations can be written: application/x-troff-eqn for eqn, application/x-asciimath for AsciiMath... -->
  <!-- Semantic MathML go under <annotation-xml encoding="MathML-Content">. -->
 </semantics>
</math>

Given that Mathjax supports MathML input, perhaps this is the standard we could assume (which would also enable asciimath etc)?

2023-03-01 15:24 UTC, rartino commented on optimade.rst
> +  This two element form specifies that the defined property can be :val:`null`.
As much as I dislike the null here (and it is indeed *very much*) it seems OpenAPI 3.1 released in 2021 also has moved over to the "null" type specification: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

Seems odd for us to adopt a way of indicating a nullable field that now is deprecated in OpenAPI?

2023-03-01 15:28 UTC, rartino commented on optimade.rst
> +  This two element form specifies that the defined property can be :val:`null`.
Oh, it is actually even worse:

*"In order to achieve the goal of letting JSON Schema tools understand OpenAPI, it was decided to remove nullable entirely instead of deprecate it."* 

We wouldn't even be compatible with OpenAPI 3.1 then, if we went with a nullable field. They also make a good point that they don't like `nullable` because it removes a constraint rather than adding one. I guess the best design would have been a `non-nullable` field.

2023-03-01 15:32 UTC, ml-evs commented on optimade.rst
> +  This two element form specifies that the defined property can be :val:`null`.
Haha wow, thanks for checking that. I guess the current OpenAPI schemas need to be updated once this change gets down to pydantic too :sweat_smile:

2023-03-01 15:33 UTC, ml-evs approved these changes
I'll approve this for now @rartino, just let me know if you want another review if you do add the unit stuff here.

2023-03-01 15:49 UTC, rartino commented
> I think we are all most familiar with LaTeX. GitHub right now will render e.g., $x=y^2$, but seemingly not MathML [...] Given that Mathjax supports MathML input, perhaps this is the standard we could assume (which would also enable asciimath etc)?

I think this is a great way to go. How is it best expressed? Something like:

- Formatting in the text SHOULD use Markdown in the [CommonMark v0.3 format](https://spec.commonmark.org/0.30/), with mathematical expressions rendered  using the LaTeX mode of [Mathjax 3.2](https://docs.mathjax.org/en/v3.2-latest/). When possible, it is preferable if mathematical expressions use as straightforward notation as possible to make them readable also when not rendered through Mathjax.

I rather not allow people to use MathML as it really isn't very human readable in raw form.

2023-03-01 19:49 UTC, fekad commented
> Sounds good to me! I think that makes it a lot easier for us to host a really nice rendered version of the definitions and schemas somewhere outside of GitHub

In that case [KaTex](https://katex.org/) could also be a nice Latex renderer.

2023-03-02 09:13 UTC, rartino commented
Ok @ml-evs, @vaitkus, @fekad I've made the edits I intend to the Physical Unit Definitions and added the formulation about MathJax. 

@fekad: the reference to Mathjax is only there to define the format, one can of course use any library that can render that format; which is also why I think forcing Mathjax *LaTeX* is the way to go, since LaTeX is fairly well supported also in many other non-web contexts.

I may have bit off a bit much with taking on the "defining-relation" here, because it became more extensive and tricky to define than I had thought. If people do not like the design I landed in, I'll suggest we take it out entirely now (we'd simply not provide this information anywhere else than in the description text in this version of the format), and we can work out a better way to do it in a machine-readable format for a v1.3 Property Definition format, e.g., during the upcoming workshop.

2023-03-02 10:25 UTC, ml-evs reviewed
Only had a second to read so will submit this review now and come back to it later!

2023-03-02 10:25 UTC, ml-evs commented on optimade.rst
> +  When possible, it is preferable for mathematical expressions to use an as straightforward notation as possible to make them readable also when not rendered.
```suggestion
  When possible, it is preferable for mathematical expressions to use as straightforward notation as possible to make them readable also when not rendered.
```

This reads a bit strangely to me with "an" though it is it not necessarily incorrect, so feel free to ignore this suggestion if you disagree

2023-03-02 10:45 UTC, rartino commented on optimade.rst
> +  For example, the defining relation of the temperature unit Fahrenheit ``F`` in Celsius ``C``, that says that ``1 F = (1 - 32) * (5/9) C`` could be expressed as follows:
```suggestion
  For example, the defining relation of the temperature unit Fahrenheit ``F`` in Celsius ``C``, that says that ``x F = (x - 32) * (5/9) C`` could be expressed as follows:
```

2023-03-02 11:18 UTC, rartino commented on optimade.rst
> +- :field:`defining-relation`: Dictionary.
I've realized a possible need for further caution here. Many (most?) units are defined by relations to SI units today. However, there are some that are not.

The only good example I found after a quick look around is the atomic mass unit (u; dalton). It only has an approximate relation to kg (1 u ~= 1.66053906660(50)×10^-27 kg). We actually have to define this unit in OPTIMADE, since we use it for masses in species.

I'm thinking the mass unit should not be expressed with a defining relation (and maybe we should clarify in the text that `defining-relation` is NOT for that.) But then perhaps it would be nice to have some other way of expressing the best known non-defining relation to SI units?

2023-03-02 11:24 UTC, rartino commented on optimade.rst
> +  The dictionary MUST adhere to the following format:
```suggestion
  A dictionary that encodes a defining relation to another unit or set of units, with the primary intended use of relating a unit to its definition in SI units, if such a relationship exists.
  Some units, e.g., the atomic mass unit (also known as dalton, commonly denoted ``u``), only has an approximate relationship to SI units, in which case the :field:`defining-relation` MUST be omitted or :val:`null`.
  The dictionary MUST adhere to the following format:
```

2023-03-02 11:26 UTC, vaitkus reviewed
Some initial comments.

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +    These three fields specify the value as the rational number :field:`numerator` / :field:`denominator`, multiplied by 10 to the power of :field:`exponent`. If omitted or :val:`null`, the defaults
```suggestion
    These three fields specify the value as the rational number :field:`numerator` / :field:`denominator`, multiplied by 10 to the power of :field:`exponent`.
    If omitted or :val:`null`, the defaults for the :field:`numerator`, :field:`denominator`, and :field:`exponent` are respectively 1, 1, and 0.
```

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +  If the fields in :field:`scale` are designated as `sn`, `sd`, and `se`; and the fields in :field:`offset` are designated as ``on``, ``od``, and ``oe``; and :field:`base-units-expression` is designa
What does `u` stand for in the expression?

Also, `b` is defined, but not actually used in the expression?

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +        "numerator": 160,
```suggestion
        "numerator": -160,
```

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +
Would it be possible to get another, a slightly more complex example that involves several units?

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +        "numerator": 160,
I guess a minus sign is needed either here or in the denominator.

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +  For example, the defining relation of the temperature unit Fahrenheit ``F`` in Celsius ``C``, that says that ``x F = (x - 32) * (5/9) C`` could be expressed as follows:
```suggestion
  For example, the defining relation of the temperature unit Fahrenheit ``F`` in Celsius ``C``, that says that ``x F = (x - 32) * (5/9) C = 5/9 x + (-160/9) C`` could be expressed as follows:
```

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +  - :field:`scale`: Dictionary. Optional.
A bit of a contradiction -- this seems to fall under the **Required keys**, but is also marked as Optional.

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +  - :field:`offset`: Dictionary. Optional.
A bit of a contradiction -- this seems to fall under the **Required keys**, but is also marked as Optional.

2023-03-02 11:26 UTC, vaitkus commented on optimade.rst
> +  (Comments in descriptions relevant to the end users should go into :field:`description`.)
The unit definition dictionary does not seem to define a `description` field?

2023-03-02 11:31 UTC, rartino commented on optimade.rst
> +  If the fields in :field:`scale` are designated as `sn`, `sd`, and `se`; and the fields in :field:`offset` are designated as ``on``, ``od``, and ``oe``; and :field:`base-units-expression` is designa
```suggestion
  If the fields in :field:`scale` are designated as `sn`, `sd`, and `se`; and the fields in :field:`offset` are designated as ``on``, ``od``, and ``oe``; and :field:`base-units-expression` is designated as ``b``, these fields state the following defining relation: a value ``v`` multiplied by the unit being defined is equal to the following expression ``(v * (se/sd) * 10**se + (oe/od) * 10**oe)*b``, where ``*`` designates multiplication and ``**`` designates exponentiation.
```

2023-03-02 11:32 UTC, rartino commented on optimade.rst
> +  For example, the defining relation of the temperature unit Fahrenheit ``F`` in Celsius ``C``, that says that ``x F = (x - 32) * (5/9) C`` could be expressed as follows:
I mean... I though this really was an obvious exercise for the reader... but ok.

2023-03-02 11:34 UTC, rartino commented on optimade.rst
> +
Ok, perhaps we can add an example of a whole Physical Unit Definition and do multiple units there.

2023-03-02 11:38 UTC, rartino commented on optimade.rst
> +  (Comments in descriptions relevant to the end users should go into :field:`description`.)
It is there? Maybe you just don't see it because you are just looking at the diff? If you fold out downwards from line 2210 you should see it?

2023-03-02 11:41 UTC, vaitkus commented on optimade.rst
> +  (Comments in descriptions relevant to the end users should go into :field:`description`.)
Sorry, my bad, totally missed that.

2023-03-02 11:59 UTC, vaitkus commented on optimade.rst
> +  If the fields in :field:`scale` are designated as `sn`, `sd`, and `se`; and the fields in :field:`offset` are designated as ``on``, ``od``, and ``oe``; and :field:`base-units-expression` is designa
```suggestion
  If the fields in :field:`scale` are designated as `sn`, `sd`, and `se`; and the fields in :field:`offset` are designated as ``on``, ``od``, and ``oe``; and :field:`base-units-expression` is designated as ``b``, these fields state the following defining relation: a value ``v`` multiplied by the unit being defined is equal to the following expression ``(v * (sn/sd) * 10**se + (on/od) * 10**oe)*b``, where ``*`` designates multiplication and ``**`` designates exponentiation.
```

2023-03-02 12:14 UTC, rartino commented on optimade.rst
> +  If the fields in :field:`scale` are designated as `sn`, `sd`, and `se`; and the fields in :field:`offset` are designated as ``on``, ``od``, and ``oe``; and :field:`base-units-expression` is designa
Oh, wow, how did I get this so screwed up. Thanks for actually digging through the details here!

2023-03-02 13:07 UTC, rartino commented on optimade.rst
> +
Done.

2023-03-02 13:08 UTC, rartino commented on optimade.rst
> +  - :field:`scale`: Dictionary. Optional.
Right, this is not the syntax we use. Should be fixed now.

2023-03-02 13:22 UTC, vaitkus commented on optimade.rst
> +          "description": "The Newton SI unit of force, defined as 1 kg m/s^2
```suggestion
          "description": "The newton SI unit of force, defined as 1 kg m/s^2
```

2023-03-02 13:32 UTC, vaitkus commented on optimade.rst
> +          "description": "The Dalton mass unit defined as 1/12 of the mass of an
```suggestion
          "description": "The dalton mass unit defined as 1/12 of the mass of an
```

2023-03-02 13:32 UTC, vaitkus commented on optimade.rst
> +                          redefinition of the SI base units.",
Is this correct here? Seems like a leftover definition of angstrom.

2023-03-02 13:36 UTC, vaitkus commented on optimade.rst
> +(Note: the description strings have been wrapped for readability only)
```suggestion
(Note: the description strings have been wrapped for readability only.)
```

2023-03-02 15:04 UTC, rartino commented on optimade.rst
> +                          redefinition of the SI base units.",
```suggestion
                          using the 2019 redefinition of the SI base units.",
```

2023-03-02 15:05 UTC, rartino commented on optimade.rst
> +                          redefinition of the SI base units.",
Good catch - copy-paste error when I grabbed the string about the SI redefinition.

2023-03-19 11:55 UTC, ml-evs reviewed
Got about halfway through, more than enough for a Sunday morning ;)  Will try to take a look at the rest next week.

I'm still a little worried about all the complexity being added, though each change in isolation seems justifiable. The most complete custom `info/structures` endpoint atm is probably https://oqmd.org/optimade/v1/info/structures, so perhaps we could offer to help them convert to this new format as a trial?

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
> +      A IRI of the external resource, which MAY be a resolvable URL.
```suggestion
      An IRI of the external resource, which MAY be a resolvable URL.
```

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
> +**OPTIONAL keys at all nested levels of the Property Definition which are regarded as annotations to the Property Definition**
```suggestion
**OPTIONAL keys at all nested levels of the Property Definition which are regarded as annotations to the Property Definition:**
```

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
>      Each string in the list MUST be one of :val:`<`, :val:`<=`, :val:`>`, :val:`>=`, :val:`=`, :val:`!=`, :val:`CONTAINS`, :val:`STARTS WITH`, :val:`ENDS WITH`:, :val:`HAS`, :val:`HAS ALL`, :val:`HAS
```suggestion
    Each string in the list MUST be one of :val:`<`, :val:`<=`, :val:`>`, :val:`>=`, :val:`=`, :val:`!=`, :val:`CONTAINS`, :val:`STARTS WITH`, :val:`ENDS WITH`, :val:`HAS`, :val:`HAS ALL`, :val:`HAS ANY`, :val:`HAS ONLY`, :val:`IS KNOWN`, :val:`IS UNKNOWN` with the following meanings:
```

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
> +  - :field:`response-default`: Boolean
```suggestion
  - :field:`response-default`: Boolean.
```

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
>      * :val:`"timestamp"` then :field:`type` is `"string"`.
```suggestion
* :val:`"boolean"`, `"string"`, or `"integer"` then :field:`type` is the same string.
* :val:`"dictionary"` then :field:`type` is `"object"`.
* :val:`"list"` then :field:`type` is `"array"`.
* :val:`"float"` then :field:`type` is `"number"`.
* :val:`"timestamp"` then :field:`type` is `"string"`.
```

Think this is the right indent level, on the rich diff these are currently appearing as inline quotes which I guess is not desirable

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
>      * :val:`"timestamp"` then :field:`type` is `"string"`.
(Same with the implementation notes bulletpoints below, but I can't make suggestions for those in this PR)

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
> +  Formatting in the text SHOULD use Markdown in the `CommonMark v0.3 format <https://spec.commonmark.org/0.30/>`__ format, with mathematical expressions written to render correctly with the LaTeX mod
```suggestion
  Formatting in the text SHOULD use Markdown in the `CommonMark v0.3 format <https://spec.commonmark.org/0.30/>`__ format, with mathematical expressions written to render correctly with the LaTeX mode of `Mathjax 3.2 <https://docs.mathjax.org/en/v3.2-latest/>`__.
```

2023-03-19 11:55 UTC, ml-evs commented on optimade.rst
> +    A IRI of the external resource (which MAY be a resolvable URL).
```suggestion
    An IRI of the external resource (which MAY be a resolvable URL).
```

2023-03-19 20:12 UTC, rartino commented on optimade.rst
>      * :val:`"timestamp"` then :field:`type` is `"string"`.
The implementation notes are actually meant to be set as [block quotes](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#block-quotes) throughout the specification. I mean, I'm happy for any other suggestions - but we've been doing it semi-consistently to separate those segments from the specification text.

2023-04-26 12:02 UTC, JPBergsma commented on optimade.rst
> +  * :val:`"boolean"`, `"string"`, or `"integer"` then :field:`type` is the same string.
```suggestion
  * :val:`"boolean"`, :val:`"string"`, or :val:`"integer"` then :field:`type` is the same string.
```
This should give a more consistent formatting of the types.
perhaps the "object" and "array" should also be preceded by ":val:"

2023-06-16 12:23 UTC, vaitkus commented on optimade.rst
> +- If the property refers to a physical quantity that is dimension and unitless (often also referred to as having the dimension 1) or refers to a dimension and unitless count of something (e.g., the n
```suggestion
- If the property refers to a physical quantity that is dimensionless and unitless (often also referred to as having the dimension 1) or refers to a dimensionless and unitless count of something (e.g., the number of protons in a nucleus) the field MUST have the value :val:`dimensionless`.
```

2023-06-16 12:23 UTC, vaitkus commented on optimade.rst
> +  However, quantities that uses counting units, e.g., the mole, or quantities that use dimensionless units, e.g., the radian MUST NOT set the field to :val:`dimensionless`.
```suggestion
  However, quantities that use counting units, e.g., the mole, or quantities that use dimensionless units, e.g., the radian MUST NOT set the field to :val:`dimensionless`.
```

2023-06-16 12:23 UTC, vaitkus commented on optimade.rst
> +      The symbol used to reference this unit in the dimensional formula.
```suggestion
      The symbol used to reference this unit in the dimensional formula.

```

2023-06-16 12:23 UTC, vaitkus commented on optimade.rst
> +    if the field is missing or :val:`null` the base-units-expression is taken to be equal to 1, i.e., the defining relation is dimensionless.
```suggestion
    If the field is missing or :val:`null` the base-units-expression is taken to be equal to 1, i.e., the defining relation is dimensionless.
```

2023-06-16 12:23 UTC, vaitkus commented on optimade.rst
> +This appendix provides a more complete example of a Property Definition on the format defined in `Property Definitions`_.
```suggestion
This appendix provides a more complete example of a Property Definition in the format defined in `Property Definitions`_.
```

2023-12-23 03:10 UTC, rartino commented on optimade.rst
> +  See subsection `Physical Units in Property Definitions`_ for the details on how units are represented in OPTIMADE Property Definitions and the precise format of this dictionary.
Perhaps we should make x-optimade-unit-definitions always REQUIRED in the outermost level (so, possibly an empty list). The specification just gets bulky from the OPTIONAL - oh but often REQUIRED - categorization. However, setting this to REQUIRED requires updating the property definitions in #445.

2023-12-23 12:52 UTC, ml-evs commented
Now I look at this wrt my comments on #488 and #445, I see we do not use the JSON Schema `pattern` field here. Is that intentional @rartino? It looks like we have `maxLength` and `minLength` for strings but not `pattern`.

2023-12-23 12:57 UTC, ml-evs requested changes

2023-12-23 12:57 UTC, ml-evs commented on optimade.rst
> +
I think the pattern field would squeeze in here (this is the only place GitHub will let me make the suggestion, so could also be reordered above `format`:

```suggestion
  - :field:`pattern`: String.
    A non-negative integer.
    This string SHOULD be a valid regular expression, according to the ECMA-262 regular expression dialect.
    A string instance is considered valid if the regular expression matches the instance successfully. Recall: regular expressions are not implicitly anchored.
```

2023-12-23 15:28 UTC, rartino commented
> I see we do not use the JSON Schema pattern field here. Is that intentional @rartino? It looks like we have maxLength and minLength for strings but not pattern.

`pattern` was indeed excluded intentionally, since we would have to agree on a regex format for OPTIMADE before we can support `pattern` (which to be used here would have to be equal to, or a subset of, ECMA since that is what JSON Schema specifies). Since we likely want to sync the regex format across OPTIMADE, this is waiting for a decision in #160.

For now, I'd suggest we merge the property definitions without 'pattern' and thus the symops would have to be validated outside of what can be done with the schemas. If anyone feels strongly enough about this omission, I think we have all pieces in place to finish #160, and then bring over the regex subset into this PR.

2024-01-05 16:51 UTC, rartino commented on optimade.rst
> +
I added this now, because I am about to merge this whole PR into #445 since they depend on each other. However, I think we need to update the description of pattern to point at whatever OPTIMADE regex subset we allow.

2024-01-05 16:54 UTC, closed without merging

2024-01-05 16:55 UTC, rartino commented
This PR is now merged into #445