Add per entry and per property meta data field.
Materials-Consortia/OPTIMADE pull request #463
Opened 2023-04-11 12:43 UTC by JPBergsma

During the discussion on ranged properties, we thought it would be a good idea to have a method for storing per entry metadata for a property. This has been discussed in Issue #410 and #462.
In this PR, I have added a brief description for this metadata field, so I can use it for the ranged properties in PR #452.

I explicitly allow metadata fields to also have metadata of its own.
When a ranged property would have uncertainty values. That property would be just as large as the original ranged property, so I think it makes sense to allow metadata fields to have metadata themselves.

We can discuss this further during the optimade meeting of next Friday.

2023-04-18 06:53 UTC, merkys reviewed
Thank you for putting together this PR. I like the idea of introducing the metadata mechanism now and specifying the actual metadata properties later.

2023-04-18 06:53 UTC, merkys commented on optimade.rst
> +The name of the metadata field consists of the name of the property for which it contains the metadata, suffixed with "_meta".
Should we explicitly forbid regular (i.e. top-level) fields with `_meta` suffices? We should reserve the suffix for metadata properties.

2023-04-18 12:06 UTC, vaitkus commented on optimade.rst
> +Database-Provider-Specific fields MUST be prefixed with (one of) the prefix(es) registered by the database provider enclosed by underscores("\_", ASCII 95 dec (0x5F)).
```suggestion
Database-Provider-Specific fields MUST be prefixed with one of the prefixes registered by the database provider enclosed by underscores ("\_", ASCII 95 dec (0x5F)).
```

2023-04-18 12:06 UTC, vaitkus commented on optimade.rst
> +Database-Provider-Specific fields MUST be prefixed with (one of) the prefix(es) registered by the database provider enclosed by underscores("\_", ASCII 95 dec (0x5F)).
The parentheses seem a bit redundant and make the text slightly harder to read.

2023-04-18 12:06 UTC, vaitkus commented on optimade.rst
> +The suffix _meta is reserved for properties that contain the metadata, as described in the section `Per property metadata fields`_ and MUST not be used for fields that do not follow the guidelines de
```suggestion
The suffix ``_meta`` is reserved for properties that contain the metadata, as described in the section `Per property metadata fields`_ and MUST not be used for fields that do not follow the guidelines described there.
```

2023-04-18 12:41 UTC, JPBergsma commented on optimade.rst
> +The name of the metadata field consists of the name of the property for which it contains the metadata, suffixed with "_meta".
Yes, that is probably a good idea. I think we should also forbid its use in nested fields, other than specified here.
I have added it under a new section: database specific properties. If you want, I can also add it elsewhere.

2023-04-26 15:29 UTC, JPBergsma commented
During the last online optimade meeting, the point was raised that we should also define how the metadata fields should be defined in the property definitions.

I expect that some metadata subfields occur in several metadata properties with the same meaning. For example, many numerical properties may have a confidence interval. For now, I have specified that these should have the same $id field. (I hope that this was indeed the intention of the original $id field) but should otherwise be declared repeatedly. 
Another option would be to allow custom data types that could be defined elsewhere, but I think that would be too complicated to include in this PR.

I have also added a metadata_for field to the metadata dictionary, as asked by @sauliusg. I do not think we reached a consensus on whether this field should be added, so I can easily remove it if that is what you prefer.

Do we want to return only the field name or the complete path including the field name in the metadata_for field?

2023-04-27 12:11 UTC, rartino commented on optimade.rst
> +The subfields SHOULD have the same value for the $id field if the $id field is present and the subfields are otherwise identical.
```suggestion
The subfields SHOULD have the same value for the :field:`$id` field if the :field:`$id` field is present and the subfields are otherwise identical.
```

2023-04-27 12:22 UTC, rartino commented
As far as I can see, we still don't have a solution to the concerns of some people in the last meeting that it is an issue to limit the field name namespace; i.e., we really should use a different meta name delimiter?

(@sauliusg alternatively argued to reduce the `_meta` suffix naming to SHOULD or MAY level, and rely completely on `metadata_for` in the property definition for the connection was the solution. But, I'm still reluctant to that, since because of code design convenience I want to be able to write code that can detect and parse ranged properties in the output without having to know about the property definitions. That will only be possible if the metadata field name is derivable from the field name.)

2023-05-01 13:10 UTC, JPBergsma commented on optimade.rst
> +Fields in this metadata MAY also have a metadata field.
If you consider a metadata property that has a value for each value in the main property (For example a confidence interval) then such a metadata property can become quite large. So to solve this, we could treat it as a ranged property. However, for this to work, the field in the metadata would need to have its own meta_data field to store the needed metadata for a ranged property. 
So that is the main reason for allowing nested metadata fields.

2023-05-01 14:45 UTC, JPBergsma commented on optimade.rst
> +- **metadata_for**: which contains a string with the name of the property for which this meta data property contains the meta data,
Sorry, that was not clear to me from the discussion. I'll change the description so that the metadata_for should be in the property definition.

2023-05-04 11:31 UTC, sauliusg commented
> argued to reduce the `_meta` suffix naming to SHOULD or MAY level, and rely completely on `metadata_for` in the property definition for the connection was the solution. But, I'm still reluctant to that, since because of code design convenience I want to be able to write code that can detect and parse ranged properties in the output without having to know about the property definitions. That will only be possible if the metadata field name is derivable from the field name.

I would once again advise against assigning special meanings or special requirements to names. IMHO this is a technological debt, and a pretty nasty one.

Special names pollute the name space, and if we go that way and try to apply it universally, we might very soon arrive at contradictory requirements. We were bitten several times by a decision to use "special" names, do I am wary about such choices.

If a data element "is_metadata_for" is embedded into the data response, what is a problem to test it and get the necessary information during processing?

2023-06-08 21:38 UTC, rartino commented on optimade.rst
> +           }
```suggestion
           "meta": {
             "property_metadata": {
               "element_ratios": {
                 "_exmpl_confidence_interval": [[0.33325,0.33347],[0.22190,0.22268],[0.44392,0.44458]],
                 "_exmpl_confidence_level": 0.95
               },
               "_exmpl_uploader" : "John Doe"
             }
           }
```

2023-06-08 21:40 UTC, rartino commented on optimade.rst
> +For the JSON response format, the resource object metadata field, :field:`meta`, is used, see `JSON Response Schema: Common Fields`_.
```suggestion
For the JSON response format, a subfield :field:`property_metadata` of the resource object metadata field, :field:`meta`, is used, see `JSON Response Schema: Common Fields`_.
```

2023-06-08 21:46 UTC, rartino submitted a review, later dismissed
This PR has undergone a major overhaul after many of the comments above.

@gmrigna , @sauliusg , @giovannipizzi  Please review and merge. (As long as there is nothing here you fundamentally disagree with, it is better that we get this into the specification now and align it with the rest of the ongoing changes in the number of other interconnected PRs)

2023-06-08 22:45 UTC, rartino commented on optimade.rst
> +  In addition the :field:`meta` can also hold metadata fields that apply to the entry as a whole.
- **meta**: a `JSON API meta object <https://jsonapi.org/format/1.0/#document-meta>`__ that is used to communicate `Metadata properties`_.

  It MAY contain the following keys:

  - **property_metadata**: an object containing per-entry and per-property metadata.
    The keys are the names of the fields in :field:`attributes` for which metadata is available.
    The values belonging to these keys are dictionaries containing the relevant metadata fields.

2023-06-08 22:47 UTC, rartino commented on optimade.rst
> +  In addition the :field:`meta` can also hold metadata fields that apply to the entry as a whole.
```suggestion
- **meta**: a `JSON API meta object <https://jsonapi.org/format/1.0/#document-meta>`__ that is used to communicate per-entry metadata.
  It MAY contain the following keys:

  - **property_metadata**: an object used to communicate `Metadata properties`_.
    The keys are the names of the fields in :field:`attributes` for which metadata is available.
    The values belonging to these keys are dictionaries containing the relevant metadata fields.
```

2023-06-08 22:50 UTC, rartino commented on optimade.rst
> +  In addition the :field:`meta` can also hold metadata fields that apply to the entry as a whole.
```suggestion
  Each resource object MAY contain a :field:`meta` field used to communicate metadata.
  The subkey :field:`property_metadata` is used to communicate `Metadata properties`_.
  The keys of the :field:`property_metadata` field are the names of the fields in :field:`attributes` for which metadata is available.
  The values belonging to these keys are dictionaries containing the relevant metadata fields.
```

2023-06-08 22:59 UTC, rartino commented on optimade.rst
> +    The values belonging to these keys are dictionaries containing the relevant metadata fields.
```suggestion
- **meta**: a `JSON API meta object <https://jsonapi.org/format/1.0/#document-meta>`__ that is used to communicate metadata.
  See `JSON Response Schema: Common Fields`_ for more information about this field.
```

2023-06-08 23:00 UTC, rartino commented on optimade.rst
> +  The values belonging to these keys are dictionaries containing the relevant metadata fields.
```suggestion
  The :field:`data` field MAY also contain a :field:`meta` field with the following key:

  - **property_metadata**: an object containing per-entry and per-property metadata.
    The keys are the names of the fields in :field:`attributes` for which metadata is available.
    The values belonging to these keys are dictionaries containing the relevant metadata fields.
```

2023-06-09 07:53 UTC, rartino commented
Workshop: the overall design is correct; meta -> property_metadata -> [name of attribute]. We should revisit the specific example given, and then merge this. Several other PRs are related/affected, but this should be merged first as the general mechanism for per-entry per-property metadata; other things will be added by other PRs. Some specific details have changed recently, so some careful review of the present text would be desirable.

2023-06-09 14:04 UTC, JPBergsma commented on optimade.rst
> +             "property_metadata": {
```suggestion
             "attributes_metadata": {
```

2023-06-11 12:12 UTC, rartino commented on optimade.rst
> +             "property_metadata": {
@sauliusg @giovannipizzi Right, what did we end up saying about this name?

I was somewhat in favor of "property_metadata" since this is the metadata channel for metadata of OPTIMADE properties when implemented in the JSON response format. I suppose one *can* argue that OPTIMADE properties are implemented in the JSON response format as attributes (except for id, type...) and as such, naming the channel "attributes_metadata" also makes some sense.

Any thought on this? Do we care at all? I'm assuming @JPBergsma prefers "attributes_metadata" since he proposes the change.

2023-06-11 12:16 UTC, rartino commented on optimade.rst
> +                 "_exmpl_confidence_level": 0.95
```suggestion
                 "_exmpl_originates_from_project": "piezoelectic_perovskites"
```

2023-06-11 12:16 UTC, rartino commented on optimade.rst
> +               "_exmpl_uploader" : "John Doe"
```suggestion
```

2023-06-11 12:18 UTC, rartino commented on optimade.rst
> +             "_exmpl_uploader" : "John Doe"
```suggestion
               "_exmpl_originates_from_project": "ferroelectric_binaries"
             },
```

2023-06-11 12:26 UTC, rartino commented on optimade.rst
> +         // ...
```suggestion
    .. code:: jsonc
         // ...
         "x-optimade-metadata-definition": {
           "title": "Metadata for the element_ratios field",
           "description": "This field contains the per-entry metadata for the element_ratios field.",
           "x-optimade-type": "dictionary",
           "x-optimade-unit": "inapplicable",
           "type": ["object", "null"],
           "properties" : {
             "_exmpl_originates_from_project": {
               "$id": "https://properties.example.com/v1.2.0/element_ratios_meta/_exmpl_originates_from_project",
               "description" : "A string naming the internal example.com project id where this property was added to the database.",
               "x-optimade-type": "string",
               "x-optimade-unit" : "inapplicable",
             }
           }
         }
         // ...
```

2023-06-11 12:32 UTC, rartino submitted a review, later dismissed

2023-06-12 07:38 UTC, merkys commented on optimade.rst
> +             "property_metadata": {
I prefer "property" as this is the term used in OPTIMADE specification. Term "attributes" is specific to JSON:API, thus I would suggest us not to tie with it. If in future alongside JSON:API we introduce XML representation with OPTIMADE terms, having both "properties" and "attributes" may add unnecessary confusion.

2023-06-12 07:47 UTC, merkys commented on optimade.rst
> +  The :field:`data` field MAY also contain a :field:`meta` field with the following key:
```suggestion
  Every resource object MAY also contain a :field:`meta` field with the following key:
```
`data` may not be an object, but a list. The sentence above (line 666) handles that nicely, I suggest extending the same here.

2023-06-12 07:54 UTC, merkys requested changes
Some minor things need correcting, but the overall design looks good.

2023-06-12 13:40 UTC, merkys commented on optimade.rst
> +           }
Please fix the spelling of `propertiy_metadata`, otherwise this seems appropriate.

2023-06-12 14:22 UTC, vaitkus commented on optimade.rst
> +Example of a response in the JSON response format with two structure entries that each include a metadata property for the attribute field :field:`element_ratios` and the database specific per entry
```suggestion
Example of a response in the JSON response format with two structure entries that each include a metadata property for the attribute field :field:`element_ratios` and the database specific per entry metadata field :field:`_exmpl_uploader` :
```

2023-06-12 14:22 UTC, vaitkus commented on optimade.rst
> +             "element_ratios":[0.33336, 0.22229, 0.44425],
```suggestion
             "element_ratios":[0.33336, 0.22229, 0.44425]
```

2023-06-12 14:22 UTC, vaitkus commented on optimade.rst
> +               },
```suggestion
               }
```

2023-06-12 14:22 UTC, vaitkus commented on optimade.rst
> +             "element_ratios":[0.5, 0.5],
```suggestion
             "element_ratios":[0.5, 0.5]
```

2023-06-12 14:22 UTC, vaitkus commented on optimade.rst
> +               },
```suggestion
               }
```

2023-06-12 14:22 UTC, vaitkus commented on optimade.rst
> +               "x-optimade-unit" : "inapplicable",
```suggestion
               "x-optimade-unit" : "inapplicable"
```

2023-06-12 15:00 UTC, JPBergsma commented on optimade.rst
> +             "property_metadata": {
Sorry, I did not realize this suggestion was already posted.
During the discussion in the coffee room, we decided that the name would be "attributes_metadata". 
In one of the examples on the white boards for the ranged properties, the term "property_metadata" was used, which is probably where @rartino got it from. "attributes_metadata" sounds more fitting for the JSON response, but I do not have a strong preference for the name. If the majority wants "property_metadata", that's also fine with me.

2023-06-12 15:20 UTC, rartino approved these changes

2023-06-12 15:22 UTC, merkys approved these changes

2023-06-13 14:30 UTC, JPBergsma commented on optimade.rst
> +For the JSON response format, a subfield :field:`property_metadata` of the resource object metadata field, :field:`meta`, is used, see `JSON Response Schema: Common Fields`_.
To me, this sentence leaves me wondering for what "a subfield :field:`property_metadata`" is used. So I have tried to make it clearer.
```suggestion
For the JSON response format, the metadata properties are stored in the resource object metadata field, :field:`meta`, see `JSON Response Schema: Common Fields`_. 
Metadata, that does not apply to the entry as a whole but only to the individual properties under attributes, is stored under the subfield :field:`property_metadata` in dictionaries with the name of the property as the key. 
```

2023-06-13 14:53 UTC, JPBergsma commented on optimade.rst
> +The metadata property is a dictionary in the format specified by the field :field:`x-optimade-metadata-definition` in the Property Definition of the field, see `Property Definitions`_.
To me, this sentence leaves me wondering for what "a subfield :field:`property_metadata`" is used. So I have tried to make it clearer.
```suggestion
For the JSON response format, the metadata properties are stored in the resource object metadata field, :field:`meta`, see `JSON Response Schema: Common Fields`_. 
Metadata, that does not apply to the entry as a whole but only to the individual properties under attributes, is stored under the subfield :field:`property_metadata` in dictionaries, here called metadata properties,  with the name of the property as the key . 

The format of the metadata property is specified by the field :field:`x-optimade-metadata-definition` in the Property Definition of the field, see `Property  #Definitions`_.
```

2023-06-13 15:02 UTC, JPBergsma commented on optimade.rst
> +The reason for this limitation is to avoid name collisions with standard metadata fields defined by the OPTIMADE standard that apply also to database-specific data fields.
```suggestion
The reason for this limitation is to avoid name collisions with metadata fields defined by the OPTIMADE standard in the future that apply also to database-specific data fields.
```

2023-06-14 10:08 UTC, ml-evs commented on optimade.rst
> +However, when an implementation supports the :field:`meta` field, it SHOULD return the metadata for any of the fields that are in the returned entries as well as metadata that applies to the entries
Just to clarify, does this mean that I will get back metadata on fields not in the response if that entry both a) has a value for that field and b) has metadata for that field?

2023-06-14 10:08 UTC, ml-evs commented on optimade.rst
> +    The values belonging to these keys are dictionaries containing the relevant metadata fields.
This should link back to the section where per entry metadata is defined

2023-06-14 13:37 UTC, JPBergsma commented on optimade.rst
> +However, when an implementation supports the :field:`meta` field, it SHOULD return the metadata for any of the fields that are in the returned entries as well as metadata that applies to the entries
I think our intention was to only make returning data for the properties that are in the actual response mandatory.
But perhaps we should change the text if that makes it clearer. 
How about this ?
```suggestion
However, when an implementation supports the :field:`meta` field, it SHOULD return the metadata for any of the fields that are in the response as well as metadata that applies to the entries as a whole.
```

2023-06-14 13:47 UTC, JPBergsma commented on optimade.rst
> +           }
Should we not add an example of a per entry metadata property here?

2023-06-14 14:21 UTC, JPBergsma commented
I am still wondering how the metadata fields for the entry as a whole should be defined. 
@rartino as you wrote the PR on the property definitions, could you add an example how this should be done?

2023-06-14 15:26 UTC, rartino commented on optimade.rst
> +-------------------
```suggestion
Entry metadata
--------------
```

2023-06-14 15:29 UTC, rartino commented on optimade.rst
> +-------------------
I didn't think this PR was meant to define metadata for the entry as a whole, because I don't know where the corresponding property definition would go. Can I suggest that the edit to allow per-entry metadata be done as another PR on top of this one?

I see there are some minor wording I had missed that allow this. I'll merge a few changes to remove them (the PR to put them back can still get them out from the edit history).

2023-06-14 15:41 UTC, rartino commented on optimade.rst
> +
```suggestion
However, when an implementation supports the :field:`meta` field, it SHOULD return the metadata for any of the fields that are in the response.

```

2023-06-15 10:19 UTC, vaitkus commented on optimade.rst
> +Database providers are allowed to define their own metadata properties in :field:`x-optimade-metadata-definition`, but they MUST use the database-specific prefix even for metadata for database-specif
Should `database-provider prefix` here be changed to `database-provider-specific prefix` or do they have different meanings?

2023-06-15 10:19 UTC, vaitkus commented on optimade.rst
> +However, when an implementation supports the :field:`meta` field, it SHOULD return the metadata for any of the fields that are in the response.
Could you please clarify with of the two interpretations (if any) is the correct one:
* "<...> it SHOULD return the metadata for *all* of the fields".
* "<...>  it SHOULD be able to return the metadata for any of the fields".

2023-06-15 11:12 UTC, rartino commented on optimade.rst
> +However, when an implementation supports the :field:`meta` field, it SHOULD return the metadata for any of the fields that are in the response.
```suggestion
However, when an implementation supports the :field:`property_metadata` field, it SHOULD return metadata fields for all fields present in the data part of the response which has metadata.
```

2023-06-15 11:13 UTC, rartino commented on optimade.rst
> +Database providers are allowed to define their own metadata properties in :field:`x-optimade-metadata-definition`, but they MUST use the database-specific prefix even for metadata for database-specif
```suggestion
Database providers are allowed to define their own metadata properties in :field:`x-optimade-metadata-definition`, but they MUST use the database-provider-specific prefix even for metadata for database-specific fields.
```

2023-06-16 06:59 UTC, merkys commented
Anyone is working on resolving the conflict? If not, I can give it a stab.

2023-06-16 07:04 UTC, rartino submitted a review, later dismissed

2023-06-16 07:07 UTC, rartino commented
@merkys Sorry, didn't see your comment. Already did the merge - it was a bit nasty, but not too bad.

I'm happy with this PR as it now is. There is apparently some disagreement over what the key inside "meta" should be to communicate metadata for properties. Perhaps @giovannipizzi and @sauliusg who were part of the referenced discussion can take a side on that? Or, for that matter, anyone else.

2023-06-16 07:15 UTC, merkys commented
> @merkys Sorry, didn't see your comment. Already did the merge - it was a bit nasty, but not too bad.

No problem, I wanted to get an ACK before embarking on it anyway.

2023-06-16 07:16 UTC, merkys commented on optimade.rst
> +The format of the metadata property is specified by the field :field:`x-optimade-metadata-definition` in the Property Definition of the field, see `Property  #Definitions`_.
```suggestion
The format of the metadata property is specified by the field :field:`x-optimade-metadata-definition` in the Property Definition of the field, see `Property Definitions`_.
```

2023-06-16 07:25 UTC, merkys approved these changes
I re-approve the proposal. I prefer the current key name `property_metadata`.

2023-06-16 08:39 UTC, vaitkus commented on optimade.rst
> +Database providers are allowed to define their own metadata properties in :field:`x-optimade-metadata-definition`, but they MUST use the database-provider-specific prefix even for metadata for databa
```suggestion
Database providers are allowed to define their own metadata properties in :field:`x-optimade-metadata-definition`, but they MUST use the database-provider-specific prefix even for metadata of database-specific fields.
```

2023-06-16 08:39 UTC, vaitkus commented on optimade.rst
> +Example of a response in the JSON response format with two structure entries that each include a metadata property for the attribute field :field:`element_ratios` and the database-specific per entry
Field `_exmpl_uploader` does not seem to actually be used in the provided example.

2023-06-16 08:39 UTC, vaitkus commented on optimade.rst
> +For the JSON response format, the metadata properties are stored in the resource object metadata field, :field:`meta` in a dictionary field :field:`property_metadata` with the keys equal to the names
```suggestion
For the JSON response format, the metadata properties are stored in the resource object metadata field, :field:`meta` in a dictionary field :field:`property_metadata` with the keys equal to the names of the respective properties for which metadata is available, see `JSON Response Schema: Common Fields`_.
```

2023-06-16 09:59 UTC, rartino commented on optimade.rst
> +Example of a response in the JSON response format with two structure entries that each include a metadata property for the attribute field :field:`element_ratios` and the database-specific per entry
```suggestion
Example of a response in the JSON response format with two structure entries that each include a metadata property for the attribute field :field:`element_ratios` and the database-specific per entry metadata field :field:`_exmpl_originates_from_project` :
```

2023-06-16 10:00 UTC, rartino approved these changes

2023-06-16 11:02 UTC, merkys approved these changes

2023-06-16 11:24 UTC, vaitkus approved these changes

2023-06-16 11:24 UTC, merged

2023-06-16 18:13 UTC, JPBergsma commented on optimade.rst
> +-------------------
Yes, we can do that as a separate PR. If I remember correctly, the partial data PR however depends on the per entry metadata field, so we would need to correct that. (That should be easy, as I think it only allows returning one property at a time.)