Symmetry operation specifications in Jones faithful notation (defined by PCRE)
Materials-Consortia/OPTIMADE pull request #464
Opened 2023-06-06 08:38 UTC by sauliusg

Please follow [the guidelines here](https://github.com/Materials-Consortia/OPTIMADE/wiki/How-to-contribute#submit-proposed-changes) to create a new pull request.
If your pull request requires discussion, make sure the OPTIMADE developer list is alerted (for more info see the link above.)

2023-06-06 08:54 UTC, sauliusg commented
NB: the text will be added/expanded later, for now its just the REs and the tests.

2023-06-06 09:33 UTC, merkys requested changes
The regular expression for symmetry operators looks good to me. Text tying them to OPTIMADE properties is needed, but the regex part seems appropriate.

2023-06-06 10:22 UTC, merkys commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
Fair point. At some point in time canonicalization was preferred, but it seems that [later this requirement was relaxed](https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1363208516).

2023-06-09 07:46 UTC, rartino commented
Workshop suggestion: we accept the syntax specification. The remaining fields from #416  https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1274498513 should be added to the PR and time given to symmetry description stakeholders to review. @rartino @sauliusg @vaitkus @merkys @giovannipizzi (feel free to post a comment below to add yourself to the stakeholders)

2023-06-18 15:36 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
I would argue for allowing both notations, to avoid forcing databases (including ours ;) to parse and re-format symmetry operations just to conform an extra-restrictive rule.

The symops are not intended for searching either, and a client will have to parse the strings into matrices anyway; both representations are equally easy to parse.

2023-06-18 15:37 UTC, sauliusg commented on optimade.rst
> +    $symop_translation_appended = "[-+]? [xyz] ([-+][xyz])? ([-+] ($translations) )?";
Added explanation and links into the description, please have a look.

2023-06-18 15:38 UTC, sauliusg commented on optimade.rst
> +    #END PCRE symops
Examples are provided along with the property definition. Here the property name is mentioned. As far as I see, this is the common way to place examples.

2023-06-18 18:13 UTC, vaitkus commented on optimade.rst
> +    #END PCRE symops
Ok.

2023-06-18 18:13 UTC, vaitkus commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
Well, some parsing and reformatting is unavoidable since real life symop values (from CIFs) contain spaces, decimal numeric values (0.5 instead of 1/2) and other irregularities. I would strive for a simpler and more uniform representation from all databases.

2023-06-18 18:15 UTC, vaitkus commented on optimade.rst
> +Symmetry operation strings that describe :property:`space_group_symmetry_operation_xyz` property MUST conform to the following regular epxressions.
```suggestion
Symmetry operation strings that describe :property:`space_group_symmetry_operation_xyz` property MUST conform to the following regular expressions.
```

2023-06-19 06:38 UTC, merkys commented on optimade.rst
> +  The interpretation of the strings MUST follow the conventions of the IUCr CIF core dictionary (IUCr, 2023).
I would suggest adding a hyperlink to the CIF Core dictionary here directly instead of putting it in references.

2023-06-19 06:43 UTC, merkys commented on optimade.rst
> +  In particular, this property MUST explicitly provide all symmetry operations needed to generate all the atoms in the unit cell from the atoms in the asymmetric unit, for the setting used.
Correct me if I am wrong, but the number of symmetry operators needed to generate all atom positions is less or equal to the group (in math sense) of symmetry operators. The current intention seems to not require the full group, just the site-renegerating subset, right?

2023-06-19 07:46 UTC, sauliusg commented on optimade.rst
> +  In particular, this property MUST explicitly provide all symmetry operations needed to generate all the atoms in the unit cell from the atoms in the asymmetric unit, for the setting used.
If we have just atoms in the asymmetric unit, then *all* symmetry operators (including the identity) must be applied to all atoms to get the full unit cell. Thus, all group operators must be provided, and each operator must be provided just once (maybe this latter point needs to be stressed specially).

The intention is to have the same rules as in the [`_space_group_symop_operation_xyz`](https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Ispace_group_symop_operation_xyz.html) definition.

2023-06-19 08:08 UTC, sauliusg commented on optimade.rst
> +  The interpretation of the strings MUST follow the conventions of the IUCr CIF core dictionary (IUCr, 2023).
Hmm, the link looks long if spelled out in the text, and will not be available in printed PDF if we just "hide" it under the text. Giving full bibliography references to Web pages seems to me like a good practice, since it gives all information, including the access times, titles, authorship and publication date or year. It is endorsed by most recommendations of the Harvard citation style (say, by [ICL](https://www.imperial.ac.uk/media/imperial-college/administration-and-support-services/library/public/Harvard-guide-2022.pdf) or [Himmelfarb Health Sciences Library](https://guides.himmelfarb.gwu.edu/harvard_citation/all-examples)].

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +  The change-of-basis operators are used as defined in the International Tables of Crystallography (ITC) Vol. B, Sect. 1.4, Appendix A1.4.2 (IUCr, 2001).
```suggestion
  The change-of-basis operations are used as defined in the International Tables of Crystallography (ITC) Vol. B, Sect. 1.4, Appendix A1.4.2 (IUCr, 2001).
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +Space group symbols with change-of-basis operators:
```suggestion
Space group symbols with change-of-basis operations:
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +  The syntax of the strings representing symmetry operators MUST conform to regular expressions given in appendix `The Symmetry Operation String Regular Expressions`_.
```suggestion
  The syntax of the strings representing symmetry operations MUST conform to regular expressions given in appendix `The Symmetry Operation String Regular Expressions`_.
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property allo
```suggestion
- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property allows to reconstruct all symmetries of the periodic material.
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +- **Description** A (human-redable) symbol of the space group containing an extended form of the Hermann-Mauguin (H-M) symbol.
```suggestion
- **Description** A human-readable symbol of the space group given in the extended form of the Hermann-Mauguin (H-M) notation.
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +  The same character string encoding conventions MUST be used as for the specificatio of the `space\_group\_symbol\_Hermann_Mauguin`_ propeerty.
```suggestion
  The same character string encoding conventions MUST be used as for the specification of the `space\_group\_symbol\_Hermann_Mauguin`_ property.
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +- **Description** A (human-readable) symbol of the space group containing a short-form of the Hermann-Mauguin (H-M) symbol.
```suggestion
- **Description** A human-readable symbol of the space group given in the short form of the Hermann-Mauguin (H-M) notation.
```

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +- **Description** A (human-readable) symbol of the space group containing a short-form of the Hermann-Mauguin (H-M) symbol.
There might be a better rewording, but the current phrasing "symbol containing a symbol" sound a bit strange.

2023-06-22 06:35 UTC, vaitkus commented on optimade.rst
> +- **Description** A (human-redable) symbol of the space group containing an extended form of the Hermann-Mauguin (H-M) symbol.
There might be a better rewording, but the current phrasing "symbol containing a symbol" sound a bit strange.

2023-06-22 07:33 UTC, sauliusg commented on optimade.rst
> +- **Description** A (human-redable) symbol of the space group containing an extended form of the Hermann-Mauguin (H-M) symbol.
> Rewrote differently.

2023-06-22 07:48 UTC, merkys commented on optimade.rst
> +  The interpretation of the strings MUST follow the conventions of the IUCr CIF core dictionary (IUCr, 2023).
The specification does not seem to use explicit links anywhere else, thus it seems it was not written to be used in printed form anyway.

2023-06-22 07:49 UTC, merkys commented on optimade.rst
> +  In particular, this property MUST explicitly provide all symmetry operations needed to generate all the atoms in the unit cell from the atoms in the asymmetric unit, for the setting used.
Right, I am OK with having the same rules as in CIF core dictionary.

2023-06-22 07:50 UTC, merkys commented on optimade.rst
> +space\_group\_symbol\_Hall
```suggestion
space\_group\_symbol\_hall
```
Identifiers cannot contain uppercase letters.

2023-06-22 07:51 UTC, sauliusg commented on optimade.rst
> +  The interpretation of the strings MUST follow the conventions of the IUCr CIF core dictionary (IUCr, 2023).
Making Web citations in a proper way, as bibliography references, makes a lot of sense to me.

2023-06-22 07:52 UTC, merkys commented on optimade.rst
> +- **Bibliographic References for the 'space\_group\_Hall' definitions**
```suggestion
- **Bibliographic References for the 'space\_group\_symbol\_hall' definitions**
```

2023-06-22 07:52 UTC, sauliusg commented on optimade.rst
> +space\_group\_symbol\_Hall
Cant' they? "Hall" is a proper name and should be spelled capitalized.

2023-06-22 07:53 UTC, merkys commented on optimade.rst
> +space\_group\_symbol\_Hermann_Mauguin
```suggestion
space\_group\_symbol\_hermann\_mauguin
```
In addition, I do not think we need to escape underscores anymore, I think this is a relic from some other format used before.

2023-06-22 07:54 UTC, sauliusg commented on optimade.rst
> +space\_group\_symbol\_Hall
The same applies to Hermann-Mauguin symbols, BTW.

2023-06-22 07:54 UTC, merkys commented on optimade.rst
> +- **Bibliographic References for the 'space\_group\_symbol\_Hermann_Mauguin' definitions**
```suggestion
- **Bibliographic References for the 'space\_group\_symbol\_hermann\_mauguin' definitions**
```

2023-06-22 07:54 UTC, merkys commented on optimade.rst
> +space\_group\_symbol\_Hermann_Mauguin\_extended
```suggestion
space\_group\_symbol\_hermann\_mauguin\_extended
```

2023-06-22 07:54 UTC, merkys commented on optimade.rst
> +  The same character string encoding conventions MUST be used as for the specification of the `space\_group\_symbol\_Hermann_Mauguin`_ property.
```suggestion
  The same character string encoding conventions MUST be used as for the specification of the `space\_group\_symbol\_hermann\_mauguin`_ property.
```

2023-06-22 07:55 UTC, merkys commented on optimade.rst
> +space\_group\_symbol\_Hall
> Cant' they? "Hall" is a proper name and should be spelled capitalized.

Citing the specification:
> **Identifier**
> Names that MUST start with a lowercase letter ([a-z]) or an underscore ("\_") followed by any number of lowercase alphanumerics ([a-z0-9]) and underscores ("\_").

2023-06-22 07:55 UTC, sauliusg commented on optimade.rst
> +space\_group\_symbol\_Hermann_Mauguin
For underscores, I just use the same convention as elsewhere in  the text. If the escaping is indeed not necessary, it should be changed systematically in all text in a separate PR; this PR should not be mixed with the refactoring.

2023-06-22 07:56 UTC, merkys commented on optimade.rst
> +- **Bibliographic References for the 'space\_group\_symbol\_Hermann_Mauguin\_extended' definitions**
```suggestion
- **Bibliographic References for the 'space\_group\_symbol\_hermann\_mauguin\_extended' definitions**
```

2023-06-22 07:57 UTC, vaitkus commented on optimade.rst
> +- **Description** A human- and machine-readable string containing a short Hermann-Mauguin (H-M) symbol specifying the space group of the structure in the response.
```suggestion
- **Description** A human- and machine-readable string containing the extended Hermann-Mauguin (H-M) which specifies the space group of the structure in the response.
```

2023-06-22 07:57 UTC, vaitkus commented on optimade.rst
> +- **Description** A human- and machine-readable string containing a short Hermann-Mauguin (H-M) symbol specifying the space group of the structure in the response.
This should probably be "extended" instead of short?

2023-06-22 07:57 UTC, vaitkus commented on optimade.rst
> +- **Description** A human- and machine-readable string containing a short Hermann-Mauguin (H-M) symbol specifying the space group of the structure in the response.
```suggestion
- **Description** A human- and machine-readable string containing the short Hermann-Mauguin (H-M) symbol which specifies the space group of the structure in the response.
```

2023-06-22 08:01 UTC, merkys commented on optimade.rst
> +space\_group\_symbol\_Hermann_Mauguin
Right, this shoud be changed in a PR on its own.

2023-06-22 08:07 UTC, merkys commented on optimade.rst
> +    However, the property is RECOMMENDED if fractional atom coordinates are returned in the response.
Fractional coordinates have not been included in the specification yet (#206).

2023-06-22 08:08 UTC, sauliusg commented on optimade.rst
> +space\_group\_symbol\_Hall
OK, I remember now, we would otherwise have clash with the Filter operator syntax...
Will change.

2023-06-22 08:09 UTC, merkys commented on optimade.rst
> +  For describing arbitrary symmetries of molecules, non-periodic (finite) collections of atoms or non-crystallographic symmetry, a different property will be used.
```suggestion
  For describing arbitrary symmetries of molecules, non-periodic (finite) collections of atoms or non-crystallographic symmetry, a different property will be defined in future.
```

2023-06-22 08:21 UTC, sauliusg commented on optimade.rst
> +    - MUST be null if :property:`nperiodic_dimensions` is equal to 0.
This is copied from somewhere and should be fixed systematically.

2023-06-22 08:23 UTC, sauliusg commented on optimade.rst
> +  For describing arbitrary symmetries of molecules, non-periodic (finite) collections of atoms or non-crystallographic symmetry, a different property will be used.
"will" be already implies "in the future". It can not be used if it is not defined. The main point is that we do not forget to update this place when it is actually defined. My wording is safer in that it will remain (approximately) valid even if we define the new property and forget to fix the description here. I wold leave as is.

2023-06-22 08:26 UTC, merkys commented on optimade.rst
> +  For describing arbitrary symmetries of molecules, non-periodic (finite) collections of atoms or non-crystallographic symmetry, a different property will be used.
I read "will" here as "below in this document", thus I would suggest clarifying.

2023-06-22 08:27 UTC, sauliusg commented on optimade.rst
> +  The identity operation :val:`x,y,z` MUST be always present.
I am not sure if the new form is better. I did not intend the emphasis it carries in my understanding.

2023-06-22 08:31 UTC, merkys commented on optimade.rst
> +    However, the property is RECOMMENDED if fractional atom coordinates are returned in the response.
I must have accidentally deleted the branch from which #206 was proposed, but there have been calls to rewrite it anyway. I hope I can do that in a week.

2023-06-22 10:29 UTC, sauliusg commented on optimade.rst
> +    However, the property is RECOMMENDED if fractional atom coordinates are returned in the response.
> I must have accidentally deleted the branch from which #206 was proposed,

Oh gosh... That's Git, folks...

But can't you just fetch the PR file from the GitHub server?

2023-06-22 10:33 UTC, merkys commented on optimade.rst
> +    However, the property is RECOMMENDED if fractional atom coordinates are returned in the response.
Yes, I can download the diff and apply it on the parent commit. I will see if I can find that without bisecting the commit history.

2023-06-22 13:14 UTC, vaitkus commented on optimade.rst
> +  If the symmetry operation list is present, it MUST be compatible with other space group specifications (the ITC space group number, the Hall symbol, the Hermann-Mauguin symbol and other space group
```suggestion
  If the symmetry operation list is present, it MUST be compatible with other space group specifications (e.g. the ITC space group number, the Hall symbol, the Hermann-Mauguin symbol) if these are present.
```

2023-06-22 13:14 UTC, vaitkus commented on optimade.rst
> +  - **Query**: Support for queries on this property is not required and in fact is NOT RECOMMENDED.
```suggestion
  - **Query**: Support for queries on this property is not required and is NOT RECOMMENDED.
```

2023-06-22 13:14 UTC, vaitkus commented on optimade.rst
> +  Space group operations for the space group number 5 (H-M symbol `C 2`, extended H-M symbol: `C 1 2 1`, Hall symbol `C 2y`):
```suggestion
  Space group operations for the space group with ITC number 5 (H-M symbol `C 2`, extended H-M symbol: `C 1 2 1`, Hall symbol `C 2y`):
```

2023-06-22 13:14 UTC, vaitkus commented on optimade.rst
> +  Space group operations for the space group number 5 (H-M symbol `C 2`, extended H-M symbol: `C 1 2 1`, Hall symbol `C 2y`):
Same formulation as in the example before.

2023-06-22 13:14 UTC, vaitkus commented on optimade.rst
> +- **Description**: Space group number for the structure assigned by the International Tables for Crystallography Vol. A. (IUCr, 2005)
This sentence reads as if the IUCr assigns space group numbers to structures. Would be better to rephrase it.

2023-06-22 13:20 UTC, merkys commented on optimade.rst
> +  The identity operation :val:`x,y,z` MUST be always present.
Indentation seems missing in the suggested line. Is this intentional?

2023-06-22 13:21 UTC, merkys commented on optimade.rst
> +  - there MUST be NO spaces in the space group generator designation (i.e. use 'P 21/m', not the 'P 21 / m');
Agree, to me this looks strange too.

2023-06-22 13:24 UTC, merkys commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-06-22 13:34 UTC, sauliusg commented on optimade.rst
> +    For example, to find all structures with bibliographic references where one of the authors has the last name "Schmidt" is performed by the following two steps:
The spilling checker complained about "Schmit"... "Schmidt" is the more usual German spelling, AFAIK. But probably, indeed, both ways are OK. Could you please check frequencies on the Web and revert if the previous spelling is widely attested?

2023-06-22 13:34 UTC, sauliusg commented on optimade.rst
> +  The identity operation :val:`x,y,z` MUST be always present.
Why longer version?

2023-06-22 13:44 UTC, vaitkus commented on optimade.rst
> +  - **Query**: Support for queries on this property is not required and in fact is NOT RECOMMENDED.
I think that capitalization emphasizes it enough.

2023-06-22 13:50 UTC, vaitkus commented on optimade.rst
> +  The identity operation :val:`x,y,z` MUST be always present.
@merkys It was indeed missing, fixed.

@sauliusg Well, is unifies the voice between the sentence before it and after it (passive, passive, passive) vs (passive, active, passive) and also specifies that the symmetry operations form a set (i.e. no repeats).

2023-06-22 13:59 UTC, sauliusg commented on optimade.rst
> +  The identity operation :val:`x,y,z` MUST be always present.
Agree to the 'set' argument :)

2023-06-22 14:05 UTC, sauliusg commented on optimade.rst
> +- **Description**: Space group number for the structure assigned by the International Tables for Crystallography Vol. A. (IUCr, 2005)
What about:

"Space group number designated for the space group of the structure by the International Tables for Crystallography Vol. A. (IUCr, 2005)" ?

2023-06-22 14:29 UTC, vaitkus commented on optimade.rst
> +    For example, to find all structures with bibliographic references where one of the authors has the last name "Schmidt" is performed by the following two steps:
"Schmidt" has 388,000,000 hits, "Schmit" 6,080,000.

I opened a separate PR which, among other minor changes, also includes typo and wording fixes from this branch (PR  #478). I also made the last name change there in case people would like to contest it.

2023-06-28 16:31 UTC, vaitkus approved these changes
There are a few minor suggestions that should be addressed before merging. Also, it would be useful if somebody outside of the COD could review the PR (e.g. @rartino or @ml-evs).

2023-06-28 23:14 UTC, ml-evs reviewed
A few minor suggestions:

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property allo
```suggestion
- **Notes** The list of space group symmetry operations applies to the whole system and together with the lattice translations given in the :property:`lattice\_vectors` property allows for the reconstruction of all symmetries of the periodic crystal.
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +  Thus the symmetry operations described in this property are only applicable to material models with at least one periodic dimension.
```suggestion
  Thus, the symmetry operations described in this property are only applicable to material models with at least one periodic dimension.
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +IUCr (2005). International Tables for Crystallography vol. A. Space-Group Symmetry. Ed. Theo Hahn. 5-th edition. Dordrecht, Springer.
```suggestion
  IUCr (2005). International Tables for Crystallography vol. A. Space-Group Symmetry. Ed. Theo Hahn. 5-th edition. Dordrecht, Springer.
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +IUCr (2001). International Tables for Crystallography vol. B. Reciprocal Space. Ed. U. Shmueli. 2-nd edition. Dordrecht/Boston/London, Kluwer Academic Publishers.
```suggestion
  Hall, S. R. (1981) Space-group notation with an explicit origin. Acta Crystallographica Section A, 37, 517-525, International Union of Crystallography (IUCr), DOI: https://doi.org/10.1107/s0567739481001228

  Hall, S. R. (1981a) Space-group notation with an explicit origin; erratum.  Acta Crystallographica Section A, 37, 921-921, International Union of Crystallography (IUCr), DOI: https://doi.org/10.1107/s0567739481001976

  IUCr (2001). International Tables for Crystallography vol. B. Reciprocal Space. Ed. U. Shmueli. 2nd edition. Dordrecht/Boston/London, Kluwer Academic Publishers.
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +IUCr (2023) Core dictionary (coreCIF) version 2.4.5; data name `\_space\_group\_symop\_operation\_xyz`. Available from: https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Ispace_group_symop_
```suggestion
  Bradley, C. J. and Cracknell, A. P. (1972) The Mathematical Theory of Symmetry in Solids. Oxford, Clarendon Press (paperback edition 2010) 745 p. ISBN `978-0-19-958258-7 <https://isbnsearch.org/isbn/9780199582587>`__.

  IUCr (2023) Core dictionary (coreCIF) version 2.4.5; data name `\_space\_group\_symop\_operation\_xyz`. Available from: https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Ispace_group_symop_operation_xyz.html [Accessed 2023-06-18T16:46+03:00].
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +Space group symbols with explicit origin (the Hall symbols):
```suggestion
  Space group symbols with explicit origin (the Hall symbols):
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +Space group symbols with change-of-basis operations:
```suggestion
  Space group symbols with change-of-basis operations:
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +  - :val:`P 21 21 21`
Can we also enumerate the possible H-M symbols in this format for easier validation?

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +IUCr (2005). International Tables for Crystallography vol. A. Space-Group Symmetry. Ed. Theo Hahn. 5-th edition. Dordrecht, Springer.
```suggestion
  IUCr (2001). International Tables for Crystallography vol. B. Reciprocal Space. Ed. U. Shmueli. 2-nd edition. Dordrecht/Boston/London, Kluwer Academic Publishers.

  IUCr (2005). International Tables for Crystallography vol. A. Space-Group Symmetry. Ed. Theo Hahn. 5-th edition. Dordrecht, Springer.
```

2023-06-28 23:14 UTC, ml-evs commented on optimade.rst
> +Symmetry operation strings that describe :property:`space_group_symmetry_operation_xyz` property MUST conform to the following regular expressions.
```suggestion
Symmetry operation strings that comprise the :property:`space_group_symmetry_operation_xyz` property MUST conform to the following regular expressions.
```

2023-06-30 12:54 UTC, sauliusg commented on optimade.rst
> +  Space group operations for the space group with ITC number 3 (H-M symbol: `P 2`, extended H-M symbol: `P 1 2 1`, Hall symbol `P 2y`):
"Space group operations" are more specific (not every symmetry operation is a space group (symmetry) operation), and this is important here (only space group (symmetry) operations are provided here); I wold therefore leave this distinction.

2023-06-30 12:54 UTC, sauliusg commented on optimade.rst
> +  Space group operations for the space group with ITC number 5 (H-M symbol `C 2`, extended H-M symbol: `C 1 2 1`, Hall symbol `C 2y`):
Same as above...

2023-06-30 13:01 UTC, sauliusg commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property allo
Is "allow for" a correct verbal phrase here? (https://en.wiktionary.org/wiki/allow_for vs https://en.wiktionary.org/wiki/allow vs https://www.merriam-webster.com/dictionary/allow)?

2023-06-30 13:07 UTC, sauliusg commented on optimade.rst
> +IUCr (2005). International Tables for Crystallography vol. A. Space-Group Symmetry. Ed. Theo Hahn. 5-th edition. Dordrecht, Springer.
What is the sense of having spaces here? Does it render differently, or is it just "code beautification"?

2023-06-30 13:26 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
An important point of distinction: both pre-fraction and pos-fraction notation will result in *exactly* the same symmetry operation matrices; there is no reason to prefer one over the other; thus, it makes sense to leave them both.

This is in contrast to notations that add 1 to translations, for example `-x, -y, z+1/2` vs. `-x, -y, z+5/2`. These two strings will produce *different* matrices, and we will have to specify if they are equivalent and if yes, in what sense. Therefore, we forbid extra unit translations.

2023-06-30 13:38 UTC, rartino commented on optimade.rst
> +    However, the property is RECOMMENDED if fractional atom coordinates are returned in the response.
Wasn't the idea that the present PR should include all the fields described here: https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1274498513

This includes `asym_fractional_coords`, which should be the field on which the symmetry operators operate (and probably this field should be mentioned here explicitly).

The old PR that @merkys links to #206 is outdated and was a proposal to include the filled cell fractional coordinates. I think we've agreed we should not have them, only the `asym_fractional_coords`.

2023-06-30 13:43 UTC, rartino reviewed
Thanks for all the work put into this.

I guess we could merge multiple PRs in succession; but as far as I can see, this addition doesn't work on its own but also needs `asym_fractional_coords` and `asym_species_at_site` to be defined according to https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1274498513

2023-06-30 13:52 UTC, rartino commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
I think the point is that arbitrary spaces, "0.5", etc. are also describing exactly the same symmetry operations, but you have at least decided to canonicalize that far.

As may already be obvious from our discussions in #416, my vote is on the side of as much canonicalization as others are willing to accept. But (as I very much promised @sauliusg :-) ) I'm also happy with approving the PR with as free-text notation as he, and others, think is motivated.

2023-06-30 13:54 UTC, sauliusg commented
> Thanks for all the work put into this.
> 
> I guess we could merge multiple PRs in succession; but as far as I can see, this addition doesn't work on its own but also needs `asym_fractional_coords` and `asym_species_at_site` to be defined according to [#416 (comment)](https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1274498513)

IMHO the fractional coordinates and symmetry operations can be merged independently. The symmetry operation specification is essential for the fractional coordinate PR to be even composed correctly.

2023-06-30 13:55 UTC, sauliusg commented
> but as far as I can see, this addition doesn't work

Why not? The space group information and the symmetry are independent on any form of coordinate presentation.

2023-06-30 14:00 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
> I think the point is that arbitrary spaces, "0.5"

The 0.5 is not accepted because, if we accept that, it would be expected to accept also 0.333333333,  and these are not exact fractions. We then need to specify rounding rules, which wold be an overcomplication, and does not bring anything new or useful. So it is not the same as 'x+1/2' vs '1/2+x'.

2023-06-30 14:01 UTC, rartino commented on optimade.rst
> +space\_group\_symmetry\_operation\_xyz
Symmetry operation or symmetry operation**s**, since this is a list of symmetry operations? I guess the singular form is inspired by the CIF naming (`_space_group_symop_operation_xyz`), but that is a column name, where the CIF standard arguably names columns to specify what is in one cell of the "table".

```suggestion
space\_group\_symmetry\_operations\_xyz
```

2023-06-30 14:02 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
> ... arbitrary spaces ...

Arbitrary spaces are easy to exclude or include; we could allow them if you wish but that would make REs more complicated. Is it worth the game?

2023-06-30 14:07 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
> as much canonicalization as others are willing to accept

Too much canonicalization is counterproductive, IMHO, especially if it would force a database to parse their symops into matrices and then serialize again only to satisfy arbitrary standardization decisions (and the choice between 'x+1/2' and '1/2+x', if this is what the discussion is about, is arbitrary and not really necessary for anything).

The symops *SHOULD NOT* be searched and compared as strings; rather, different means should be used for searching and processing symmetries. I think we agreed that symops are not a searchable property, didn't we?

2023-06-30 14:09 UTC, rartino commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
Well, *I* want to exclude as much as possible, so no.

But, just to clarify; I understood @vaitkus's argument (which I agree with) that there is already a *some* degree of canonicalization going on in the proposed OPTIMADE definition in disallowing spaces and '0.5', which one needs to handle when translating the CIF field `_space_group_symop_operation_xyz`. Hence, it doesn't seem that big of a step to also canonicalize on either the prefix or appended notation.

(But, if you feel strongly for allowing this degree of freedom - and it seems you do - I'm OK with that.)

2023-06-30 14:13 UTC, sauliusg commented on optimade.rst
> +space\_group\_symmetry\_operation\_xyz
The IUCr dictionary uses singular, 'https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Ispace_group_symop_operation_xyz.html', and this is where the data name comes from. I wold stick to existing notation that is in wide use and wold not invent a new one.

The motivation for a singular in CIF is that the data item that is named in the data name has exactly one value, and these singular data items are further organized in a loop (or an array/list, if this is a JSON).

2023-06-30 14:21 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
> But, just to clarify; I understood @vaitkus's argument (which I agree with) that there is already a _some_ degree of canonicalization going on in the proposed OPTIMADE definition in disallowing spaces and '0.5', which one needs to handle when translating the CIF field `_space_group_symop_operation_xyz`. Hence, it doesn't seem that big of a step to also canonicalize on either the prefix or appended notation.

If you tell a crystallography (who implemented OPTIMADE) that 'x+1/2' is a correct symop and '1/2+x' is not, the crystallography will answer that you are wrong and you should go learn a bit of crystallography. And she/he will be right. If we instead start arguing that this is a standard which we set up a long while ago, the crystallographer will answer that he/she has better things to do than to get into idiosyncrasies of whatever standard whoever designed. And again he/she will be right. Why do we want to create problems on an even spot be preferring one equivalent representation over the other?

Can one give an example what exactly problem is solved by forbidding 'x+1/2' and requiring '1/2+x', or vice versa?

2023-06-30 14:25 UTC, sauliusg commented on optimade.rst
> +    $symop_re = "($symop_translation_appended|$symop_translation_prepended)";
Moreover, there are another such "non-canonicalities", like 'x+y' vs. 'y+x'. You do not want to force choice of these, do you?

2023-06-30 14:29 UTC, sauliusg commented on optimade.rst
> +  - **Query**: Support for queries on this property is not required and in fact is NOT RECOMMENDED.
Capitalization refers to RFC 2119, not to emphasis in this case (or at least I understand it like that).

2023-06-30 15:04 UTC, vaitkus commented on optimade.rst
> +IUCr (2005). International Tables for Crystallography vol. A. Space-Group Symmetry. Ed. Theo Hahn. 5-th edition. Dordrecht, Springer.
@sauliusg Spaces are required for the text to render properly (general level text vs. text under the "- **Bibliographic References for <...>" paragraph).

2023-06-30 15:58 UTC, sauliusg commented on optimade.rst
> +- **Description**: Space group number for the structure assigned by the International Tables for Crystallography Vol. A. (IUCr, 2005)
> "Space group number which specifies the space group of the structure as defined in the International Tables for Crystallography Vol. A. (IUCr, 2005)."

This is how it is written in the current revision, isn't it?

2023-06-30 16:09 UTC, vaitkus commented on optimade.rst
> +- **Description**: Space group number for the structure assigned by the International Tables for Crystallography Vol. A. (IUCr, 2005)
Yes. Probably the conversation was not resolved after making the change.

2023-06-30 16:55 UTC, sauliusg commented on optimade.rst
> +  - :val:`P 21 21 21`
I'll have to look at that. I have several lists of H-M symbols, but they are not authoritative. We'd need to cross-check them against the ITC, but this is, as I see at the moment, quite some (manual) work...

2023-06-30 17:44 UTC, ml-evs commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property allo
Yes, to me at least, "allows to" isn't correct unless you prefer "allows the user/client to"

2023-06-30 17:45 UTC, ml-evs commented on optimade.rst
> +  For describing arbitrary symmetries of molecules, non-periodic (finite) collections of atoms or non-crystallographic symmetry, a different property will be used.
Thirded!

2023-06-30 17:46 UTC, ml-evs commented on optimade.rst
> +  - :val:`P 21 21 21`
It's not a blocker for me, so only do it if you agree that it is useful. I can see myself making mistakes implementing this so an exhaustive list to validate against would be great

2023-07-03 06:51 UTC, rartino commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
space\_group\_symmetry\_operations\_xyz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-07-03 06:53 UTC, rartino requested changes

2023-07-03 06:53 UTC, rartino commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
space\_group\_symmetry\_operations\_xyz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-07-03 06:53 UTC, rartino commented on optimade.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
space\_group\_symbol\_hermann\_mauguin
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-07-03 06:57 UTC, rartino commented
Last web meeting we seemed to agree on that this PR is more or less finished, but to merge it, it needs some very brief statement that there currently is no standard way to communicate fractional coordinates for atoms in the asymmetric unit (despite the PR referring to that in a few places).

(Alternatively, the field definitions to do so could of course be added; the `asym_fractional_coords` and `asym_species_at_site` from https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1274498513 )

If the statement is added, the idea is obviously to merge `asym_fractional_coords` and `asym_species_at_site` shortly after and remove the statement.

2023-07-03 15:41 UTC, vaitkus commented on optimade.rst
> +- **Bibliographic References for the 'space\_group\_hall' definitions**
```suggestion
- **Bibliographic References for the 'space\_group\_symbol\_hall' definitions**
```

2023-07-03 15:42 UTC, merkys commented on optimade.rst
> +  The interpretation of the strings MUST follow the conventions of the IUCr CIF core dictionary (IUCr, 2023).
Yes, I am fine with this.

2023-07-03 15:43 UTC, vaitkus commented on optimade.rst
> +- **Bibliographic References for the 'space\_group\_Hall' definitions**
This very correct comment was not properly visible due to the "outdated" flag so I resuggested the same fix. Closing this.

2023-07-03 15:44 UTC, vaitkus commented on optimade.rst
> +  The same character string encoding conventions MUST be used as for the specification of the `space\_group\_symbol\_hermann\_mauguin`_ property.
```suggestion
  The same character string encoding conventions MUST be used as for the specification of the :property:`space\_group\_symbol\_hermann\_mauguin`_ property.
```

2023-07-03 15:45 UTC, vaitkus commented on optimade.rst
> +  The same character string encoding conventions MUST be used as for the specification of the `space\_group\_symbol\_hermann\_mauguin`_ property.
The same change was previously suggested by @merkys, but was no longer properly visible due to the "outdated" status.

2023-07-03 15:45 UTC, vaitkus commented on optimade.rst
> +  The same character string encoding conventions MUST be used as for the specification of the `space\_group\_symbol\_Hermann_Mauguin`_ property.
Resuggested the change for visibility.

2023-07-03 15:47 UTC, vaitkus commented on optimade.rst
> +  - **Query**: Support for queries on this property is not required and in fact is NOT RECOMMENDED.
I still do not think that the additional emphasis is needed, but I will mark this as resolved to move things forward.

2023-07-03 15:51 UTC, vaitkus commented on optimade.rst
> +space\_group\_symbol\_Hermann_Mauguin
The core issues seems to be resolved. @merkys, do you want to open a separate issue about the removal of the backslash escape characters (e.g. as a reminder)?

2023-07-04 06:48 UTC, merkys commented on optimade.rst
> +space\_group\_symbol\_Hermann_Mauguin
OK, I am marking this as resolved for now.

2023-09-28 14:48 UTC, sauliusg commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property allo
Fixed as discussed with M.E.

2023-09-28 16:04 UTC, sauliusg commented
> Last web meeting we seemed to agree on that this PR is more or less finished, but to merge it, it needs some very brief statement that there currently is no standard way to communicate fractional coordinates for atoms in the asymmetric unit (despite the PR referring to that in a few places).
> 
> (Alternatively, the field definitions to do so could of course be added; the `asym_fractional_coords` and `asym_species_at_site` from [#416 (comment)](https://github.com/Materials-Consortia/OPTIMADE/issues/416#issuecomment-1274498513) )
> 
> If the statement is added, the idea is obviously to merge `asym_fractional_coords` and `asym_species_at_site` shortly after and remove the statement.

Once more, I do not feel like adding "temporary" messages. Probably the better way is to make definition of symmetry operations independent of the fractional coordinate property.

I have attempted to rephrase conventions (requirements) for the symmetry operation property so that it specifies general conditions when this property SHOULD or MUST be provided (essentially, it SHOULD be provided whenever it is applicable, and MUST be provided when it is needed ;). The fractional coordinates are mentioned only as an example, or as a general crystallographic concept.

Actually, symmetry operations can also be applied to atoms when Cartesian coordinates are returned; in that case one needs to convert them to fractional coords (which is possible since the unit cell vectors are also provided), apply the symmetry operations and then convert back to Cartesian if needed.

Please have a look at the new version.

2023-09-28 16:23 UTC, vaitkus commented on optimade.rst
> +    Moreover, the property is REQUIRED symmetry operations are necessary to reconstruct the full model of the material no other symmetry information (e.g., the Hall symbol) is provided that would all
```suggestion
    Moreover, the property is REQUIRED if symmetry operations are necessary to reconstruct the full model of the material and no other symmetry information (e.g., the Hall symbol) is provided that would allow the user to derive symmetry operations unambiguously.
```

2023-09-28 17:04 UTC, vaitkus commented
@sauliusg Thank you for also accepting the earlier changes.

I would like to note, that during one of the earlier meetings it was agreed that the approvals from neither me, nor @merkys should count on this issue given that all three of us work on the COD project.

That being said, I do not think that moving the mention of fractional coordinates to an example helps, because we are still mentioning a property that is not currently supported. Also, I found the earlier phrasing more succinct and easier to understand -- now the reader if left to wonder what are those different coordinate forms to which the symmetry operations can be applied. In your earlier comment you mention Cartesian coordinates as one such case, but that would clash with other statements presented in this PR, e.g.:
```
The symmetry operations are to be applied to fractional atom coordinates.
```
Finally, if the new phrasing is accepted, the `can and must` part should probably be rewritten to use either "can" or "must", because in this situation "must" encompasses "can". I would probably go with "can".

2023-11-03 14:46 UTC, sauliusg commented
> I would like to note, that during one of the earlier meetings it was agreed that the approvals from neither me, nor @merkys should count on this issue given that all three of us work on the COD project.

Since in these cases we are voting neither on personalities nor on policy statements in which we could have vested interest, but instead we vote on *technical* issues, affiliation of voters with the COD or any other project is not relevant, IMHO. Since there does not seem to be many participants who would be deeply interested in symmetry description, your comments on technical issues would be highly appreciated. But of course anybody is free to decline if they feel that they have a conflict of interest here.

2023-11-03 15:21 UTC, vaitkus commented
@sauliusg wrote:

> I cannot find the place where I mention application of symmetry operations to Cartesian coordinates; that would be also incorrect. Could you please give me the exact location of the text that you cite?

I was referring to part of the comment from (https://github.com/Materials-Consortia/OPTIMADE/pull/464#issuecomment-1739617585):
> Actually, symmetry operations can also be applied to atoms when Cartesian coordinates are returned; in that case one needs to convert them to fractional coords (which is possible since the unit cell vectors are also provided), apply the symmetry operations and then convert back to Cartesian if needed.

But this has now been addressed with an additional sentence in the PR.

> I disagree. The symops as given can be applied to fractional coordinates. They must be applied if fractional coordinates are given for the AU only and the user wants to reconstruct the full unit cell. Both cases are relevant.

Then it should be "which these operations can or must be applied" instead of "which these operations can and must be applied" ("and" -> "or").

2023-11-03 15:24 UTC, sauliusg commented
> > Actually, symmetry operations can also be applied to atoms when Cartesian coordinates are returned; in that case one needs to convert them to fractional coords (which is possible since the unit cell vectors are also provided), apply the symmetry operations and then convert back to Cartesian if needed.
> 
> But this has now been addressed with an additional sentence in the PR.

OK, so this is hopefully resolved now.

> > I disagree. The symops as given can be applied to fractional coordinates. They must be applied if fractional coordinates are given for the AU only and the user wants to reconstruct the full unit cell. Both cases are relevant.
> 
> Then it should be "which these operations can or must be applied" instead of "which these operations can and must be applied" ("and" -> "or").

Good suggestion, thanks, I will apply it!

2023-11-03 15:25 UTC, vaitkus commented on optimade.rst
> +  In case only Cartesian coordinates are available, these Cartesian coordinates must be converted to fractional coordinates before application of the provided symmetry operations.
```suggestion
  In case only Cartesian coordinates are available, these Cartesian coordinates must be converted to fractional coordinates before the application of the provided symmetry operations.
```

2023-11-03 15:29 UTC, vaitkus commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property prov
Is `reconstruct every symmetry of the periodic material` correct? Maybe there is a noun missing after "symmetry".

Not a blocking issue, feel free to ignore if the usage is correct.

2023-11-03 15:44 UTC, sauliusg commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property prov
> Is `reconstruct every symmetry of the periodic material` correct? Maybe there is a noun missing after "symmetry".
> 
> Not a blocking issue, feel free to ignore if the usage is correct.

I'm not quite sure what I though back when I wrote this sentence :), but how I read it now is the following: the -x,-y,z+1/2 together with the lattice translations allow us to infer crystal symmetry operations like -x+1,y+1,z-1/2 and so on, in general, all operations of the sort -x+p,-y+q,z+1/2+r, where p,q,r ∈ ℤ.

We could write "provides all information necessary to reconstruct every symmetry equivalent atom of the periodic material", this would be probably more clear but too narrow since symmetry operations are applied not only to atoms but to all objects and (abstract Euclidean space) points in the crystal... Shall we sacrifice completes to hopefully get clarity?

2023-11-03 15:54 UTC, vaitkus commented on optimade.rst
> +- **Notes** The list of space group symmetry operations applies to the whole periodic array of atoms and together with the lattice translations given in the :property:`lattice\_vectors` property prov
My vote is for clarity. :)

2023-12-19 13:39 UTC, rartino reviewed
Comments during meeting.

2023-12-19 13:39 UTC, rartino commented on optimade.rst
> +  The H-M symbols SHOULD be given as specified in the International Tables for Crystallography vol. A (IUCr, 2005), Table 4.3.2.1.
```suggestion
  The H-M symbols SHOULD be given using the short format used in the International Tables for Crystallography vol. A (IUCr, 2005), Table 4.3.2.1 as described in the accompanying text.
  The symbol MAY be a non-standard short H-M symbol.
  The H-M symbol does not unambiguously communicate the axis and origin choice, and the given symbol SHOULD NOT be amended to convey this information.
```

2023-12-19 14:10 UTC, rartino reviewed
One more edit from meeting.

2023-12-19 14:10 UTC, rartino commented on optimade.rst
> +  The change-of-basis operation SHOULD be provided for unusual settings and cell choices.
```suggestion
  The change-of-basis operation SHOULD be provided for the non-standard axis and cell choices.
  The extended H-M symbol does not unambiguously communicate the origin choice, and the given symbol SHOULD NOT be amended to convey this information.
```

2023-12-19 14:28 UTC, ml-evs approved these changes
Looks great to me, thanks for the hard work!

2023-12-19 14:30 UTC, merged

2023-12-20 10:49 UTC, blokhin commented
Let me also add a direct link to the CIF dictionary mentioned. Also I’d like to check, if the ops non-symbolic notation is discouraged (e.g. `x+0.6666667` should be `x+2/3`).

2024-01-12 15:19 UTC, vaitkus commented
@blokhin wrote:
> Let me also add a direct link to the CIF dictionary mentioned. Also I’d like to check, if the ops non-symbolic notation is discouraged (e.g. `x+0.6666667` should be `x+2/3`).

A link to the `CIF_CORE` dictionary is provided under the `space_group_symmetry_operations_xyz`  section as:

https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Ispace_group_symop_operation_xyz.html

The non-symbolic notation is not allowed at all by the regular expression, that is, `x+2/3` is allowed, `x+0.6666667` is not allowed.