Add `type` and `id` to the entry info endpoints
Materials-Consortia/OPTIMADE pull request #472
Opened 2023-06-13 13:03 UTC by ml-evs

Partially addresses #470, in a manner suitable for 1.2 (i.e., without backwards-incompatible changes). It seemed there was consensus in #470 that this is a bug (well, there was a thumbs up and a positive comment), and I think simply adding `type` and `id` fixes it for most use cases (i.e., downloading and storing an `/info/entry_type` endpoint whilst retaining the entry's identity).

I have added a future deprecation warning, as it seems clear to me at least that OPTIMADE v2 will just follow the JSON:API format for this, though I don't see any benefit in supporting both in v1.2.

2023-06-13 13:06 UTC, merkys commented on optimade.rst
> +    **Note**: Future versions of the OPTIMADE API will deprecate this behavior and
The lines do not seem to be folded anywhere in the specification.

2023-06-13 13:09 UTC, merkys commented on optimade.rst
>  - **properties**: A dictionary describing properties for this entry type, where each key is a property name and the value is an OPTIMADE Property Definition described in detail in the section `Proper
It is probably not too late to move at least `properties` inside `attributes`, but not sure which is worse, having inconsistency or forwards-incompatible structure.

2023-06-13 13:13 UTC, merkys requested changes
Thanks for the PR @ml-evs, I am happy with the way it fixes the incompatibility with JSON:API and says how it should be addressed in the future. Line folding should be undone, as it does not seem to happen anywhere else in the document.

2023-06-13 13:19 UTC, ml-evs commented on optimade.rst
> +    **Note**: Future versions of the OPTIMADE API will deprecate this behavior and
The example I found was under `original\_name`, it gets rendered as a note, see bottom of this definition https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#species

2023-06-13 13:19 UTC, ml-evs commented on optimade.rst
>  - **properties**: A dictionary describing properties for this entry type, where each key is a property name and the value is an OPTIMADE Property Definition described in detail in the section `Proper
I think I am strongly in favour of leaving it where it is for now, otherwise e.g., my client will break and queries to `v1` URLs will require some additional logic

2023-06-13 13:20 UTC, ml-evs commented on optimade.rst
>  - **properties**: A dictionary describing properties for this entry type, where each key is a property name and the value is an OPTIMADE Property Definition described in detail in the section `Proper
So I'd rather just resolve the inconsistency with JSON:API (which we're not completely beholden to anyway) in a later version

2023-06-13 13:25 UTC, merkys commented on optimade.rst
> +    **Note**: Future versions of the OPTIMADE API will deprecate this behavior and
Right, but lines are not folded there.

2023-06-14 10:12 UTC, merkys submitted a review, later dismissed

2023-06-14 12:01 UTC, vaitkus commented on optimade.rst
> +    :field:`attributes` key.
```suggestion
    **Note**: Future versions of the OPTIMADE API will deprecate this behavior and require all keys that are not :field:`type` or :field:`id` to be under the :field:`attributes` key.
```

2023-06-14 12:01 UTC, vaitkus commented on optimade.rst
> +    initial context of the request.
```suggestion
    At this point, :field:`type` and :field:`id` will be made mandatory to allow the :endpoint:`/info/<entry-type>` endpoints to be understood outside the initial context of the request.
```

2023-06-14 15:49 UTC, ml-evs commented on optimade.rst
> +    **Note**: Future versions of the OPTIMADE API will deprecate this behavior and
Ah I see what you mean now (thanks to @vaitkus's suggestions), I think I wouldcall that wrapping rather than folding. I'll fix it and request re-review

2023-06-14 16:11 UTC, vaitkus approved these changes

2023-06-15 00:47 UTC, rartino commented on optimade.rst
> +The response for these endpoints SHOULD also include the following information in the :field:`data` field:
Should we consider "MUST" here? This is a rather minor thing to add to implementations, and the response is *very* JSON API non-compliant without them; and we say higher up that we are JSON API compliant, and that any discrepancies means that the implementation still should (try?) to adhere to the JSON API specification...

2023-06-15 05:23 UTC, merkys commented on optimade.rst
>  - **properties**: A dictionary describing properties for this entry type, where each key is a property name and the value is an OPTIMADE Property Definition described in detail in the section `Proper
Right, this makes sense. Marking as resolved.

2023-06-15 05:25 UTC, merkys commented on optimade.rst
> +    **Note**: Future versions of the OPTIMADE API will deprecate this behavior and
Oh right. It must be the name of command line tool `fold` which affected my calling of this concept :smile:

2023-06-15 05:31 UTC, merkys commented on optimade.rst
> +The response for these endpoints SHOULD also include the following information in the :field:`data` field:
Might be a good idea to do so. This does not break the backwards compatibility for clients, right?

2023-06-15 05:31 UTC, merkys approved these changes

2023-06-15 06:20 UTC, rartino commented on optimade.rst
> +The response for these endpoints SHOULD also include the following information in the :field:`data` field:
@merkys No, not as described at the top of the specification - i.e., the client shouldn't break on unrecognized fields. And implementations should be prepared to implement new forced features (that don't break old clients) if they want to advance versions.

2023-06-17 12:03 UTC, ml-evs commented on optimade.rst
> +The response for these endpoints SHOULD also include the following information in the :field:`data` field:
Fair point, just added this and tweaked the deprecation note.

2023-06-19 07:54 UTC, merkys approved these changes
All good as before, just needs a merge from `develop`.

2023-06-19 08:10 UTC, ml-evs commented
Yes, we're stuck in a bit of a re review loop here, as we get closer to the release I think I will start using admin powers to merge in trivial cases like this.

2023-06-19 08:13 UTC, merged