Small corrections for metadata and partial data
Materials-Consortia/OPTIMADE pull request #480
Opened 2023-06-26 08:54 UTC by JPBergsma

I still have some small corrections for the metadata PR #463  and partial data PR #467

2023-06-26 09:09 UTC, merkys commented on optimade.rst
> +However, when an implementation supports the :field:`property_metadata` field, it SHOULD include metadata fields for all fields, present in the data part of the response, which have metadata.
```suggestion
However, when an implementation supports the :field:`property_metadata` field, it SHOULD include metadata fields for all properties, present in the data part of the response, which have metadata.
```
I however prefer the variant without introduced commas.

2023-06-26 09:10 UTC, merkys commented on optimade.rst
>    - **partial_data_links**: an object used to list links which can be used to fetch data that has been omitted from the :field:`data` part of the response.
```suggestion
  - **partial_data_links**: a dictionary used to list links which can be used to fetch data that has been omitted from the :field:`data` part of the response.
```

2023-06-26 09:11 UTC, merkys commented on optimade.rst
> +    Each value is a list of objects that MUST have the following keys:
```suggestion
    Each value is a list of dictionaries that MUST have the following keys:
```
Elsewhere in the specification we use "list of dictionaries"

2023-06-26 09:13 UTC, merkys commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
```suggestion
- :field:`"returned_ranges"`: list of dictionaries.
```

2023-06-26 12:27 UTC, JPBergsma commented on optimade.rst
> +However, when an implementation supports the :field:`property_metadata` field, it SHOULD include metadata fields for all fields, present in the data part of the response, which have metadata.
Do you mean you would prefer if I only change has to have ?
```suggestion
However, when an implementation supports the :field:`property_metadata` field, it SHOULD include metadata fields for all fields present in the data part of the response which have metadata.
```
Without the commas, I get the impression that which refers to response rather than fields.

How about:
```suggestion
However, when an implementation supports the :field:`property_metadata` field, it SHOULD include metadata fields for all properties which have metadata and are present in the data part of the response.
```

2023-06-26 12:43 UTC, JPBergsma commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
I think we should still add capitalization as on line 2079.
```suggestion
- :field:`"returned_ranges"`: List of Dictionaries.
```

2023-06-26 12:55 UTC, merkys commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
I must have confused OPTIMADE types with JSON types, apologies. I now see that
> Note: since the below definition references both JSON fields and OPTIMADE properties, the data type names depend on context: for JSON they are, e.g., "array" and "object" and for OPTIMADE properties they are, e.
g., "list" and "dictionary".

Thus here and above the JSON data types should have been given instead of OPTIMADE. I think this is confusing, but distinction should remain. It makes sense to talk in JSON terms when defining OPTIMADE JSON lines format.

I see that capitalization in this section of specification prefers initial capital letter, thus my suggestions for capitalization are inconsistent with the rest of this section. Sorry again.

2023-06-26 12:58 UTC, JPBergsma commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
Ok than I'll reverse your suggestions.

2023-06-26 12:58 UTC, merkys commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
Right, thank you.

2023-06-28 14:26 UTC, JPBergsma commented on optimade.rst
> +  - :field:`"version"`: String.
We already used the field name "format" in section 3.10 Transmission of large property values. So I do not think we should use it here again with a different meaning.

2023-08-04 19:20 UTC, vaitkus commented on optimade.rst
>      Specifies the minor version of the partial data format used. The string MUST be of the format "MAJOR.MINOR", referring to the version of the OPTIMADE standard that describes the format. The versi
```suggestion
    Specifies the minor version of the partial data format used.
    The string MUST be of the format "MAJOR.MINOR", referring to the version of the OPTIMADE standard that describes the format.
    The version number string MUST NOT be prefixed by, e.g., "v". In implementations of the present version of the standard, the value MUST be exactly :val:`1.2`.
```

2023-08-07 07:42 UTC, rartino commented on optimade.rst
> +  - :field:`"version"`: String.
Good catch - it is indeed potentially confusing that these two fields are named the same. However, the use of "format" here reflects the same fieldname in the property definitions, and the design idea is the same: future versions of OPTIMADE may want to make this field more expressive than simply the OPTIMADE version (which is why the next line of the text says how to handle if the string cannot be parsed as a version number). For this, I still think "format" is the best name.

So, can we change the other "format" instead? I find it a bit tricky to come up with a good name. How about "protocol"? "data_protocol"?

2023-08-07 07:55 UTC, rartino commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
Commenting on the original proposed change: I see the specification currently is not consistent whether type declarations like these of lists/arrays should use plural or singular. E.g. in section "8.6.1. species" the type is "list of dictionary". Whereas in "8.2.15 species_at_sites" it is "list of strings".

My personal preference (which perhaps comes a bit from a programmer-first perspective) is to not mess around with pluralization in a declarative statement like this, just use the type name as we have defined it. So, for the above IMO it should be "Array of Object". However, in the bulk text where one uses full sentences I would write, e.g., "The value should be an array of objects". But I don't feel very strongly either way, so if no one backs me up on this view, I'm OK approving this change.

2023-08-07 08:00 UTC, rartino requested changes
Thanks for making these fixes. The only thing I think needs to be handled before merging this is to agree what to do with the double "format" fields where - as you can see below - I don't agree with changing the name of the field embedded in the data. (But if others chime in and agree with plurals in the type declaration, I suggest that be reverted too).

2023-08-07 12:22 UTC, JPBergsma commented on optimade.rst
> +  - :field:`"version"`: String.
I have changed "version" back into "format".
I will change the format field in section 3.10 into "file_format" as that seems to be what it describes in the example.
Protocol is more general than file format, so it would probably be better to use that for a method to share larger data items in a manner that is very different from the current partial data format.

2023-08-07 12:25 UTC, vaitkus commented on optimade.rst
> +  - :field:`"version"`: String.
What about "data_format" as an alternative name for the property in Section 3.10? This term is already used in the human-readable portion of the specification, e.g. `<...> The default partial data format is named "jsonlines" and is described <...>`?

However, I also find the name "format" in the current context a little bit unintuitive (makes me think about file formats and data types instead of version-like strings). Maybe something like "format_version" would also be viable? (I understand that it might be too late to change it due to "format" already being used in property definitions).

2023-08-07 12:50 UTC, rartino commented on optimade.rst
> +  - :field:`"version"`: String.
You are right that the naming may not be perfect here, and since we haven't released any of this yet, it isn't too late to change if we can find something that is consistently better. It may require a 'find + sed' through the not-yet-merged property definition source files, but that is not so much work.

`data_format` seems more accurate than `file_format`, but I think the other "format" field name in that case also needs a qualifier (which is why I tried to get rid of "format" completely, e.g., "protocol"). 

But, at some level I wonder if these things describing "what is the format of this thing" shouldn't just be the same? The structured way to go would be that `format` is a dictionary with a `name` and a `version`, potentially with the `version` part optional. However, `version` is in that case also not the ideal name for that subfield, since we want to chop off the patch part.

2023-08-07 14:01 UTC, JPBergsma commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
I have undone this change. It would probably be best to open a new issue to discuss this for the optimade specification as a whole.

2023-08-07 14:07 UTC, rartino commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
Yes, please open an issue. It also concerns the auto-generated documentation pages from the property definitions published under schema.optimade.org. (Right now the human-readable pages only presents the outermost type, but that should be fixed and use whatever we think is right.)

2023-08-08 12:01 UTC, JPBergsma commented on optimade.rst
> +  - :field:`"version"`: String.
I think that the format consists of two parts.

1. The part we define in Optimade, i.e. the names and definitions of the fields and how these are arranged in data structures

2. The container format, i.e. how data types and data structures are stored in a file / response.

The current format field under “partial_data_links” is most similar to the container format, so we should perhaps rename that field to “container_format”.
Elsewhere, we have however also used the term “response_format” so that is also an option. 

The “format” field that we supply in the partial data response mostly corresponds with point 1.
It is meant to describe which version of the optimade specification was used to construct the partial data response. At the moment this field gives the optimade version but not which protocol was used.

Now, we have only one way of returning large data items, so it is not necessary to specify that the partial data protocol is used. If in the future we, however, come up with more methods to return data, it could be useful to have a field specifying the used method. So I think it would be better to keep the version number and the used method separate, like @rartino already suggested. 
> The structured way to go would be that format is a dictionary with a name and a version

I am also not happy with “property-format” as a field name in the property definitions. As it describes the version of the definition of the property and not how the property is formatted.

`data_format` sound a bit vague to me, so I do not like that name.

2023-08-21 09:07 UTC, JPBergsma commented on optimade.rst
> +- :field:`"returned_ranges"`: Array of Objects.
I have created Issue #483 to discuss this further.

2023-12-19 13:49 UTC, ml-evs approved these changes

2023-12-19 13:49 UTC, rartino approved these changes
Looks good to me, but we need to figure out in a separate PR what to do with the double use of 'format'.

2023-12-19 13:49 UTC, merged