Adding the `dimension_slices` query parameter and associated metadata
Materials-Consortia/OPTiMaDe pull request #481
Opened 2023-06-29 15:01 UTC by JPBergsma

This PR introduces the ability for a client to request a specific subset, or "slice", of items from list properties. This is primarily achieved through the addition of a new query parameter, `dimension_slices`, and associated metadata fields to describe slicing capabilities and reflect the requested slices in the response.
Note this new feature is distinct from the existing protocol for large property values (see #467 and follow-up PRs), as slicing is initiated by the client, not the server. This means that even when slicing is requested by the client, the server can still decide whether to return the whole data in line, or via the partial data protocol.

### 1. `dimension_slices` query parameter
- **Purpose**: Request only specific parts of list properties.
- **Syntax**: `dimension_slices=dim_xxx[start:stop:step],...`
  - The slice defaults are as follows: start=0, step=1, stop=null (meaning upto the last value in the list).
  - Note that, at variance with Python, stop is inclusive.

### 2. Metadata enhancements in the response
A new `list_axes` list of dictionaries describing each list dimension. Each dict must contain `dimension_name` (required).
Optional keys: `length`, `sliceable` (bool), `available_slice` (index range), `requested_slice` (returned in `list_axes` for each sliced property, reflecting the exact slice requested).

### 3. Shared dimensions
- A slice on a dimension name applies to all properties that use that same name.

**Result:** Clients can fetch only needed portions of list data, with servers clearly describing slicing capabilities and confirming applied slices in the response.

Note that it surpersedes the original  proposal #452.

2023-06-29 22:00 UTC, vaitkus commented on optimade.rst
> +Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format. It communicates that the property value has been omitted from the response and incl
```suggestion
Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format.
It communicates that the property value has been omitted from the response and includes three different links for different partial data formats provided and metadata that makes it possible to request only a part of the data for this property.
```

2023-06-30 14:41 UTC, rartino commented
Thanks for writing this up!

Why did you move the whole section "Transmission of large property values"? It makes it tricky to see what has changed. Can you move it back?

Also, my interpretation of the workshop discussions was to make the `property_ranges` query parameter completely separate from, and orthogonal to, the mechanism for "Transmission of large property values" (this was a strong point of @sauliusg). Hence, it isn't clear to me why anything has to change in the "Transmission of large property values". Why can't we keep all documentation about this feature in the definition of the `property_ranges` query parameter?

2023-06-30 14:49 UTC, JPBergsma commented
It seemed more logical to place the metadata section before the "Transmission of large property values" section, as the "Transmission of large property values" section depends on the metadata section but not the other way round. So it is more useful to read the metadata section before the "Transmission of large property values" section.

2023-08-21 10:10 UTC, JPBergsma commented on optimade.rst
> +Transmission of large property values
To clarify why I moved this section:

The section "Transmission of large property values" uses features from the section "Metadata properties". But the section "Metadata properties" does not depend on the section "Transmission of large property values" so I therefore placed the "Transmission of large property values" after the "Metadata properties" section.

I have made two small changes in the "Transmission of large property values" section:

Line 534 I replaced "one of alternative partial data formats " to  "one of the partial data formats". 
As I do not think the word alternative adds anything here.
Line 537: I broke the sentence into two parts and replaced "from the response, with three different links" with "from the response and includes three different links"

2023-12-19 18:39 UTC, ml-evs requested changes
Mostly formatting changes and suggesting rewordings -- I think I can go through and force most of them in if there are no objections

2023-12-19 18:39 UTC, ml-evs commented on optimade.rst
> +      This means that the energy at index x(in the dimension labelled by this range_id) belongs to the cartesian_site_positions at the same index x.
```suggestion
      This means that the energy at index *x* (in the dimension labelled by this `range_id`) belongs to the `cartesian_site_positions` at the same index *x*.
```

2024-01-09 14:30 UTC, rartino commented
This PR appears a bit stalled and is important. @JPBergsma do you plan to continue working on this, or are you ok with me (or someone else) starting to merge changes into it?

2024-01-17 13:43 UTC, rartino commented on optimade.rst
> +      This means that the energy at index x(in the dimension labelled by this range_id) belongs to the cartesian_site_positions at the same index x.
This is duplicated with the property definition PR #445, note that there the names are called "dimension names"
```suggestion
```

2024-01-17 13:44 UTC, rartino commented
This PR makes a number of references to "range_ids", which is not the term used in the property definition PR #445. This needs to be adjusted.

2024-01-18 12:48 UTC, vaitkus commented on optimade.rst
> +  Databases MUST use these ranges for properties where the dimension is listed under :field:`indexable_dimensions`, if this is not the case, the database MAY return more data than was specified in th
```suggestion
  Databases MUST use these ranges for properties where the dimension is listed under :field:`indexable_dim`, if this is not the case, the database MAY return more data than was specified in the range.
```

2024-01-18 12:48 UTC, vaitkus commented on optimade.rst
> +  For dense arrays that may mean that the field :field:`returned_range` differs from the requested range.
```suggestion
  For dense arrays that may mean that the field :field:`returned_ranges` differs from the requested range.
```

2024-01-18 12:48 UTC, vaitkus commented on optimade.rst
> +  For dense arrays that may mean that the field :field:`returned_range` differs from the requested range.
I assume the `returned_ranges` is meant here as `returned_range` does not seem to be currently defined.

2024-03-22 07:45 UTC, merkys commented on optimade.rst
> +  If one or more values are not present at one of the requested combination of indexes, the server MAY either decide to return null or if possible adjust the returned range so the indexes for which n
```suggestion
  If one or more values are not present at one of the requested combination of indexes, the server MAY either decide to return :val:`null` or if possible adjust the returned range so the indexes for which no value is defined are no longer part of the range.
```

2024-03-22 07:47 UTC, merkys commented on optimade.rst
> +  The slices are 0-based, i.e. the first value has index 0, and inclusive i.e. for the range :val:`:10:20:1` the last value returned belongs to index 20.
Shouldn't this be `dim:10:20:1`? I suggest explicitly naming the example dimension for clarity.

2024-03-22 08:17 UTC, merkys commented on optimade.rst
> +  The latter is only allowed when no defined values would be lost.
```suggestion
  The latter is only allowed when no defined values would be omitted.
```
Maybe "omitted" fits here better than "lost"?

2024-03-22 08:25 UTC, merkys commented on optimade.rst
> +      The outermost dimension of a nested array should come first.
```suggestion
      The outermost dimension of a nested array MUST come first.
```
I think making this a MUST would make it easier to use both for client and server.

2024-03-22 08:26 UTC, merkys commented on optimade.rst
> +      If, within one entry, dimensions for two or more properties share the same :field:`range_id` those dimensions should be thought of as the same dimension.
```suggestion
      If, within one entry, dimensions for two or more properties share the same :field:`range_id` those dimensions should be treated as the same dimension.
```

2024-03-22 08:27 UTC, merkys commented on optimade.rst
> +      For example, if both the :property:`energy` and :property:`cartesian_site_positions` of a molecular dynamics trajectory share a range_id of :val:`frames`.
```suggestion
      For example, both the :property:`energy` and :property:`cartesian_site_positions` of a molecular dynamics trajectory may share a range_id of :val:`frames`.
```

2024-03-22 11:47 UTC, rartino commented on optimade.rst
> +  The slices are 0-based, i.e. the first value has index 0, and inclusive i.e. for the range :val:`:10:20:1` the last value returned belongs to index 20.
```suggestion
  The slices are 0-based, i.e. the first value has index 0, and inclusive i.e. for the dimension :val:`dim` the range :val:`dim:10:20:1` the last value returned belongs to index 20.
```

2024-03-22 11:53 UTC, rartino commented on optimade.rst
> +      This means that the energy at index x(in the dimension labelled by this range_id) belongs to the cartesian_site_positions at the same index x.
This was fixed in https://github.com/Materials-Consortia/OPTIMADE/pull/481/commits/f2a27996c2e6eb59258385f5716265a9e78624c4

2024-06-13 05:21 UTC, rartino commented on optimade.rst
> +      The outermost dimension of a nested array should come first.
This is outdated: it was handed in the property definitions PR (that used a completely different formulation that means the same thing).

2024-06-13 05:22 UTC, rartino commented on optimade.rst
> +      If, within one entry, dimensions for two or more properties share the same :field:`range_id` those dimensions should be thought of as the same dimension.
Outdated: right now the text already says "represents the same dimension".

2024-06-13 05:24 UTC, rartino commented on optimade.rst
> +      For example, if both the :property:`energy` and :property:`cartesian_site_positions` of a molecular dynamics trajectory share a range_id of :val:`frames`.
Outdated: this must have been edited after this suggestion, since the sentence now continues "this means ..." which doesn't make it easy to apply this suggestion. On the other hand, we probably will edit this anyway.

2024-06-14 08:27 UTC, rartino commented
This PR should probably be squashed when merged.

2024-06-14 09:19 UTC, giovannipizzi commented
We pushed the last changes discussed during the in-person review. The PR is ready for re-review by all. 

One note that is still open to discussion.

The current range specification looks like: `dim_frames:3:7:2`.

While this is formally clear, using the same `:` separator between dimension name and slice components, and within the slice part, might be confusing to the human eye (e.g. compare `dim_frames:5::`, `dim_frames::5:` and `dim_frames:::5`).

Ideally, if we find a better separator, it would be great.

A possible alternative: `dim_frames[3:7:2]`.
(Note that for the extension of #528 this is not a problem, in the sense that we could find a different symbol to specify the axis index, e.g., `cartesian_site_positions(0)[3:7:2]`).

My feeling is that this makes it much easier to see at a glance the difference between `dim_frames[5::]`, `dim_frames[:5:]` and `dim_frames[::5]`.

2024-06-14 10:45 UTC, vaitkus reviewed
Looks good overall, just a few minor typos.

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format for a request to the trajectory endpoint with the query parameter :query-param:`prop
```suggestion
Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format for a request to the trajectory endpoint with the query parameter :query-param:`property_slices=dim_frames:3:37:5` and :query-param:`response_fields=cartesian_site_positions,_exmpl_temperature` where the trajectory consists of 432934 frames (with indexes 0 to 432933) and where the :field:`cartesian_site_positions` contains 7 sites. Furthermore, the :field:`_exmpl_temperature` contains only :val:`null` values except for items with indexes 1000, 1030, 1060, ..., 4000 (where the values can be either numeric or :val:`null`).
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +    This query URL requests items from the array :field:`cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of the fir
```suggestion
    This query URL requests items from the array :field:`cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of the first 1000 frames (i.e., taking steps of 10 over indexes 0 through 999 inclusive, which requests the frames with indexes 0, 10, 20, 30, ..., 990) of a trajectory with ID :val:`id_12345`.
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +    Dimension names defined by database or definition providers MUST be prefixed by the corresponding database or namespace prefix, and SHOULD also be prefixed with ``dim_``, e.g., ``_exmpl_dim_parti
```suggestion
    Dimension names defined by database or definition providers MUST be prefixed by the corresponding database or namespace prefix, and SHOULD also be prefixed by ``dim_``, e.g., ``_exmpl_dim_particles``.
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +                   "length": 432934,
```suggestion
                   "length": 432934
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +                   "length": 7,
```suggestion
                   "length": 7
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +                   "length": 3,
```suggestion
                   "length": 3
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +                   "length": 432934,
```suggestion
                   "length": 432934
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +               ],
```suggestion
               ]
```

2024-06-14 10:45 UTC, vaitkus commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise it MUST be omitted or equal
It was not immediately clear to me whether the "it" refers to the `property_slices` parameter or to the `requested_slices` field (on a second read I assume the latter). I would suggest rewording this sentence.

2024-06-14 12:27 UTC, rartino commented
On the topic of separators: The business with url-safe characters is complicated. I note that according to [RFC3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) both bracket parentheses and colons are in the same category, "gen-delims", which I think is generally worse in terms of having to be escaped in practice compared to the characters in "sub-delims" (and in particular the unreserved characters listed right below the linked segment, which are always safe). However, very particular for bracket parentheses, apparently chrome and Firefox had decided to violate the standard and generally do not encode those characters out of 'tradition'.

2024-06-14 22:03 UTC, merkys submitted a review, later dismissed
Looks good, I left only some minor comments.

2024-06-15 13:23 UTC, rartino commented on optimade.rst
> +Slices of array properties
You are right, good catch. Array should almost everywhere be replaced by list. Array should only be kept when we explicitly refer to JSON:API output arrays.

2024-06-15 13:24 UTC, rartino commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise it MUST be omitted or equal
```suggestion
  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise the key MUST be omitted or equal to :val:`null`:
```

2024-06-15 13:30 UTC, rartino commented on optimade.rst
> +    For example, let us consider the property :property:`cartesian_site_positions` of the trajectory entry, where the first dimension name is :val:`dim_frames`.
Right, but, this refers to the `trajectory` entry type, and it was decided as we were writing this PR up that it was OK to use trajectory examples even though that endpoint isn't in the specification yet. 

However, you have an excellent point in that we shouldn't name the field in trajectories, which also has an extent in `dim_frames`, exactly the same name as the field in structures, which does not have that.

@giovannipizzi, @gmrigna, @sauliusg What should the list of `cartesian_site_coordinates` be named? Maybe: `frame_cartesian_site_coordinates`?

2024-06-15 14:09 UTC, rartino commented on optimade.rst
> +Slices of array properties
After thinking about this, I don't find a good way to handle this without defining the term 'array' to be a general word for a list or a structure of nested lists. (IMO "Multidimensional lists" is far worse as a term.) So, I've pushed a commit that does this.

2024-06-15 14:19 UTC, rartino commented on optimade.rst
> +    For example, let us consider the property :property:`cartesian_site_positions` of the trajectory entry, where the first dimension name is :val:`dim_frames`.
I've fixed this by renaming the field in the examples to `frame_cartesian_site_positions`.

2024-06-15 14:38 UTC, rartino commented on optimade.rst
> +Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format for a request to the trajectory endpoint with the query parameter :query-param:`prop
I've split the line and somewhat rephrased that last sentence. Please see if it is more clear now.

(What you read as a contradiction is intentional, but hopefully it is more clear now.)

2024-06-21 09:12 UTC, vaitkus commented on optimade.rst
> +  The query parameter contains a comma-separated (",", ASCII 44(0x2C)) list of slice specifications.
```suggestion
  The query parameter contains a comma-separated (",", ASCII symbol 44 dec, 0x2C hex) list of slice specifications.
```

2024-06-21 09:12 UTC, vaitkus commented on optimade.rst
> +  Each slice specification consists of an ordered sequence of four elements separated by the colon character (":", ASCII 58(0x3A)).
```suggestion
  Each slice specification consists of an ordered sequence of four elements separated by the colon character (":", ASCII symbol 58 dec, 0x3A hex).
```

2024-07-04 07:18 UTC, giovannipizzi commented on optimade.rst
> +  The default is the last index of the array along the specified dimension.
```suggestion
  The default is :val:`null`, which represents the last index of the array along the specified dimension.
```

2024-07-04 07:24 UTC, giovannipizzi commented
In view of Monday's online meeting where we need to discuss this, it would be great if we can get a last check and, if all is OK, approvals.

The only remaining things are:
- a comment between @rartino and @merkys but it seems to me that the current state is probably OK?
- the discussion on the syntax `dim_xxx:start:stop:step` vs `dim_xxx[start:stop:step]` or similar. I still think the second is easier to read, but I'm OK to keep the currently suggested version only with `:` if nobody else feels strongly about it

2024-08-28 15:52 UTC, ndaelman-hu reviewed
Hey! In anticipation of the upcoming meeting, here is the promised review.

Mostly just questions for clarification, or me pointing out where the phrasing may be somewhat dense for those less familiar with OPTIMADE.

From the NOMAD perspective, my main question would be "whether array dimensions MAY also just be integers (served as strings)?"
We are also working on a system for adding (named) variables, so some dimensions may be dynamic. I don't think this conflicts with the specificatiosn per se, but I'd have to consult my coworkers about the implementation.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +  - :field:`requested_slice`: Dictionary.
So, these are very different modes of querying. Typically, a client will have to query them in separate stages.

1. I'd think it would be good to explicitely state this, either between this and specification above, or at the very beginning of the enumeration.
2. Fun edge case: which response should a server provide when both fields are used in a query? Kind of silly, but I could see clients make this mistake.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +Slices of array properties
I'll leave it up to somebody more experienced in the protocol to resolve this.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +    The implementation MUST preserve the values as given in the query parameter, including the distinction between specific values and default values even when they are equivalent.
This one was kinda though to get on the first read. Maybe refer to the example below.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +        But it is instead a valid representation if the query parameter was :query-string:`property_slices=dim_frames:0::`.
I think this would be clearer when presented as 2 bulletpoints in the format _query: response_.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +    By including this field, the server certifies that there are only :val:`null` values outside this slice.
> the server certifies that [...]

Can I interpret this as a MUST? If so, I would put the stronger specifier before the weaker MAY.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +One additional query parameter :query-param:`property_slices` MUST be handled by the API implementation either as defined below or by returning the error :http-error:`501 Not Implemented`:
I get the impression from the `develop` branch that the use of HTTP errors is new in this PR.
While in-line with many standards, it'll increase the burden of response handling on the client's side.

Probably, HTTP errors merrit their own section. Questions that come to mind include for example:
Is there any specication about the message body? Is the server obliged to specify why it returned the 501?

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +  The default is the last index of the array along the specified dimension.
It's actually already explaiend that `:val:null` refers to the default value, and that it should be returned unless a specified value was used.
From how I understood it, the same applies to the `start` and `step` keys too.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +  The default is the last index of the array along the specified dimension.
Are inverse indices, e.g. -1 for last, -2 for penultimate, also supported?

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +  An empty value of the :query-param:`property_slices` query parameter MUST be interpreted as equivalent to the query parameter not being included in the request.
Is this then equivalent to `property_ranges=[<first_dim>:::, ...]`?
I.e. should this return the full property or leave it out?

This might be defined somewhere else. If so, pls refer to that section.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +    This query URL requests items from the array :field:`frame_cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of t
Minor style changes to make the phrase clearer:

1. Split the phrase up by both attributes.
2. Align the order of the example with the explanation, i.e. concerning `dim_frames` and `dim_sites`.
3. Just reiterate the 0-indexing convention after "the 31st to 71st sites". Apart from that, it's a great refresher.
4. `the frames with indexes 0, 10, 20, 30, ..., 990` explains it enough. The paranteses else become too verbose.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +    Dimension names defined by database or definition providers MUST be prefixed by the corresponding database or namespace prefix, and SHOULD also be prefixed by ``dim_``, e.g., ``_exmpl_dim_particl
> SHOULD also be prefixed by ``dim_``

Would that still be a prefix? Maybe, "extended by the `dim_` qualifier"?

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +- **property\_slices**: A number of slice specifications to request only parts of array properties for the functionality described in `Slices of array properties`_.
May the client request multiple (different) slices from the same array axis in the same query?
E.g. ```property_slices=[dim_frames:3:37:5,dim_frames:49:105:2]```

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +- **property\_slices**: A number of slice specifications to request only parts of array properties for the functionality described in `Slices of array properties`_.
This is clarified in "REQUIRED keys". A link suffices then.

2024-08-28 15:52 UTC, ndaelman-hu commented on optimade.rst
> +    If there is another one-dimensional (i.e., with a single axis) array property :property:`_exmpl_energy` of the same trajectory entry that specifies in its property definition the same dimension n
Her, you lost me

2024-09-06 15:47 UTC, giovannipizzi commented
As a follow-up on [my comment](https://github.com/Materials-Consortia/OPTIMADE/pull/481#issuecomment-2167614128), the decision in today's online meeting is to go for the syntax `dim_xxx[start:stop:step]`

2024-09-25 17:21 UTC, ndaelman-hu commented
Coming back to last meeting's discussion about the slicing, I'd like to explain my question further via an example.

In NOMAD, we have a tree-like schema with data at the nodes. That data may have any tensor rank, i.e. scalar, vector, matrix, etc. and slicing it is very sensible. However, our schema is being extended to be more dynamic and easier tailor.

Consequentially, we foresee that rank may vary. Consider for example a property, like `forces`, sliceable along the constituent atoms or spatial axes (e.g. `x`, `y`, `z`). Any entry can extend that definition's rank by adding independent variables, e.g. `forces(time)`. A client could now, in principle, also slice along the `time` dimension. The table below lists various examples of independent variables and the full rank:

```
dependent variable | rank dependent variable | independent variables | rank independent variables | full rank
--|--|--|--|--
forces | 2 | time | 1 | 3
forces | 2 | temperature | 1 | 3
forces | 2 | electric field | 2 | 4
forces | 2 | strain | 3 | 5
```

At a database-wide level, we can only ensure a minimum set of dimensionalities for `forces`, i.e. the force vector over each atom. Additional, entry-specific dimensions could at best only be returned after a query has filtered down the data. Does this limitation conflict with "query parameter :query-param:`property_slices` for metadata"?

Lastly, while I named the dimensions here, most of them only bear integers in practice (at least the dependent ones). Would integers (represented as strings) also be fine to identify dimensions, or is that semantically too vague?

2024-10-18 09:27 UTC, rartino commented on optimade.rst
> +The OPTIMADE standard defines a way for a client to request only a subset of the items of an array, referred to as a slice.
This isn't something we do elsewhere in the standard so I don't think it belongs in this PR. However, please bring this up at the web meet, and if agreed it is a good general idea for when we define terms in the specification, I'd be happy to review a PR where someone does this consistently throughout the document.

2024-10-18 10:23 UTC, rartino commented on optimade.rst
> +The protocol for this functionality allows the server to allow slicing independently per entry, per array, and per array axis.
```suggestion
The protocol for this functionality specifies how a server MAY support slicing arrays independently per entry, per array, and per array axis.
```

2024-10-18 10:24 UTC, rartino commented on optimade.rst
> +This functionality is separate from the protocol described in `Transmission of large property values`_.
```suggestion
This functionality is separate from (but compatible with) the protocol described in `Transmission of large property values`_.
```

2024-10-18 10:31 UTC, rartino commented on optimade.rst
> +In contrast, the protocol for large property values is used by the server implementation to transmit a set of items that it deems too large to provide inside the normal OPTIMADE response.
```suggestion
The protocol for large property values is used by the server implementation to transmit a set of items that it deems too large to provide inside the normal OPTIMADE response.
Slices, on the other hand, are used for a client to request a subset of items of an array, which still may result in such a large amount of values that the protocol for large property values has to be used to transmit them.
```

2024-10-18 10:38 UTC, rartino commented on optimade.rst
> +Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using metadata property field :field:`array_axes` (see `Metadata proper
I'm not sure what you mean here, can you use the GitHub suggest edit feature to show a suggestion? (Also, the discussion of terminology with regards to indices and axes may have been clarified by a discussion we had last web meet?)

2024-10-18 10:42 UTC, rartino commented on optimade.rst
> +  A list of dictionaries which provide information related to the axes of an array property, which is relevant for slicing.
But the information about which axes are slice-able isn't the only information that these dictionaries provide? Maybe:

```suggestion
  A list of dictionaries which provide information related to the axes of an array property, which includes which of the axes are sliceable.
```

2024-10-18 10:46 UTC, rartino commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise the key MUST be omitted or
There is a bit of redundancy, but we want the lists  to be complete and self-contained in the sense of specifying what members are required or not, so I don't see an easy way to remove this minor redundancy.

2024-10-18 12:11 UTC, rartino commented on optimade.rst
> +        But it is instead a valid representation if the query parameter was :query-string:`property_slices=dim_frames:0::`.
I think we need a suggested edit here to understand the format you are after.

2024-10-18 12:14 UTC, rartino commented on optimade.rst
> +    By including this field, the server certifies that there are only :val:`null` values outside this slice.
```suggestion
    This field describes a `slice object`_.
    By including this field, the server certifies that there MUST only be :val:`null` values outside this slice.
    Inside the slice there MAY be any combination of null and non-null values.
```

2024-10-18 12:17 UTC, rartino commented on optimade.rst
> +One additional query parameter :query-param:`property_slices` MUST be handled by the API implementation either as defined below or by returning the error :http-error:`501 Not Implemented`:
No?... Specific HTTP errors are mentioned at least as far back as 1.0. So, I don't think this discussion belongs in this PR, but can be posted as an issue and possibly in the future a general cleanup of the references to HTTP errors.

2024-10-18 12:19 UTC, rartino commented on optimade.rst
> +- **property\_slices**: A number of slice specifications to request only parts of array properties for the functionality described in `Slices of array properties`_.
In the present version (which may have changed since you commented) I think this information is quite clear in the text right below.

2024-10-18 12:19 UTC, rartino commented on optimade.rst
> +  The default is the last index of the array along the specified dimension.
Since they are not defined, no. They could be supported in the future.

2024-10-18 12:45 UTC, rartino commented on optimade.rst
> +  An empty value of the :query-param:`property_slices` query parameter MUST be interpreted as equivalent to the query parameter not being included in the request.
The query parameter not being included means the client isn't trying to use this protocol; so I think the natural interpretation is that "everything works as usual without the slices protocol". I guess that could be clarified somewhere, but I'm not sure exactly where.

2024-10-18 12:56 UTC, rartino commented on optimade.rst
> +    This query URL requests items from the array :field:`frame_cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of t
I think this addresses @ndaelman-hu suggestions, except for removing the explanation in the last parenthesis, which from our discussions on the workshop I do think still is necessary to be completely clear. 

```suggestion
  - :query-url:`http://optimade.example.com/v1/trajectories/id_12345?response_fields=frame_cartesian_site_positions&property_ranges=dim_sites:30:70:,dim_frames::999:10`

    This query URL requests items from the trajectory with ID :val:`id_12345`.
    It requests items from the array :field:`frame_cartesian_site_positions` for this trajectory.
    The items that are requested are for only the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of the first 1000 frames (i.e., taking steps of 10 over indexes 0 through 999 inclusive, which requests the frames with indexes 0, 10, 20, 30, ..., 990).
```

2024-10-18 12:57 UTC, rartino commented on optimade.rst
> +    Dimension names defined by database or definition providers MUST be prefixed by the corresponding database or namespace prefix, and SHOULD also be prefixed by ``dim_``, e.g., ``_exmpl_dim_particl
```suggestion
    Dimension names defined by database or definition providers MUST be prefixed by the corresponding database or namespace prefix, which SHOULD then be immediately followed by ``dim_``, e.g., ``_exmpl_dim_particles``.
```

2024-10-18 13:14 UTC, rartino commented on optimade.rst
> +    If there is another one-dimensional (i.e., with a single axis) array property :property:`_exmpl_energy` of the same trajectory entry that specifies in its property definition the same dimension n
@ndaelman-hu is this more clear?:
```suggestion
    Let the trajectory entry in this example have another, one-dimensional, array property :property:`_exmpl_energy`, which in its property definition specifies *the same name*, :val:`dim_frames`, as the name of the axis corresponding to its single dimension.
    The joint dimension name means the values of :property:`_exmpl_energy` and of :property:`frame_cartesian_site_positions` at index *i* pertain to the same frame.
    If slicing is used to request only parts of the data along the :val:`dim_frames` dimension, that is a request to slice both the properties according to the specified slice.
```

2024-10-18 13:33 UTC, ndaelman-hu commented on optimade.rst
> +In contrast, the protocol for large property values is used by the server implementation to transmit a set of items that it deems too large to provide inside the normal OPTIMADE response.
I like this better, yes. Given that only _large_ has a meaning, it's better to remove small, as you did.
2 minor suggestions:
1. `The protocol for large property values`: can this refer to the relevant section?
2. If we decide on using some kind of highlighting (as brought up above), I'd mark _server_ and _client_. I think it's a good short-hand for navigating the protocol.

2024-10-18 13:37 UTC, ndaelman-hu commented on optimade.rst
> +  A list of dictionaries which provide information related to the axes of an array property, which is relevant for slicing.
Sure, if that's more appropriate. Would avoid the triply nested _which_, though:

```suggestion
A list of dictionaries which provide information related to the axes of an array property, including sliceable axes.
```

2024-10-18 13:45 UTC, rartino commented
I have now updated the PR to reflect the syntax `dim_xxx[start:stop:step]`.

I have also tried to somehow address all outstanding comments of @ndaelman-hu. It would be great if you can:

* "thumb up" any edit suggestions that matches your intent
* counter-suggest edits if my suggested edit do not match your intent.
* press 'resolve' on any conversations where I replied without an edit where you think the matter is resolved.
* reply in any conversation where you think the matter is not resolved.

Finally, as a reply to this:

> At a database-wide level, we can only ensure a minimum set of dimensionalities for forces, i.e. the force vector over each atom. Additional, entry-specific dimensions could at best only be returned after a query has filtered down the data. Does this limitation conflict with "query parameter :query-param:property_slices for metadata"?

Just to make sure I understand: do you mean that according to the new schemas of NOMAD:

* There exist a concept "force". 

* The NOMAD schemas say "a force is an array of at least 3xN spatial dimensions, e.g., force = [3.2 , 4.2, 6.4], [6.2, 3.6, 6.2] for a two-atom system (in units of, e.g., E_h/a0, which you also specify somehow). 
 
* However, at any time when I (as a client) get a force from NOMAD, it may instead be an array of dimension, e.g., 3 x N x 2064, or even 3 x N x 2064 x 160, or 3 x N x 160 x 2064, where the force is resolved along a new 'dimension' such as time and (just to add something) trajectory_set_index (to index 160 trajectory sets).

* Presumably, I can get information about what these dimensions are and which order they come, however, NOMAD do not already assign these different options different names, they are all 'force'?

Because then the answer is that you cannot today represent this kind of freedom as a single OPTIMADE property definition. A single property has to have a fixed dimensionality. However, if you are OK with dynamically assigning alternative names to the different options, you can translate your data representation to that of OPTIMADE. 

Lets for the moment disregard that if your example with forces vs time is actually the atomic forces in a trajectory, we will already have a specific standard field for that; lets instead just discuss these as if they were completely custom NOMAD properties.

What you would do is provide a set of force property definitions:

* If your `force` is a 3 x N array, then you define `_nomad_force` defined via an OPTIMADE property definition to be a two-dimensional array with the dimension names `dim_spatial` and `dim_sites`.
* If your `force` is a 3 x N x 2064 array with forces for 2064 times, you'd call it `force_per_time` and define it via an OPTIMADE property definition to be a three-dimensional array with the dimension names `dim_spatial`, `dim_sites`, and `_nomad_dim_time`.
* and so on...

> Lastly, while I named the dimensions here, most of them only bear integers in practice (at least the dependent ones). Would integers (represented as strings) also be fine to identify dimensions, or is that semantically too vague?

In the OPTIMADE property definitions, a dimension name is a string. There is nothing preventing you from generating OPTIMADE dimension names from your numbers, e.g., `_nomad_dim_force_3` as the dimension name of the third axis of your `force` property.

2024-10-18 14:04 UTC, ndaelman-hu commented on optimade.rst
> +Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using metadata property field :field:`array_axes` (see `Metadata proper
> (Also, the discussion of terminology with regards to indices and axes may have been clarified by a discussion we had last web meet?)

I'd need a refresher there, sorry.

2024-10-18 14:07 UTC, ndaelman-hu commented on optimade.rst
> +Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using metadata property field :field:`array_axes` (see `Metadata proper
```suggestion
Information relating to the ability of the server to handle this query parameter. This MAY include the property field :field:`array_axes` (see `Metadata properties`_) to list the numerical indices of axes that may be sliced.
```

2024-10-18 14:11 UTC, sauliusg commented on optimade.rst
> +  Note that arrays are represented using lists and not as a separate data type.
In JSON? If we move to e.g. HDF5 then there the arrays will be a real distinct data type.

2024-10-18 14:12 UTC, ndaelman-hu commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise the key MUST be omitted or
Upon re-reading the paragraph above, it actually refers down. This is fine then.

2024-10-18 14:13 UTC, sauliusg commented on optimade.rst
> +  The specification uses **array** as a more general term for structures of nested lists representing single or multidimensional data, and the term **array axes** for the levels of nesting.
Would it make sense to require that a multidimensional array, as opposed to just a list of lists, MUST always have the same size for all sublists at the same dimension? I.e. a matrix (2D array) can be square or rectangular, but can not be triangle or arbitrarily ragged?

2024-10-18 14:24 UTC, ndaelman-hu commented on optimade.rst
> +  - :field:`requested_slice`: Dictionary.
With 2 query modes, I meant:
1. requesting metadata about the schema (explicitly demanding metadata on sliceable properties). This section explains the responses format.
2. actually querying for data, sliced to the desired format.

Perhaps mode 1 could be split into 1.1 (sliceable metadata implicit requested) and 1.2 (sliceable metadata explicitly requested).

Anyhow, I was just asking for a clearer distinction between which query mode is covered where. Subtitles could work?
Maybe I highlighted the wrong lines, but that would underscore my point.

Lastly, my 2nd question was about the responses when a query asks for both schema metadata and regular data.

2024-10-18 14:38 UTC, rartino commented on optimade.rst
> +In contrast, the protocol for large property values is used by the server implementation to transmit a set of items that it deems too large to provide inside the normal OPTIMADE response.
> The protocol for large property values: can this refer to the relevant section?

I realize that the way these comments chop up the text can make it a bit difficult to see the context, but the link you ask for is already right on the row before this line (numbered 616 right now).

2024-10-18 14:44 UTC, rartino commented on optimade.rst
> +Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using metadata property field :field:`array_axes` (see `Metadata proper
I'm confused, this doesn't read cleanly to me in the context it appears. The first sentence in the suggestion isn't even a complete sentence?

The context here is that we are in the general text at the top of the section trying to outline what this feature is and how it is used. The sentence right now is just trying to communicate that the metadata property array_axis is one of the essential mechanisms of the protocol.

2025-01-31 13:44 UTC, ndaelman-hu commented on optimade.rst
> +- **property\_slices**: A number of slice specifications to request only parts of array properties for the functionality described in `Slices of array properties`_.
Yes, I guess the question just popped up for me while reading this, while the response is much more below. But this is a minor point.

2025-01-31 14:40 UTC, ndaelman-hu commented on optimade.rst
> +    This query URL requests items from the array :field:`frame_cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of t
It's good like this, including the parentheses.

2025-01-31 15:05 UTC, ndaelman-hu commented on optimade.rst
> +      - ``{"start": 3, "stop": 5, "step": 2}``
```suggestion
    Examples:
    Query Type | Query Formulation | Valid Representations
    ----------------|---------------------------|------------------------------
    fully formed | :query-string:`property_slices=dim_frames:3:5:2` | ``{"start": 3, "stop": 5, "step": 2}``
    empty query with start | :query-string:`property_slices=dim_frames:0::` | ``{"start": 0}``
    empty query | :query-string:`property_slices=dim_frames:::` | ``{}``
                         |                                                                         | ``{"start": null, "stop": null, "step": null}``
                         |                                                                         | ``{"start": null}``
                         |                                                                         | ``{"stop": null, "step": null}``

   Note that any of the representations for the "empty query" are valid.
   Even though, semantically, it means the same as the "empty query with start" at index zero, both differ in representation.
```

2025-01-31 15:07 UTC, ndaelman-hu commented on optimade.rst
> +      - ``{"start": 3, "stop": 5, "step": 2}``
I went with a tabular lay-out, but if this is too unconventional, I can split it by paragraphs.
Note that I swapped the order, introducing the empty query after the one with the explicit starting index.

2025-01-31 15:09 UTC, ndaelman-hu commented on optimade.rst
> +        But it is instead a valid representation if the query parameter was :query-string:`property_slices=dim_frames:0::`.
Done

2025-01-31 15:16 UTC, ndaelman-hu commented on optimade.rst
> +  - :field:`requested_slice`: Dictionary.
I think I found the source of my confusion, let me add a suggested modification

2025-01-31 15:17 UTC, ndaelman-hu commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise the key MUST be omitted or
```suggestion
  If furthermore the request specifies any sliceable array axes, the following key MUST be present, otherwise the key MUST be omitted or equal to :val:`null`:
```

2025-01-31 15:19 UTC, ndaelman-hu commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise the key MUST be omitted or
It's confusing that you start listing mandatory fields, only to break up the list specifying the same query.
I understand now that this covers a subcase. I think this phrasing communicates that idea better.

2025-01-31 15:22 UTC, ndaelman-hu commented on optimade.rst
> +Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using metadata property field :field:`array_axes` (see `Metadata proper
```suggestion
Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using the metadata property field :field:`array_axes` (see `Metadata properties`_).
```

2025-09-15 15:10 UTC, rartino commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present, otherwise the key MUST be omitted or
```suggestion
  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present. However, if that query parameter is not specified, the key MUST either be omitted or set equal to :val:`null`:
```

2025-09-15 15:23 UTC, rartino commented on optimade.rst
> +  An empty value of the :query-param:`property_slices` query parameter MUST be interpreted as equivalent to the query parameter not being included in the request.
```suggestion
  An empty value of the :query-param:`property_slices` query parameter MUST be interpreted as equivalent to the query parameter not being included in the request.
As a consequence, the server will not slice any properties. 
```

2025-09-15 15:24 UTC, rartino commented on optimade.rst
> +  - :query-url:`http://optimade.example.com/v1/trajectories/id_12345?response_fields=frame_cartesian_site_positions&property_ranges=dim_frames::999:10,dim_sites:30:70:`
```suggestion
  - :query-url:`http://optimade.example.com/v1/trajectories/id_12345?response_fields=frame_cartesian_site_positions&property_slices=dim_frames::999:10,dim_sites:30:70:`
```

2025-09-15 15:27 UTC, rartino commented on optimade.rst
> +    This query URL requests items from the array :field:`frame_cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of t
Code review: @ndaelman-hu will suggest a rephrasing

2025-09-15 15:29 UTC, rartino commented on optimade.rst
> +  - :field:`requested_slice`: Dictionary.
Code review: @ndaelman-hu will suggest a change

2025-09-15 15:35 UTC, rartino commented on optimade.rst
> +    By including this field, the server certifies that there are only :val:`null` values outside this slice.
No: the indicated slice object MAY include only null values. The server makes no guarantee of that.

2025-09-15 15:43 UTC, rartino commented on optimade.rst
> +    This query URL requests items from the array :field:`frame_cartesian_site_positions` only for the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of t
```suggestion
    This query URL requests items from the trajectory with ID :val:`id_12345`.
    It requests items from the array :field:`frame_cartesian_site_positions` for this trajectory.
    The items that are requested are for only the 31st to 71st sites (i.e., with indexes 30 through 70 inclusive) for 1 out of every 10 frames of the first 1000 frames (i.e., taking steps of 10 over indexes 0 through 999 inclusive, which requests the frames with indexes 0, 10, 20, 30, ..., 990).
```

2025-09-16 07:28 UTC, ndaelman-hu commented on optimade.rst
> +  - :field:`requested_slice`: Dictionary.
Puzzling the convo back together again, I originally understood some fields to define metadata of query capabitilies as well as data. Those would be 2 types of queries that should be connected serially. I remember also discussing this at the last workshop.

Upon a fresh re-read, I understand these to ALL be metadata. I am adding a few targeted review comments that emphasize this interpretation.

2025-09-16 07:29 UTC, ndaelman-hu commented on optimade.rst
> +  A list of dictionaries which provide information related to the axes of an array property, including sliceable axes.
```suggestion
  A list of dictionaries which provide descriptive information related to the axes of an array property, including sliceable axes.
```

2025-09-16 07:32 UTC, ndaelman-hu commented on optimade.rst
> +    A field that describes the requested slice that was provided via the query parameter :query-param:`property_slices`.
```suggestion
    A metadata field that describes the requested slice that was provided via the query parameter :query-param:`property_slices`.
```

2025-09-16 07:33 UTC, ndaelman-hu commented on optimade.rst
> +    This field describes a `slice object`_.
```suggestion
    This metadata field describes a `slice object`_.
```

2025-09-16 13:58 UTC, ndaelman-hu commented on optimade.rst
> +The protocol for this functionality specifies how a server MAY support slicing arrays independently per entry, per array, and per array axis.
```suggestion
The protocol for this functionality specifies how a server MAY support slicing arrays independently per array axis.
```

2025-09-16 14:14 UTC, ndaelman-hu commented on optimade.rst
> +Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format for a request to the trajectory endpoint with the query parameter :query-param:`prop
```suggestion
Below follows an example of the :field:`data` and :field:`meta` parts of a response using the JSON response format for a request to the trajectory endpoint with the query parameter :query-param:`property_slices=dim_frames[3:37:5]` and :query-param:`response_fields=frame_cartesian_site_positions,_exmpl_temperature` where the trajectory consists of 432934 frames (with indexes 0 to 432933) and where the :field:`frame_cartesian_site_positions` contains 7 sites.
```

2025-09-17 09:11 UTC, gmrigna commented on optimade.rst
> +  The specification uses **array** as a more general term for structures of nested lists representing single or multidimensional data, and the term **array axes** for the levels of nesting.
```suggestion
  The term **list axes** refers to the levels of nesting.
```

2025-09-17 09:24 UTC, gmrigna commented on optimade.rst
> +  Note that arrays are represented using lists and not as a separate data type.
```suggestion
```

2025-09-17 09:25 UTC, gmrigna commented on optimade.rst
> +The OPTIMADE standard defines a way for a client to request only a subset of the items of an array, referred to as a slice.
```suggestion
The OPTIMADE standard defines a way for a client to request only a subset of the items of a list, referred to as a slice.
```

2025-09-17 09:25 UTC, gmrigna commented on optimade.rst
> +The protocol for this functionality specifies how a server MAY support slicing arrays independently per entry, per array, and per array axis.
```suggestion
The protocol for this functionality specifies how a server MAY support slicing lists independently per list axis.
```

2025-09-17 09:26 UTC, gmrigna commented on optimade.rst
> +Slices, on the other hand, are used for a client to request a subset of any size of the items of an array, which can possibly (but not necessarily) result in such a large amount of values that the pr
```suggestion
Slices, on the other hand, are used for a client to request a subset of any size of the items of a list, which can possibly (but not necessarily) result in such a large amount of values that the protocol for large property values is required to transmit them.
```

2025-09-17 09:27 UTC, gmrigna commented on optimade.rst
> +The field :field:`array_axes` is defined as follows:
```suggestion
The field :field:`list_axes` is defined as follows:
```

2025-09-17 09:27 UTC, gmrigna commented on optimade.rst
> +- :field:`array_axes`: List of Dictionary.
```suggestion
- :field:`list_axes`: List of Dictionary.
```

2025-09-17 09:28 UTC, gmrigna commented on optimade.rst
> +  A list of dictionaries which provide descriptive information related to the axes of an array property, including sliceable axes.
```suggestion
  A list of dictionaries which provide descriptive information related to the axes of a list property, including sliceable axes.
```

2025-09-17 09:28 UTC, gmrigna commented on optimade.rst
> +  Each item, in order, represents the array axis as declared in the corresponding property definition.
```suggestion
  Each item, in order, represents the list axis as declared in the corresponding property definition.
```

2025-09-17 09:29 UTC, gmrigna commented on optimade.rst
> +  If the request specifies the :query-param:`property_slices` query parameter for any of the array axes of this array property the following key MUST be present. However, if that query parameter is n
```suggestion
  If the request specifies the :query-param:`property_slices` query parameter for any of the list axes of this list property the following key MUST be present. However, if that query parameter is not specified, the key MUST either be omitted or set equal to :val:`null`:
```

2025-09-17 09:32 UTC, gmrigna commented on optimade.rst
> +Implementation of the :field:`meta` field is OPTIONAL, unless the server implements slicing, in which case it is MANDATORY (see `Slices of array properties`_).
```suggestion
Implementation of the :field:`meta` field is OPTIONAL, unless the server implements slicing, in which case it is MANDATORY (see `Slices of list properties`_).
```

2025-09-17 09:33 UTC, gmrigna commented on optimade.rst
> +Slices of array properties
```suggestion
Slices of list properties
```

2025-09-17 09:38 UTC, gmrigna commented on optimade.rst
> +Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using the metadata property field :field:`array_axes` (see `Metadata pr
```suggestion
Information relating to the ability of the server to handle this query parameter and the relevant ranges of indexes is provided using the metadata property field :field:`list_axes` (see `Metadata properties`_).
```

2025-09-17 09:38 UTC, gmrigna commented on optimade.rst
> +When the client request includes the query parameter :query-param:`property_slices`, the server MUST provide metadata for all properties for which including the subfield :field:`requested_slice` of t
```suggestion
When the client request includes the query parameter :query-param:`property_slices`, the server MUST provide metadata for all properties for which including the subfield :field:`requested_slice` of the :field:`list_axes` is MANDATORY (see below).
```

2025-09-17 09:40 UTC, gmrigna commented on optimade.rst
> +    The dimension name of the corresponding array axis.
```suggestion
    The dimension name of the corresponding list axis.
```

2025-09-17 09:45 UTC, gmrigna commented on optimade.rst
> +    The length of this array axis which MUST be the same as the length of the declared dimension for this axis in the corresponding property definition.
```suggestion
    The length of this list axis which MUST be the same as the length of the declared dimension for this axis in the corresponding property definition.
```

2025-09-17 09:46 UTC, gmrigna commented on optimade.rst
> +    If not provided, or equal to :val:`null` or an empty dictionary, the client cannot make any assumptions about what part of the array contains :val:`null` values.
```suggestion
    If not provided, or equal to :val:`null` or an empty dictionary, the client cannot make any assumptions about what part of the list contains :val:`null` values.
```

2025-09-17 09:47 UTC, gmrigna commented on optimade.rst
> +    - ``{"start": 3, "stop": 7, "step": 2}`` means the server certifies that values at indexes 0, 1, 2, 4, 6 and any index from 8 to the end of the array are :val:`null`.
```suggestion
    - ``{"start": 3, "stop": 7, "step": 2}`` means the server certifies that values at indexes 0, 1, 2, 4, 6 and any index from 8 to the end of the list are :val:`null`.
```

2025-09-17 09:48 UTC, gmrigna commented on optimade.rst
> +Furthermore, the metadata subfield :field:`available_slice` in :field:`array_axes` in :field:`_exmpl_temperature` certifies that all values of the data field :field:`_exmpl_temperature` are :val:`nul
```suggestion
Furthermore, the metadata subfield :field:`available_slice` in :field:`list_axes` in :field:`_exmpl_temperature` certifies that all values of the data field :field:`_exmpl_temperature` are :val:`null` except at indexes 1000, 1030, 1060, ..., 4000, where values can be either numeric or :val:`null`).
```

2025-09-17 09:49 UTC, gmrigna commented on optimade.rst
> +               "array_axes": [
```suggestion
               "list_axes": [
```

2025-09-17 09:49 UTC, gmrigna commented on optimade.rst
> +               "array_axes": [
```suggestion
               "list_axes": [
```

2025-09-17 09:50 UTC, gmrigna commented on optimade.rst
> +    Let the trajectory entry in this example have another, one-dimensional, array property :property:`_exmpl_energy`, which in its property definition specifies *the same name*, :val:`dim_frames`, as
```suggestion
    Let the trajectory entry in this example have another, one-dimensional, list property :property:`_exmpl_energy`, which in its property definition specifies *the same name*, :val:`dim_frames`, as the name of the axis corresponding to its single dimension.
```

2025-09-17 09:50 UTC, gmrigna commented on optimade.rst
> +    If, within one entry, two or more array axes in one or more properties share the same dimension :field:`name`, those represent the same dimension.
```suggestion
    If, within one entry, two or more list axes in one or more properties share the same dimension :field:`name`, those represent the same dimension.
```

2025-09-17 09:51 UTC, gmrigna commented on optimade.rst
> +    It requests items from the array :field:`frame_cartesian_site_positions` for this trajectory.
```suggestion
    It requests items from the list :field:`frame_cartesian_site_positions` for this trajectory.
```

2025-09-17 09:52 UTC, gmrigna commented on optimade.rst
> +  Requirements and conventions for the response when this query parameter is used are described in `Slices of array properties`_.
```suggestion
  Requirements and conventions for the response when this query parameter is used are described in `Slices of list properties`_.
```

2025-09-17 09:53 UTC, gmrigna commented on optimade.rst
> +- **property\_slices**: A number of slice specifications to request only parts of array properties for the functionality described in `Slices of array properties`_.
```suggestion
- **property\_slices**: A number of slice specifications to request only parts of list properties for the functionality described in `Slices of list properties`_.
```

2025-09-17 09:53 UTC, gmrigna commented on optimade.rst
> +  The default is :val:`null`, which represents the last index of the array along the specified dimension.
```suggestion
  The default is :val:`null`, which represents the last index of the list along the specified dimension.
```

2025-09-17 15:58 UTC, sauliusg reviewed
Comments from open discussion

2025-09-17 15:58 UTC, sauliusg commented on optimade.rst
Add client implementation note (reference section Metadata properties): to discover which properties have sliceable dimensions (and more generally the dimension names etc.), the client should add `property_metadata` in the `response_fields` query parameter together with the names of the fields we are interested to.

2025-09-17 15:58 UTC, sauliusg commented on optimade.rst
>  If the client includes the string ``property_metadata`` in the query parameter :query-param:`response_fields`, the server MUST include metadata fields for all properties which have metadata.
```suggestion
If the client includes the string ``property_metadata`` in the query parameter :query-param:`response_fields`, the server MUST include metadata fields for all properties which have metadata and are part of the response fields.
```

2025-09-17 15:58 UTC, sauliusg commented on optimade.rst
> +Implementation of the :field:`meta` field is OPTIONAL.
Revert the latest change.

2025-09-17 15:58 UTC, sauliusg commented on optimade.rst
>  Furthermore, if the server returns metadata for a property, it must be included in its entirety, i.e., including all non-null fields.
```suggestion
Furthermore, if the server returns metadata for a property, it MUST be included in its entirety, i.e., including all non-null fields.
```

2025-09-17 15:58 UTC, sauliusg commented on optimade.rst
> +    In particular, the field is MANDATORY if the client request includes the :query-param:`property_slices` query parameter for this list axis.
Replace everywhere `property_slices` with `dimension_slices`

2025-09-17 20:57 UTC, giovannipizzi commented on optimade.rst
> +    In particular, the field is MANDATORY if the client request includes the :query-param:`property_slices` query parameter for this list axis.
done

2025-09-17 20:57 UTC, giovannipizzi commented on optimade.rst
> +Implementation of the :field:`meta` field is OPTIONAL.
Done

2025-09-17 21:01 UTC, giovannipizzi commented on optimade.rst
done

2025-09-18 07:06 UTC, rartino commented on optimade.rst
> +  Multidimensional collections of items are represented as nested lists, and are still simply referred to as "lists" in this document.
The way I understood our discussion a **list** now has already be the multidimensional object. Hence, it seems contradictory/circular to first define it as an ordered one-dimensional collection, and then redefine it as a nested structure of itself. So, let me try this:

```
**list**: a collection of items composed as a structure of nested one dimensional ordered arrangements of items in such way that each item has a well-defined position given by N indices, and where all items are of the same type, unless they are unknown.
```

2025-09-18 07:15 UTC, rartino commented on optimade.rst
> +  However, the dimensionality of a list, defined as the number of axes (i.e., the number of levels of nesting) must be the same for all entries of a given entry type.
```suggestion
  The term **list axes** refers to the levels of nesting of a list.
  A list can have elements of different lengths along a given axis, i.e., the list does not need to be rectangular.
  However, the dimensionality of a list, defined as the number of axes (i.e., the number of levels of nesting) must be the same for all entries of a given entry type.
```

2025-09-18 07:45 UTC, rartino commented on optimade.rst
> +    - ``[1.0, null, 3.0]`` is a one-dimensional list of floats. The ``null`` value is valid as it represents an unknown value.
I'm missing the example:

```
[[1, 2], null, [3]]
```

It would be nice to settle clearly if this is valid or not (is it? I think it was but may no longer be with the requirements we put above...)

2025-09-18 08:23 UTC, rartino commented on optimade.rst
> +  Multidimensional collections of items are represented as nested lists, and are still simply referred to as "lists" in this document.
After discussion with @gmrigna, here is an arguably improved version:

```
**list**: a collection of items organized as nested ordered one-dimensional arrangements. All items are of the same type, unless unknown.
```

And then we edit the **list_axis** definition to speak about indexing.

2025-09-18 08:28 UTC, rartino commented on optimade.rst
> +  However, the dimensionality of a list, defined as the number of axes (i.e., the number of levels of nesting) must be the same for all entries of a given entry type.
In reference to the 2:nd version of the change above, this is an improved suggestion:

```suggestion
  The term **list axes** refers to the levels of nesting of a list.
  A list can have elements of different lengths along a given axis, i.e., the list does not need to be rectangular.
  However, the dimensionality of a list, defined as the number of axes (i.e., the number of levels of nesting) must be the same for all entries of a given entry type.
  Hence, each item in the list can be indexed by a number of indices equal to the dimensionality of the list.
```

2025-09-18 08:50 UTC, giovannipizzi commented on optimade.rst
> +  Multidimensional collections of items are represented as nested lists, and are still simply referred to as "lists" in this document.
Merged

2025-09-18 17:28 UTC, sauliusg commented on optimade.rst
> +    - ``[1.0, null, 3.0]`` is a one-dimensional list of floats. The ``null`` value is valid as it represents an unknown value.
An example that would be valid IMHO is:

```
[[1, 2], null, [3, 5]]

```

2025-09-18 22:35 UTC, rartino commented on optimade.rst
> +- **dictionary**: a collection of **key**-**value** pairs, where **keys** are pre-determined strings, i.e., for the same entry property the **keys** remain the same among different entries whereas th
```suggestion
- **list**: an ordered indexed collection of items that are either (i) all of the same basic type, (ii) only dictionaries, or (iii) only lists.
  In each case, (i)-(iii), unknown values (i.e., ``null``) are also allowed at any of the positions.
  Furthermore, a list can also be empty, i.e., contain no items.
  
  Multidimensional collections of items are represented as nested lists.
  This specification uses the term **list axes** to refer to the levels of nesting in nested lists, and **dimension** as the maximum number of axes represented via such nesting in a list and its sublists.
  A list can have elements of different lengths along a given axis, i.e., nested lists do **not** need to describe a rectangular arrangement of items.
  While this definition of the list type allows for complex structures of nested lists of varying depth, only those variants that can be expressed by OPTIMADE `Property definitions`_ are available for properties.

  Examples of valid lists:

    - ``[1.0, 2.0, 3.0]`` is a one-dimensional list of three floats (only one axis).

    - ``[]`` is a one-dimensional empty list.

    - ``[1.0, null, 3.0]`` is a one-dimensional list of floats. The ``null`` value is valid as it represents an unknown value.

    - ``[[1, 2], [3, 4], [5, 6]]`` is a two-dimensional list of three lists, each containing two integers. The first list axis has length 3 and the second list axis has length 2.

    - ``[[1, 2], [3, 4, 5], [6]]`` is a two-dimensional list of three lists, each containing a different number of integers, and each sublist has a different length.

    - ``[[1, 2], [null], [3]]`` and ``[[1, 2], [], [3]]`` are both valid two-dimensional lists, since all items can be indexed by two list indices.

    - ``[[1, 2], null, [3]]`` is valid since ``null`` can substitute items of any type, including sublists.

  Examples of invalid lists:

    - ``[3.0, "string"]`` is not a valid list, since the two elements have different types.
    
  Examples of lists that are valid, but cannot be used for properties in OPTIMADE due to limits imposed by OPTIMADE property definitions: 

    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists have different types.

    - ``[[1.0, 2.0], [[3.0], [4.0]], [5.0]]``: the second sublist contains nested lists, whereas the other two sublists do not, thus not allowing a consistent definition of the dimensions and axes of the list.

- **dictionary**: a collection of **key**-**value** pairs, where **keys** are pre-determined strings, i.e., for the same entry property the **keys** remain the same among different entries whereas the **values** change.
```

2025-09-18 23:06 UTC, rartino commented on optimade.rst
> +- **dictionary**: a collection of **key**-**value** pairs, where **keys** are pre-determined strings, i.e., for the same entry property the **keys** remain the same among different entries whereas th
I've gone through the rest of the PR, and if the above is committed, I'd be happy to approve the PR.

2025-09-19 05:06 UTC, giovannipizzi commented on optimade.rst
> +    It requests items from the list :field:`frame_cartesian_site_positions` for this trajectory.
```suggestion
  - :query-url:`http://optimade.example.com/v1/trajectories/id_12345?response_fields=cartesian_site_positions&dimension_slices=dim_frames[:999:10],dim_sites[30:70:]`

    This query URL requests items from the trajectory with ID :val:`id_12345`.
    It requests items from the list :field:`cartesian_site_positions` for this trajectory.
```

2025-09-19 05:20 UTC, giovannipizzi commented on optimade.rst
> +    The joint dimension name means the values of :property:`_exmpl_energy` and of :property:`frame_cartesian_site_positions` at index *i* pertain to the same frame.
```suggestion
    For example, let us consider the property :property:`cartesian_site_positions` of the trajectory entry, where the first dimension name is :val:`dim_frames`.
    Let the trajectory entry in this example have another, one-dimensional, list property :property:`_exmpl_energy`, which in its property definition specifies *the same name*, :val:`dim_frames`, as the name of the axis corresponding to its single dimension.
    The joint dimension name means the values of :property:`_exmpl_energy` and of :property:`cartesian_site_positions` at index *i* pertain to the same frame.
```

2025-09-19 05:45 UTC, giovannipizzi commented on optimade.rst
> +- **dictionary**: a collection of **key**-**value** pairs, where **keys** are pre-determined strings, i.e., for the same entry property the **keys** remain the same among different entries whereas th
I'm Ok with this change! I would just rewrite one of the lines as follows: 

  An empty list has a distinct meaning from ``null``: a list of no elements (...

I.e., move the "from null" part

2025-09-19 06:21 UTC, rartino commented on optimade.rst
> +    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists cannot w
```suggestion
    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists will not be able to be validated by the same item subschema in a Property definition.
```

2025-09-19 06:21 UTC, sauliusg commented on optimade.rst
> +  Furthermore, a list can also be empty, i.e., contain no items.
"Furthermore" seems superflous, I suggest removing it.

2025-09-19 06:25 UTC, sauliusg commented on optimade.rst
> +  An empty list has a distinct meaning from ``null``: a list of no items (see `Properties with an unknown value`_).
Suggest adding predicate:

"An empty list has a distinct meaning from ``null``, namely, it is a list with no items (see `Properties with an unknown value`_).
Comment"

2025-09-19 06:26 UTC, rartino approved these changes

2025-09-19 06:27 UTC, giovannipizzi approved these changes
I am very happy with this final version. If there are minor textual changes, feel free to apply and merge as if these are also approved by me!

2025-09-19 06:28 UTC, sauliusg commented on optimade.rst
> +    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists cannot w
Pls. remove either "cannot" or "will not be able"

2025-09-19 06:29 UTC, sauliusg commented on optimade.rst
> +    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists cannot w
Suggested text: "the two sublists cannot be validated by the same item subschema"

2025-09-19 06:30 UTC, sauliusg commented on optimade.rst
> +    - ``[[1.0, 2.0], [[3.0], [4.0]], [5.0]]``: the second sublist contains nested lists, whereas the other two sublists do not, thus not allowing a consistent definition of the dimensions and axes of
Maybe we add additional clarification: "as of OPTIMADE v1.2, such lists are excluded by Property definitions".

2025-09-19 06:48 UTC, sauliusg commented on optimade.rst
> +    If :val:`false`, the server MAY handle slices for that dimension, or MAY return the error :http-error:`501 Not Implemented` when a client requests a slice involving this dimension.
If a server is capable of handling slicing for a particular dimension, the server SHOULD indicate this by setting :field:`sliceable` to :val:`true` in its responses.

2025-09-19 06:50 UTC, sauliusg commented on optimade.rst
> +    If :val:`false`, the server MAY handle slices for that dimension, or MAY return the error :http-error:`501 Not Implemented` when a client requests a slice involving this dimension.
MAY server do anything else, e.g. silently ditching the slicing request?

Should we make it stricter:

"if a server cannot handle the slicing request, it MUST return the error :http-error:`501 Not Implemented`"

2025-09-19 07:29 UTC, rartino commented on optimade.rst
> +  Furthermore, a list can also be empty, i.e., contain no items.
```suggestion
  A list can also be empty, i.e., contain no items.
```

2025-09-19 07:32 UTC, rartino commented on optimade.rst
> +  An empty list has a distinct meaning from ``null``: a list of no items (see `Properties with an unknown value`_).
```suggestion
  An empty list has a distinct meaning from ``null``, namely, it is a list with no items (see `Properties with an unknown value`_).
```

2025-09-19 07:33 UTC, rartino commented on optimade.rst
> +    - ``[[1.0, 2.0], [[3.0], [4.0]], [5.0]]``: the second sublist contains nested lists, whereas the other two sublists do not, thus not allowing a consistent definition of the dimensions and axes of
```suggestion
    - ``[[1.0, 2.0], [[3.0], [4.0]], [5.0]]``: the second sublist contains nested lists, whereas the other two sublists do not, thus not allowing a consistent definition of the dimensions and axes of the list.
      As of OPTIMADE v1.2, such lists are excluded by Property definitions.
```

2025-09-19 07:39 UTC, rartino commented on optimade.rst
> +    If :val:`false`, the server MAY handle slices for that dimension, or MAY return the error :http-error:`501 Not Implemented` when a client requests a slice involving this dimension.
```suggestion
  - :field:`sliceable`: Boolean.
    If :val:`true`, the server MUST handle slices for that dimension.
    If :val:`false`, the server MAY handle slices for that dimension, but if it receives a slice request it cannot handle, it MUST return the error :http-error:`501 Not Implemented` when a client requests a slice involving this dimension.    
    If a server is capable of handling slicing for a particular dimension, the server SHOULD indicate this by setting :field:`sliceable` to :val:`true` in its responses.
```

2025-09-19 07:42 UTC, rartino commented on optimade.rst
> +    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists will not
```suggestion
    - ``[[1.0, 2.0], ["string", "string"]]``: while each of the two sublists is a valid list ([1.0, 2.0] is a list of floats, and ["string", "string"] is a list of strings), the two sublists cannot be validated by the same item subschema in a Property definition.
```

2025-09-19 07:42 UTC, rartino approved these changes

2025-09-19 07:45 UTC, sauliusg submitted a review, later dismissed

2025-09-19 07:49 UTC, rartino approved these changes

2025-09-19 07:52 UTC, sauliusg submitted a review, later dismissed

2025-09-19 07:53 UTC, d-beltran commented on optimade.rst
> +    - :field:`stop`: Non-negative integer or :val:`null`.
```suggestion
    - :field:`stop`: Non-negative integer equal or greater to the :field:`start` value or :val:`null`.
```

2025-09-19 07:53 UTC, d-beltran commented on optimade.rst
> +    - :field:`stop`: Non-negative integer or :val:`null`.
I suggest this change to avoid the possibility of requests with stop values lower than start values. This could be handled in different ways, including backwards values, which I think could make things more complicated.

2025-09-19 07:55 UTC, rartino approved these changes

2025-09-19 07:58 UTC, sauliusg approved these changes

2025-09-19 08:12 UTC, giovannipizzi approved these changes
Thanks, great work! Let's get it merged!

2025-09-19 08:14 UTC, merged