Minor typo and formatting fixes
Materials-Consortia/OPTIMADE pull request #486
Opened 2023-12-20 13:39 UTC by ml-evs

Just a few things that popped up whilst implementing the new symmetry operations.

I think it's better to rearrange the big block descriptions into the "Requirements/conventions" sections to follow how we do it with other fields (see the second commit here) but happy to roll that one back.

2024-01-02 12:59 UTC, merkys submitted a review, later dismissed
I support moving conventions under "Requirements/Conventions". Other changes are small, nevertheless appropriate.

2024-01-03 10:34 UTC, vaitkus requested changes

2024-01-03 10:34 UTC, vaitkus commented on optimade.rst
> +  - Space group operations for the space group with ITC number 3 (H-M symbol: `P 2`, extended H-M symbol: `P 1 2 1`, Hall symbol `P 2y`): :val:`["x,y,z", "-x,y,-z"]`
```suggestion
  - Space group operations for the space group with ITC number 3 (H-M symbol `P 2`, extended H-M symbol `P 1 2 1`, Hall symbol `P 2y`): :val:`["x,y,z", "-x,y,-z"]`
```

2024-01-03 10:34 UTC, vaitkus commented on optimade.rst
> +  - Space group operations for the space group with ITC number 5 (H-M symbol `C 2`, extended H-M symbol: `C 1 2 1`, Hall symbol `C 2y`): :val:`["x,y,z", "-x,y,-z", "x+1/2,y+1/2,z", "-x+1/2,y+1/2,-z"]
```suggestion
  - Space group operations for the space group with ITC number 5 (H-M symbol `C 2`, extended H-M symbol `C 1 2 1`, Hall symbol `C 2y`): :val:`["x,y,z", "-x,y,-z", "x+1/2,y+1/2,z", "-x+1/2,y+1/2,-z"]`
```

2024-01-04 10:23 UTC, merkys submitted a review, later dismissed

2024-01-04 10:51 UTC, vaitkus requested changes
I had an additional look at the rendered version of the file and the indentation of some lists seems a bit off (see marked suggestions).

2024-01-04 10:51 UTC, vaitkus commented on optimade.rst
>  - **Examples**:
```suggestion
- **Examples**:

```

2024-01-04 10:51 UTC, vaitkus commented on optimade.rst
>  - **Examples**:
Not sure if this fixes it, but currently both examples are displayed in a single paragraph without treating them as list items.

2024-01-04 10:51 UTC, vaitkus commented on optimade.rst
> +  - To encode as character strings, the following adaptations MUST be made when representing H-M symbols given in their typesetted form:
```suggestion
  - To encode as character strings, the following adaptations MUST be made when representing H-M symbols given in their typesetted form:

```

2024-01-04 10:51 UTC, vaitkus commented on optimade.rst
>    - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.
```suggestion
  - **Support**: OPTIONAL support in implementations, i.e., MAY be :val:`null`.

```

2024-01-04 10:51 UTC, vaitkus commented on optimade.rst
>      - MUST be :val:`null` if :property:`nperiodic_dimensions` is equal to 0.
In this section we place this requirement in the sublist of  "**Support**" while in  the `space_group_symbol_hall` section the same requirement is placed at the same indentation level as "**Support**" item. The same approach should probably be taken in both cases.

2024-01-04 11:11 UTC, ml-evs commented on optimade.rst
>  - **Examples**:
Thanks, think this should fix it (will go manually do it if not)

2024-01-04 11:17 UTC, ml-evs commented on optimade.rst
>      - MUST be :val:`null` if :property:`nperiodic_dimensions` is equal to 0.
I can't see where you are referring to (perhaps it was fixed in a previous suggestion) but all now looks good to me?

2024-01-04 11:35 UTC, merkys submitted a review, later dismissed

2024-01-04 11:51 UTC, vaitkus submitted a review, later dismissed
Looks good, feel free to ignore the two newly added nitpicky comments.

2024-01-04 11:51 UTC, vaitkus commented on optimade.rst
>      - MUST be :val:`null` if :property:`nperiodic_dimensions` is equal to 0.
What I meant is that here the statement is given on a different sublevel than the "Support":

- **Support**: <...>
  - <...>
  - MUST be :val:`null` if :property:`nperiodic_dimensions` <...>
  
while on line  2827 it is placed on the same level as support:

- **Support**: <...>
- **Query**: <...>
- <...>
- MUST be :val:`null` if :property:`nperiodic_dimensions` <...>

This might be intentional, though.

2024-01-04 11:51 UTC, vaitkus commented on optimade.rst
> +  - Space group operations for the space group with ITC number 5 (H-M symbol `C 2`, extended H-M symbol `C 1 2 1`, Hall symbol `C 2y`): :val:`["x,y,z", "-x,y,-z", "x+1/2,y+1/2,z", "-x+1/2,y+1/2,-z"]`
Just noticed that the surrounding backticks are not rendered in any special way. Maybe they could be replaced by single quotes (as in line 2866) or the "`:val:`" construct could be used to mke them stand out more.

2024-01-04 11:58 UTC, ml-evs commented on optimade.rst
>      - MUST be :val:`null` if :property:`nperiodic_dimensions` is equal to 0.
Ah I'm with you now, yes I agree with you. I'll make both of your changes and force the merge (to save everyone's time).

2024-01-04 12:03 UTC, ml-evs commented
Thanks @merkys and @vaitkus, hopefully this is the last request ;)

2024-01-04 12:04 UTC, merkys approved these changes

2024-01-04 12:07 UTC, vaitkus approved these changes
Thanks!

2024-01-04 12:09 UTC, merged

2024-01-05 16:11 UTC, rartino commented on optimade.rst
> +Symmetry operation strings that comprise the :property:`space\_group\_symmetry\_operations\_xyz` property MUST conform to the following regular expressions.
Is quoting underscores inside custom roles in rst necessary? This footnote leads me to think that it is not?: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#footnote-reference-3

2024-01-05 17:38 UTC, ml-evs commented on optimade.rst
> +Symmetry operation strings that comprise the :property:`space\_group\_symmetry\_operations\_xyz` property MUST conform to the following regular expressions.
The main fix here was the typo in the field name, perhaps I was over cautious with the `\`...