Add ECMA definition of symmetry operation regexp and associated tests
Materials-Consortia/OPTIMADE pull request #488
Opened 2023-12-23 12:40 UTC by ml-evs

Closes #487.

This PR adds an explicit and simplified symmetry operation regexp that can be used with JSON Schema.
It is validated against the same test cases as the PCRE version with an exact match in the results.

2023-12-23 12:44 UTC, ml-evs commented
Have tagged reviewers but no pressure to look at this before 2024!

2023-12-25 13:05 UTC, sauliusg requested changes
Looks good to me in principle. As details go, I suggest adding a test that compares the original PCRE REs and the ECMA REs, by generating automatically the ECMA RE from the PCRE by interpolating variables (should be easy to do in Perl) and comparing them with the ECMA RE provided in the specification. In this way we would know that if tests pass, both sets of REs define the same thing.

2023-12-25 13:05 UTC, sauliusg commented on optimade.rst
> +
What if we add a test that: a) takes the original PCRE definitions b) outputs the expanded PCRE (I guess it uses only ECMA-endorsed subset of the REs) and c) compares that with the ECMA RE provided in the OPTIMADE spec? In this way we would be *sure* that if tests pass, the two versions of the REs define the same thing.

2024-01-06 14:18 UTC, rartino commented on optimade.rst
> +- The regular expression is also provided in a simplified explicit form compatible with the subset of the `ECMA 262 dialect <https://ecma-international.org/publications-and-standards/standards/ecma-2
I propose to first merge #490 and then rewrite this sentence to refer to that appendix.

2024-01-10 09:42 UTC, rartino commented
I've added the 'requires-discussion' label in preparation of the web meet, as it seems we may want to generally find a consensus around the 'pattern' field. (I suppose I could have added the label on #490 instead, but technically it is the possible reference to that appendix from here that is the topic to discuss).

2024-01-12 13:08 UTC, sauliusg commented on optimade.rst
> +- The regular expression is also provided in a simplified explicit form compatible with the subset of the `ECMA 262 dialect <https://ecma-international.org/publications-and-standards/standards/ecma-2
I agree that we should proceed with merging and wording issues should not block it. The proposed consistency tests can be added later.

It just hurts me a bit to say "provided in a simplified ... for" when in fact it is more complicated :/ (but of course it depends on how one defines simplicity ;) ). I suggest remove the word "simplified", yielding " The regular expression is also provided in a explicit form compatible with the subset of the `ECMA ..." (and further according to the text), and merge.

2024-01-12 13:36 UTC, ml-evs commented on tests/cases/ecma_symops_001.sh
> +
Tests for new ECMA regexp

2024-01-12 13:36 UTC, ml-evs commented on optimade.rst
> +- The regular expression is also provided in a simplified explicit form compatible with the subset of the `ECMA 262 dialect <https://ecma-international.org/publications-and-standards/standards/ecma-2
Happy to change wording as you see fit, please just make a suggestion!

Re: the tests, they already exist and are passing (see https://github.com/Materials-Consortia/OPTIMADE/pull/488/files#r1450464273)

2024-01-12 13:36 UTC, ml-evs commented on optimade.rst
> +
See https://github.com/Materials-Consortia/OPTIMADE/pull/488/files#r1450464273; pretty much does what you want, beyond generating the regexp directly

2024-01-15 21:18 UTC, vaitkus commented on optimade.rst
> +
I think this PR (https://github.com/ml-evs/OPTIMADE/pull/1) should address Saulius' suggestion.

2024-01-17 13:23 UTC, rartino commented on optimade.rst
> +
This is now merged into this PR.

2024-01-17 13:27 UTC, ml-evs commented on optimade.rst
> +- The regular expression is also provided in a simplified explicit form compatible with the subset of the `ECMA 262 dialect <https://ecma-international.org/publications-and-standards/standards/ecma-2
```suggestion
- The regular expression is also provided in an expanded form:
```

2024-01-17 13:32 UTC, ml-evs commented on optimade.rst
> +The regular expressions are recorded below in two forms:
```suggestion
The regular expressions are recorded below in two forms, both compatible with the `OPTIMADE Regular Expression Format`.
```

2024-01-17 13:35 UTC, vaitkus commented on optimade.rst
> +The regular expressions are recorded below in two forms, both compatible with the `OPTIMADE Regular Expression Format`.
The PCRE version is currently not compatible with the `OPTIMADE Regular Expression Format` since it uses the `{2}` operator:
```
($symop_re)(,$symop_re){2}
```

2024-01-18 10:57 UTC, ml-evs commented on optimade.rst
> +The regular expressions are recorded below in two forms, both compatible with the `OPTIMADE Regular Expression Format`.
Hmm, yes... do we care about this enough to expand the PCRE regexp too or should I just reword the above to say the second example is compatible? @rartino had thoughts I think...

2024-01-18 14:14 UTC, rartino commented on optimade.rst
> +The regular expressions are recorded below in two forms, both compatible with the `OPTIMADE Regular Expression Format`.
Doesn't the declarations in the PCRE version (e.g. "$translations = '1\/2|[12]\/3|[1-3]\/4|[1-5]\/6';") already disqualify it? I think the point here is that the PCRE one is meant to be written as human-readable as possible, and the ECMA version is meant to be what we can put in the `pattern` field?

2024-01-18 14:29 UTC, vaitkus commented on optimade.rst
> +The regular expressions are recorded below in two forms, both compatible with the `OPTIMADE Regular Expression Format`.
Looks good, but could we replace "using declarations" with "using variable interpolation"?

2024-01-18 14:36 UTC, ml-evs commented on optimade.rst
> +The regular expressions are recorded below in two forms, both compatible with the `OPTIMADE Regular Expression Format`.
Updated above to just using "variables" as that's probably clear enough and more generic. Will commit

2024-03-22 07:06 UTC, sauliusg approved these changes
Cool test 'symops_pcre_to_ecma_001.sh', I think it is sufficient to safeguard that ECMA and PCER symop definitions do not diverge. Well done!

2024-03-22 07:37 UTC, merkys commented on optimade.rst
> +  The whitespace characters in these definitions are not significant; if used in Perl programs, these expressions MUST be processed with the :code:`/x` RE option.
```suggestion
  The whitespace characters in these definitions are not significant; if used in Perl programs, these expressions MUST be processed with the :code:`/x` RE modifier.
```
The proper term for this is "modifier", see https://perldoc.perl.org/perlre#Modifiers

2024-03-22 09:29 UTC, ml-evs commented on optimade.rst
> +Symmetry operation strings that comprise the :property:`space\_group\_symmetry\_operation\_xyz` property MUST conform to the following regular expressions.
```suggestion
Symmetry operation strings that comprise the :property:`space\_group\_symmetry\_operations\_xyz` property MUST conform to the following regular expressions.
```

2024-03-22 09:49 UTC, rartino commented on optimade.rst
> +- The regular expression is also provided in an expanded form:
```suggestion
- The regular expression is also provided in an expanded form as an OPTIMADE regex:
```

2024-03-22 09:49 UTC, rartino approved these changes

2024-03-22 09:50 UTC, merkys approved these changes

2024-03-22 09:51 UTC, sauliusg approved these changes

2024-03-22 09:53 UTC, merged