License property improvements
Materials-Consortia/OPTIMADE pull request #497
Opened 2024-01-17 09:03 UTC by merkys

This PR addresses issues raised in #494 by:

* defining what an unknown value for `available_licenses` means;
* including the structure of the database among the things that are covered by `available_licenses`;
* introducing `available_licenses_for_entries` to specify licenses for database content and metadata only (without its structure).

Fixes #494.

2024-01-17 09:27 UTC, vaitkus commented on optimade.rst
> +  - **available\_licenses**: List of `SPDX license identifiers <https://spdx.org/licenses/>` specifying a set of alternative licenses under which the client is granted access to all the content, meta
```suggestion
  - **available\_licenses**: List of `SPDX license identifiers <https://spdx.org/licenses/>`__ specifying a set of alternative licenses under which the client is granted access to all the content, metadata and structure of this database.
```

2024-01-17 09:27 UTC, vaitkus commented on optimade.rst
> +  - **available\_licenses\_for\_entries**: List of `SPDX license identifiers <https://spdx.org/licenses/>` specifying a set of alternative licenses under which the client is granted access to all the
```suggestion
  - **available\_licenses\_for\_entries**: List of `SPDX license identifiers <https://spdx.org/licenses/>`__ specifying a set of alternative licenses under which the client is granted access to all the content, metadata and data extracts that neither constitute substantial parts of the database nor encompass the structure of this database.
```

2024-01-17 09:27 UTC, vaitkus commented on optimade.rst
> +    Inclusion of a license identifier in the list is a commitment of the database that the rights are in place to grant clients access to all the content, metadata and database structure according to
```suggestion
    Inclusion of a license identifier in the list is a commitment of the database that the rights are in place to grant clients access to all the content, metadata and database structure according to the terms of any of these licenses (at the choice of the client).
```

2024-01-17 09:27 UTC, vaitkus commented on optimade.rst
> +    The remaining definition of this field is the same as for :field:`available_licenses`.
Maybe we should specify if the value of `available_licenses_for_entries` is unknown, the licenses from the `available_licenses` apply?

2024-01-17 09:49 UTC, merkys commented on optimade.rst
> +    The remaining definition of this field is the same as for :field:`available_licenses`.
Right, we should state how these two fields interact.

2024-01-17 13:44 UTC, ml-evs commented on optimade.rst
> +    An unknown value means that the database makes no commitment to its content, metadata and/or database structure data being covered by any of the SPDX licenses.
```suggestion
    An unknown value (i.e., :val:`null` or missing) means that the database makes no commitment to its content, metadata and/or database structure data being covered by any of the SPDX licenses.
```

2024-01-17 13:44 UTC, ml-evs commented on optimade.rst
> +    The remaining definition of this field is the same as for :field:`available_licenses`.
I think we need an example of the two scenarios, as this is quite abstract to me

2024-01-18 07:12 UTC, merkys commented on optimade.rst
> +    An unknown value means that the database makes no commitment to its content, metadata and/or database structure data being covered by any of the SPDX licenses.
I do not think this is necessary, as the specification already explains what "unknown value" means (it is a term in the specification), see "Properties with an unknown value" or "JSON Response Schema: Common Fields" sections for reference.

2024-01-18 07:20 UTC, merkys commented on optimade.rst
> +    The remaining definition of this field is the same as for :field:`available_licenses`.
@ml-evs let's say a whole database is licensed as `CC0-1.0`, and it chooses to output just `available_licenses` field with `available_licenses_for_entries` set to unknown, as `available_licenses_for_entries` only pertains to a subset of the database (entry data). As I understand, @vaitkus asked to clarify the text to mean "look at `available_licenses` if `available_licenses_for_entries` is missing". As @rartino nicely put yesterday, `available_licenses_for_entries` is just an additional list of licenses for entry data, on top of `available_licenses`.

Now consider the case when `available_licenses` is undefined, but `available_licenses_for_entries` contains `CC0-1.0`. This should mean that the entry data is licensed under `CC0-1.0`, but there should be no assumptions about the remaining copyrightable content of the database, apart from entry data. Does this make sense?

2024-01-18 14:07 UTC, rartino requested changes
I have a few proposals that I think helps improve the clarity and stay clear of things possible to be interpreted in unintentional ways.

2024-01-18 14:35 UTC, merkys commented on optimade.rst
> +    If :field:`available_licenses` is known, the licenses provided in :field:`available_licenses_for_entries` are additional alternative licenses granting access to individual database entries, their
Indeed, @vaitkus pointed this out to me too.

2024-01-18 14:40 UTC, merkys commented on optimade.rst
> +    If the database is available under multiple alternative licenses, identifiers of these multiple licenses SHOULD be provided to let clients know under which conditions they can be used.
Good point, I struggled with finding a better wording here.

2024-01-18 14:44 UTC, merkys commented on optimade.rst
> +  - **available\_licenses**: List of `SPDX license identifiers <https://spdx.org/licenses/>`__ specifying a set of alternative licenses under which the client is granted access to all the individual
I think this is fine, but I leave this unresolved as a reminder for myself to look into how other people describe similar cases (for example, how Debian describes software it distributes).

2024-01-18 14:49 UTC, rartino commented on optimade.rst
> +    The remaining definition of this field is the same as for :field:`available_licenses`.
> Now consider the case when `available_licenses` is undefined, but `available_licenses_for_entries` contains `CC0-1.0`. This should mean that the entry data is licensed under `CC0-1.0`, but there should be no assumptions about the remaining copyrightable content of the database, apart from entry data. Does this make sense?

This is precisely how I would interpret it (and what I want it to mean).

2024-01-19 12:17 UTC, merkys commented on optimade.rst
> +  - **available\_licenses**: List of `SPDX license identifiers <https://spdx.org/licenses/>`__ specifying a set of alternative licenses under which the client is granted access to all the individual
I looked at FAIRsharing (for example [FAIRsharing page for the COD](https://fairsharing.org/FAIRsharing.7mm5g5)), which lists databases and their licenses (among other properties), and it has the following header above each indicated database license:

>  This is a subset of licences recommended by the resource or most commonly used by its users.

This formulation seems to be written on the safer side, but FAIRsharing provides license links for informational use only while OPTIMADE aims to make them macine-readable and -actionable.

2024-02-09 15:51 UTC, rartino approved these changes
I guess I was holding off for other conversions to settle; but I think the current version is good enough to merge. Thanks for the work on this!

2024-02-09 16:05 UTC, merkys commented
Thanks @rartino. It would be nice to get approvals from more OPTIMADE adopters as this PR changes the interpretation of license properties (new in this release, though).

2024-02-14 14:37 UTC, rartino commented
@ml-evs In the spirit of cutting down on our PR log - since you've commented on this previously - do you still think there are remaining issues, or could you consider approving it?

@merkys 
> It would be nice to get approvals from more OPTIMADE adopters as this PR changes the interpretation of license properties (new in this release, though). 

This PR clarifies a few situations that were previously unclear, and extends what can be expressed. But as far as I see, no behavior that was well-defined with the previous PR *changes* by this PR. (Feel free to enlighten me if I'm missing something.)

2024-02-15 17:12 UTC, ml-evs approved these changes
I think the current wording is clear to me (and circumvents my need for examples). Thanks all!

2024-02-16 00:41 UTC, rartino commented
@merkys Are you comfortable 'resolving' the two remaining conversations and merging this? (Apparently leaving conversations unresolved is now a blocker that cannot be overridden - I'm not sure how I feel about that.)

2024-02-19 09:25 UTC, merkys commented
@rartino
> 
> @merkys
> 
> > It would be nice to get approvals from more OPTIMADE adopters as this PR changes the interpretation of license properties (new in this release, though).
> 
> This PR clarifies a few situations that were previously unclear, and extends what can be expressed. But as far as I see, no behavior that was well-defined with the previous PR _changes_ by this PR. (Feel free to enlighten me if I'm missing something.)

This is correct. I guess I tried to be extra-safe here with talking about the changes to the interpretation.

I have just marked all the remaining conversations about the text as resolved.

2024-02-20 07:43 UTC, merged